// Code generated by genparcelgo. DO NOT EDIT.

package classification

import (
	"github.com/xaionaro-go/binder/parcel"
)

type FieldClassification struct {
	// AutofillId: opaque type — not yet supported
}

var _ parcel.Parcelable = (*FieldClassification)(nil)

func (s *FieldClassification) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *FieldClassification) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
