package evs

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIEvsEnumerator = "android.hardware.automotive.evs.IEvsEnumerator"

const (
	TransactionIEvsEnumeratorCloseCamera             = binder.FirstCallTransaction + 0
	TransactionIEvsEnumeratorCloseDisplay            = binder.FirstCallTransaction + 1
	TransactionIEvsEnumeratorCloseUltrasonicsArray   = binder.FirstCallTransaction + 2
	TransactionIEvsEnumeratorGetCameraList           = binder.FirstCallTransaction + 3
	TransactionIEvsEnumeratorGetDisplayIdList        = binder.FirstCallTransaction + 4
	TransactionIEvsEnumeratorGetDisplayState         = binder.FirstCallTransaction + 5
	TransactionIEvsEnumeratorGetStreamList           = binder.FirstCallTransaction + 6
	TransactionIEvsEnumeratorGetUltrasonicsArrayList = binder.FirstCallTransaction + 7
	TransactionIEvsEnumeratorIsHardware              = binder.FirstCallTransaction + 8
	TransactionIEvsEnumeratorOpenCamera              = binder.FirstCallTransaction + 9
	TransactionIEvsEnumeratorOpenDisplay             = binder.FirstCallTransaction + 10
	TransactionIEvsEnumeratorOpenUltrasonicsArray    = binder.FirstCallTransaction + 11
	TransactionIEvsEnumeratorRegisterStatusCallback  = binder.FirstCallTransaction + 12
	TransactionIEvsEnumeratorGetDisplayStateById     = binder.FirstCallTransaction + 13
)

type IEvsEnumerator interface {
	AsBinder() binder.IBinder
	CloseCamera(ctx context.Context, carCamera IEvsCamera) error
	CloseDisplay(ctx context.Context, display IEvsDisplay) error
	CloseUltrasonicsArray(ctx context.Context, evsUltrasonicsArray IEvsUltrasonicsArray) error
	GetCameraList(ctx context.Context) ([]CameraDesc, error)
	GetDisplayIdList(ctx context.Context) ([]byte, error)
	GetDisplayState(ctx context.Context) (DisplayState, error)
	GetStreamList(ctx context.Context, description CameraDesc) ([]Stream, error)
	GetUltrasonicsArrayList(ctx context.Context) ([]UltrasonicsArrayDesc, error)
	IsHardware(ctx context.Context) (bool, error)
	OpenCamera(ctx context.Context, cameraId string, streamCfg Stream) (IEvsCamera, error)
	OpenDisplay(ctx context.Context, id int32) (IEvsDisplay, error)
	OpenUltrasonicsArray(ctx context.Context, ultrasonicsArrayId string) (IEvsUltrasonicsArray, error)
	RegisterStatusCallback(ctx context.Context, callback IEvsEnumeratorStatusCallback) error
	GetDisplayStateById(ctx context.Context, id int32) (DisplayState, error)
}

type EvsEnumeratorProxy struct {
	remote binder.IBinder
}

func NewEvsEnumeratorProxy(
	remote binder.IBinder,
) *EvsEnumeratorProxy {
	return &EvsEnumeratorProxy{remote: remote}
}

func (p *EvsEnumeratorProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IEvsEnumerator = (*EvsEnumeratorProxy)(nil)

func (p *EvsEnumeratorProxy) CloseCamera(
	ctx context.Context,
	carCamera IEvsCamera,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	binder.WriteBinderToParcel(ctx, _data, carCamera.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "closeCamera")
	if _err != nil {
		_code = TransactionIEvsEnumeratorCloseCamera
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *EvsEnumeratorProxy) CloseDisplay(
	ctx context.Context,
	display IEvsDisplay,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	binder.WriteBinderToParcel(ctx, _data, display.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "closeDisplay")
	if _err != nil {
		_code = TransactionIEvsEnumeratorCloseDisplay
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *EvsEnumeratorProxy) CloseUltrasonicsArray(
	ctx context.Context,
	evsUltrasonicsArray IEvsUltrasonicsArray,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	binder.WriteBinderToParcel(ctx, _data, evsUltrasonicsArray.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "closeUltrasonicsArray")
	if _err != nil {
		_code = TransactionIEvsEnumeratorCloseUltrasonicsArray
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *EvsEnumeratorProxy) GetCameraList(
	ctx context.Context,
) ([]CameraDesc, error) {
	var _result []CameraDesc
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getCameraList")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetCameraList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]CameraDesc, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *EvsEnumeratorProxy) GetDisplayIdList(
	ctx context.Context,
) ([]byte, error) {
	var _result []byte
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getDisplayIdList")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetDisplayIdList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]byte, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadPaddedByte()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *EvsEnumeratorProxy) GetDisplayState(
	ctx context.Context,
) (DisplayState, error) {
	var _result DisplayState
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getDisplayState")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetDisplayState
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_raw, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	_result = DisplayState(_raw)
	return _result, nil
}

func (p *EvsEnumeratorProxy) GetStreamList(
	ctx context.Context,
	description CameraDesc,
) ([]Stream, error) {
	var _result []Stream
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	_data.WriteInt32(1)
	if _err := description.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getStreamList")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetStreamList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]Stream, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *EvsEnumeratorProxy) GetUltrasonicsArrayList(
	ctx context.Context,
) ([]UltrasonicsArrayDesc, error) {
	var _result []UltrasonicsArrayDesc
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getUltrasonicsArrayList")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetUltrasonicsArrayList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]UltrasonicsArrayDesc, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *EvsEnumeratorProxy) IsHardware(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "isHardware")
	if _err != nil {
		_code = TransactionIEvsEnumeratorIsHardware
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *EvsEnumeratorProxy) OpenCamera(
	ctx context.Context,
	cameraId string,
	streamCfg Stream,
) (IEvsCamera, error) {
	var _result IEvsCamera
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	_data.WriteString16(cameraId)
	_data.WriteInt32(1)
	if _err := streamCfg.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "openCamera")
	if _err != nil {
		_code = TransactionIEvsEnumeratorOpenCamera
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewEvsCameraProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *EvsEnumeratorProxy) OpenDisplay(
	ctx context.Context,
	id int32,
) (IEvsDisplay, error) {
	var _result IEvsDisplay
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	_data.WriteInt32(id)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "openDisplay")
	if _err != nil {
		_code = TransactionIEvsEnumeratorOpenDisplay
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewEvsDisplayProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *EvsEnumeratorProxy) OpenUltrasonicsArray(
	ctx context.Context,
	ultrasonicsArrayId string,
) (IEvsUltrasonicsArray, error) {
	var _result IEvsUltrasonicsArray
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	_data.WriteString16(ultrasonicsArrayId)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "openUltrasonicsArray")
	if _err != nil {
		_code = TransactionIEvsEnumeratorOpenUltrasonicsArray
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewEvsUltrasonicsArrayProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *EvsEnumeratorProxy) RegisterStatusCallback(
	ctx context.Context,
	callback IEvsEnumeratorStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "registerStatusCallback")
	if _err != nil {
		_code = TransactionIEvsEnumeratorRegisterStatusCallback
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *EvsEnumeratorProxy) GetDisplayStateById(
	ctx context.Context,
	id int32,
) (DisplayState, error) {
	var _result DisplayState
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIEvsEnumerator)
	_data.WriteInt32(id)

	_code, _err := p.remote.ResolveCode(DescriptorIEvsEnumerator, "getDisplayStateById")
	if _err != nil {
		_code = TransactionIEvsEnumeratorGetDisplayStateById
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_raw, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	_result = DisplayState(_raw)
	return _result, nil
}

// EvsEnumeratorStub dispatches incoming binder transactions
// to a typed IEvsEnumerator implementation.
type EvsEnumeratorStub struct {
	Impl IEvsEnumerator
}

var _ binder.TransactionReceiver = (*EvsEnumeratorStub)(nil)

func (s *EvsEnumeratorStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIEvsEnumeratorCloseCamera:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_carCamera IEvsCamera
		_ = _arg_carCamera
		_err := s.Impl.CloseCamera(ctx, _arg_carCamera)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIEvsEnumeratorCloseDisplay:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_display IEvsDisplay
		_ = _arg_display
		_err := s.Impl.CloseDisplay(ctx, _arg_display)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIEvsEnumeratorCloseUltrasonicsArray:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_evsUltrasonicsArray IEvsUltrasonicsArray
		_ = _arg_evsUltrasonicsArray
		_err := s.Impl.CloseUltrasonicsArray(ctx, _arg_evsUltrasonicsArray)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIEvsEnumeratorGetCameraList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetCameraList(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorGetDisplayIdList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetDisplayIdList(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorGetDisplayState:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetDisplayState(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(int32(_result))
		return _reply, nil
	case TransactionIEvsEnumeratorGetStreamList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_description CameraDesc
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_description.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.GetStreamList(ctx, _arg_description)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorGetUltrasonicsArrayList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetUltrasonicsArrayList(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorIsHardware:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsHardware(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIEvsEnumeratorOpenCamera:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_cameraId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_streamCfg Stream
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_streamCfg.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.OpenCamera(ctx, _arg_cameraId, _arg_streamCfg)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorOpenDisplay:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_id, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.OpenDisplay(ctx, _arg_id)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorOpenUltrasonicsArray:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_ultrasonicsArrayId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.OpenUltrasonicsArray(ctx, _arg_ultrasonicsArrayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIEvsEnumeratorRegisterStatusCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IEvsEnumeratorStatusCallback
		_ = _arg_callback
		_err := s.Impl.RegisterStatusCallback(ctx, _arg_callback)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIEvsEnumeratorGetDisplayStateById:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_id, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetDisplayStateById(ctx, _arg_id)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(int32(_result))
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IEvsEnumeratorServer is the server-side interface that user implementations
// provide to NewEvsEnumeratorStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IEvsEnumeratorServer interface {
	CloseCamera(ctx context.Context, carCamera IEvsCamera) error
	CloseDisplay(ctx context.Context, display IEvsDisplay) error
	CloseUltrasonicsArray(ctx context.Context, evsUltrasonicsArray IEvsUltrasonicsArray) error
	GetCameraList(ctx context.Context) ([]CameraDesc, error)
	GetDisplayIdList(ctx context.Context) ([]byte, error)
	GetDisplayState(ctx context.Context) (DisplayState, error)
	GetStreamList(ctx context.Context, description CameraDesc) ([]Stream, error)
	GetUltrasonicsArrayList(ctx context.Context) ([]UltrasonicsArrayDesc, error)
	IsHardware(ctx context.Context) (bool, error)
	OpenCamera(ctx context.Context, cameraId string, streamCfg Stream) (IEvsCamera, error)
	OpenDisplay(ctx context.Context, id int32) (IEvsDisplay, error)
	OpenUltrasonicsArray(ctx context.Context, ultrasonicsArrayId string) (IEvsUltrasonicsArray, error)
	RegisterStatusCallback(ctx context.Context, callback IEvsEnumeratorStatusCallback) error
	GetDisplayStateById(ctx context.Context, id int32) (DisplayState, error)
}

type evsEnumeratorStubWrapper struct {
	impl       IEvsEnumeratorServer
	stubBinder *binder.StubBinder
}

func (w *evsEnumeratorStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *evsEnumeratorStubWrapper) CloseCamera(
	ctx context.Context,
	carCamera IEvsCamera,
) error {
	return w.impl.CloseCamera(ctx, carCamera)
}

func (w *evsEnumeratorStubWrapper) CloseDisplay(
	ctx context.Context,
	display IEvsDisplay,
) error {
	return w.impl.CloseDisplay(ctx, display)
}

func (w *evsEnumeratorStubWrapper) CloseUltrasonicsArray(
	ctx context.Context,
	evsUltrasonicsArray IEvsUltrasonicsArray,
) error {
	return w.impl.CloseUltrasonicsArray(ctx, evsUltrasonicsArray)
}

func (w *evsEnumeratorStubWrapper) GetCameraList(
	ctx context.Context,
) ([]CameraDesc, error) {
	return w.impl.GetCameraList(ctx)
}

func (w *evsEnumeratorStubWrapper) GetDisplayIdList(
	ctx context.Context,
) ([]byte, error) {
	return w.impl.GetDisplayIdList(ctx)
}

func (w *evsEnumeratorStubWrapper) GetDisplayState(
	ctx context.Context,
) (DisplayState, error) {
	return w.impl.GetDisplayState(ctx)
}

func (w *evsEnumeratorStubWrapper) GetStreamList(
	ctx context.Context,
	description CameraDesc,
) ([]Stream, error) {
	return w.impl.GetStreamList(ctx, description)
}

func (w *evsEnumeratorStubWrapper) GetUltrasonicsArrayList(
	ctx context.Context,
) ([]UltrasonicsArrayDesc, error) {
	return w.impl.GetUltrasonicsArrayList(ctx)
}

func (w *evsEnumeratorStubWrapper) IsHardware(
	ctx context.Context,
) (bool, error) {
	return w.impl.IsHardware(ctx)
}

func (w *evsEnumeratorStubWrapper) OpenCamera(
	ctx context.Context,
	cameraId string,
	streamCfg Stream,
) (IEvsCamera, error) {
	return w.impl.OpenCamera(ctx, cameraId, streamCfg)
}

func (w *evsEnumeratorStubWrapper) OpenDisplay(
	ctx context.Context,
	id int32,
) (IEvsDisplay, error) {
	return w.impl.OpenDisplay(ctx, id)
}

func (w *evsEnumeratorStubWrapper) OpenUltrasonicsArray(
	ctx context.Context,
	ultrasonicsArrayId string,
) (IEvsUltrasonicsArray, error) {
	return w.impl.OpenUltrasonicsArray(ctx, ultrasonicsArrayId)
}

func (w *evsEnumeratorStubWrapper) RegisterStatusCallback(
	ctx context.Context,
	callback IEvsEnumeratorStatusCallback,
) error {
	return w.impl.RegisterStatusCallback(ctx, callback)
}

func (w *evsEnumeratorStubWrapper) GetDisplayStateById(
	ctx context.Context,
	id int32,
) (DisplayState, error) {
	return w.impl.GetDisplayStateById(ctx, id)
}

var _ IEvsEnumerator = (*evsEnumeratorStubWrapper)(nil)

// NewEvsEnumeratorStub creates a server-side IEvsEnumerator wrapping the given
// server implementation. The returned value satisfies IEvsEnumerator
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewEvsEnumeratorStub(
	impl IEvsEnumeratorServer,
) IEvsEnumerator {
	wrapper := &evsEnumeratorStubWrapper{impl: impl}
	stub := &EvsEnumeratorStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
