package evs

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type RotationQuaternion struct {
	X float32
	Y float32
	Z float32
	W float32
}

var _ parcel.Parcelable = (*RotationQuaternion)(nil)

func (s *RotationQuaternion) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.X)
	p.WriteFloat32(s.Y)
	p.WriteFloat32(s.Z)
	p.WriteFloat32(s.W)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *RotationQuaternion) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.X, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.Y, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.Z, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.W, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
