package telephony

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBootstrapAuthenticationCallback = "android.telephony.IBootstrapAuthenticationCallback"

const (
	TransactionIBootstrapAuthenticationCallbackOnKeysAvailable         = binder.FirstCallTransaction + 0
	TransactionIBootstrapAuthenticationCallbackOnAuthenticationFailure = binder.FirstCallTransaction + 1
)

const (
	MethodIBootstrapAuthenticationCallbackOnKeysAvailable         = "onKeysAvailable"
	MethodIBootstrapAuthenticationCallbackOnAuthenticationFailure = "onAuthenticationFailure"
)

type IBootstrapAuthenticationCallback interface {
	AsBinder() binder.IBinder
	OnKeysAvailable(ctx context.Context, token int32, gbaKey []byte, btId string) error
	OnAuthenticationFailure(ctx context.Context, token int32, reason int32) error
}

type BootstrapAuthenticationCallbackProxy struct {
	Remote binder.IBinder
}

func NewBootstrapAuthenticationCallbackProxy(
	remote binder.IBinder,
) *BootstrapAuthenticationCallbackProxy {
	return &BootstrapAuthenticationCallbackProxy{Remote: remote}
}

func (p *BootstrapAuthenticationCallbackProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IBootstrapAuthenticationCallback = (*BootstrapAuthenticationCallbackProxy)(nil)

func (p *BootstrapAuthenticationCallbackProxy) OnKeysAvailable(
	ctx context.Context,
	token int32,
	gbaKey []byte,
	btId string,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBootstrapAuthenticationCallback)
	_data.WriteInt32(token)
	_data.WriteByteArray(gbaKey)
	_data.WriteString16(btId)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBootstrapAuthenticationCallback, MethodIBootstrapAuthenticationCallbackOnKeysAvailable)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBootstrapAuthenticationCallback, MethodIBootstrapAuthenticationCallbackOnKeysAvailable, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BootstrapAuthenticationCallbackProxy) OnAuthenticationFailure(
	ctx context.Context,
	token int32,
	reason int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIBootstrapAuthenticationCallback)
	_data.WriteInt32(token)
	_data.WriteInt32(reason)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIBootstrapAuthenticationCallback, MethodIBootstrapAuthenticationCallbackOnAuthenticationFailure)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIBootstrapAuthenticationCallback, MethodIBootstrapAuthenticationCallbackOnAuthenticationFailure, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// BootstrapAuthenticationCallbackStub dispatches incoming binder transactions
// to a typed IBootstrapAuthenticationCallback implementation.
type BootstrapAuthenticationCallbackStub struct {
	Impl      IBootstrapAuthenticationCallback
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*BootstrapAuthenticationCallbackStub)(nil)

func (s *BootstrapAuthenticationCallbackStub) Descriptor() string {
	return DescriptorIBootstrapAuthenticationCallback
}

func (s *BootstrapAuthenticationCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIBootstrapAuthenticationCallbackOnKeysAvailable:
		_arg_token, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_gbaKey []byte
		{
			_bytes, _err := _data.ReadByteArray()
			if _err != nil {
				return nil, _err
			}
			_arg_gbaKey = _bytes
		}
		_arg_btId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnKeysAvailable(ctx, _arg_token, _arg_gbaKey, _arg_btId)
		return nil, _err
	case TransactionIBootstrapAuthenticationCallbackOnAuthenticationFailure:
		_arg_token, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnAuthenticationFailure(ctx, _arg_token, _arg_reason)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IBootstrapAuthenticationCallbackServer is the server-side interface that user implementations
// provide to NewBootstrapAuthenticationCallbackStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IBootstrapAuthenticationCallbackServer interface {
	OnKeysAvailable(ctx context.Context, token int32, gbaKey []byte, btId string) error
	OnAuthenticationFailure(ctx context.Context, token int32, reason int32) error
}

type bootstrapAuthenticationCallbackStubWrapper struct {
	impl       IBootstrapAuthenticationCallbackServer
	stubBinder *binder.StubBinder
}

func (w *bootstrapAuthenticationCallbackStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *bootstrapAuthenticationCallbackStubWrapper) OnKeysAvailable(
	ctx context.Context,
	token int32,
	gbaKey []byte,
	btId string,
) error {
	return w.impl.OnKeysAvailable(ctx, token, gbaKey, btId)
}

func (w *bootstrapAuthenticationCallbackStubWrapper) OnAuthenticationFailure(
	ctx context.Context,
	token int32,
	reason int32,
) error {
	return w.impl.OnAuthenticationFailure(ctx, token, reason)
}

var _ IBootstrapAuthenticationCallback = (*bootstrapAuthenticationCallbackStubWrapper)(nil)

// NewBootstrapAuthenticationCallbackStub creates a server-side IBootstrapAuthenticationCallback wrapping the given
// server implementation. The returned value satisfies IBootstrapAuthenticationCallback
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewBootstrapAuthenticationCallbackStub(
	impl IBootstrapAuthenticationCallbackServer,
) IBootstrapAuthenticationCallback {
	wrapper := &bootstrapAuthenticationCallbackStubWrapper{impl: impl}
	stub := &BootstrapAuthenticationCallbackStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
