package media

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type AudioProfileSys struct {
	IsDynamicFormat   bool
	IsDynamicChannels bool
	IsDynamicRate     bool
}

var _ parcel.Parcelable = (*AudioProfileSys)(nil)

func (s *AudioProfileSys) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteBool(s.IsDynamicFormat)
	p.WriteBool(s.IsDynamicChannels)
	p.WriteBool(s.IsDynamicRate)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *AudioProfileSys) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.IsDynamicFormat, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	s.IsDynamicChannels, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	s.IsDynamicRate, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
