package media

// Code generated by aidlgen. DO NOT EDIT.

type AudioMixerBehavior int32

const (
	AudioMixerBehaviorINVALID    AudioMixerBehavior = -1
	AudioMixerBehaviorDEFAULT    AudioMixerBehavior = 0
	AudioMixerBehaviorBitPerfect AudioMixerBehavior = 1
)
