package media

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type FadeManagerConfiguration struct {
	FadeState                     int32
	FadeOutDurationMillis         int64
	FadeInDurationMillis          int64
	FadeInDelayForOffendersMillis int64
}

var _ parcel.Parcelable = (*FadeManagerConfiguration)(nil)

func (s *FadeManagerConfiguration) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.FadeState)
	p.WriteInt64(s.FadeOutDurationMillis)
	p.WriteInt64(s.FadeInDurationMillis)
	p.WriteInt64(s.FadeInDelayForOffendersMillis)
	p.WriteInt32(-1) // null UsageToFadeWrapperMap
	p.WriteInt32(-1) // null AttrToFadeWrapperMap
	p.WriteInt32(-1) // null ToArray()
	p.WriteInt32(-1) // null ToArray()
	p.WriteInt32(-1) // null ToArray()
	p.WriteInt32(-1) // null ToArray()
	p.WriteInt32(-1) // null UnfadeableAudioAttributes
	return nil
}

func (s *FadeManagerConfiguration) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.FadeState, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.FadeOutDurationMillis, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.FadeInDurationMillis, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.FadeInDelayForOffendersMillis, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	return nil // opaque UsageToFadeWrapperMap: cannot skip without known wire format
}
