package media

import (
	"context"
	"fmt"
	Spatialization "github.com/xaionaro-go/binder/android/media/audio/common/Spatialization"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorINativeSpatializerCallback = "android.media.INativeSpatializerCallback"

const (
	TransactionINativeSpatializerCallbackOnLevelChanged  = binder.FirstCallTransaction + 0
	TransactionINativeSpatializerCallbackOnOutputChanged = binder.FirstCallTransaction + 1
)

type INativeSpatializerCallback interface {
	AsBinder() binder.IBinder
	OnLevelChanged(ctx context.Context, level Spatialization.Level) error
	OnOutputChanged(ctx context.Context, output int32) error
}

type NativeSpatializerCallbackProxy struct {
	remote binder.IBinder
}

func NewNativeSpatializerCallbackProxy(
	remote binder.IBinder,
) *NativeSpatializerCallbackProxy {
	return &NativeSpatializerCallbackProxy{remote: remote}
}

func (p *NativeSpatializerCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ INativeSpatializerCallback = (*NativeSpatializerCallbackProxy)(nil)

func (p *NativeSpatializerCallbackProxy) OnLevelChanged(
	ctx context.Context,
	level Spatialization.Level,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorINativeSpatializerCallback)

	_code, _err := p.remote.ResolveCode(DescriptorINativeSpatializerCallback, "onLevelChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *NativeSpatializerCallbackProxy) OnOutputChanged(
	ctx context.Context,
	output int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorINativeSpatializerCallback)
	_data.WriteInt32(output)

	_code, _err := p.remote.ResolveCode(DescriptorINativeSpatializerCallback, "onOutputChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// NativeSpatializerCallbackStub dispatches incoming binder transactions
// to a typed INativeSpatializerCallback implementation.
type NativeSpatializerCallbackStub struct {
	Impl INativeSpatializerCallback
}

var _ binder.TransactionReceiver = (*NativeSpatializerCallbackStub)(nil)

func (s *NativeSpatializerCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionINativeSpatializerCallbackOnLevelChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_level Spatialization.Level
		_err := s.Impl.OnLevelChanged(ctx, _arg_level)
		_ = _err
		return nil, nil
	case TransactionINativeSpatializerCallbackOnOutputChanged:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_output, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnOutputChanged(ctx, _arg_output)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
