package selectiontoolbar

import (
	"github.com/xaionaro-go/binder/tools/pkg/testutil"
	"testing"
)

// Code generated by aospgen. DO NOT EDIT.

func TestSmoke_SelectionToolbarCallbackProxy(t *testing.T) {
	mock := testutil.NewMockBinder()
	proxy := NewSelectionToolbarCallbackProxy(mock)
	result := testutil.SmokeTestAllMethods(t, proxy)
	t.Logf("SelectionToolbarCallbackProxy: %d/%d passed, %d panicked, %d failed",
		result.Passed, result.Total, result.Panicked, result.Failed)
}

func TestSmoke_SelectionToolbarManagerProxy(t *testing.T) {
	mock := testutil.NewMockBinder()
	proxy := NewSelectionToolbarManagerProxy(mock)
	result := testutil.SmokeTestAllMethods(t, proxy)
	t.Logf("SelectionToolbarManagerProxy: %d/%d passed, %d panicked, %d failed",
		result.Passed, result.Total, result.Panicked, result.Failed)
}
