package signal

import (
	"context"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAudioSignalInfoListener = "android.media.tv.extension.signal.IAudioSignalInfoListener"

const (
	TransactionIAudioSignalInfoListenerOnAudioSignalInfoChanged = binder.FirstCallTransaction + 0
)

type IAudioSignalInfoListener interface {
	AsBinder() binder.IBinder
	OnAudioSignalInfoChanged(ctx context.Context, sessionToken string, changedSignalInfo os.Bundle) error
}

type AudioSignalInfoListenerProxy struct {
	remote binder.IBinder
}

func NewAudioSignalInfoListenerProxy(
	remote binder.IBinder,
) *AudioSignalInfoListenerProxy {
	return &AudioSignalInfoListenerProxy{remote: remote}
}

func (p *AudioSignalInfoListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAudioSignalInfoListener = (*AudioSignalInfoListenerProxy)(nil)

func (p *AudioSignalInfoListenerProxy) OnAudioSignalInfoChanged(
	ctx context.Context,
	sessionToken string,
	changedSignalInfo os.Bundle,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAudioSignalInfoListener)
	_data.WriteString16(sessionToken)
	if _err := changedSignalInfo.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIAudioSignalInfoListener, "onAudioSignalInfoChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
