package ranging

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type ComplexNumber struct {
	Real      float64
	Imaginary float64
}

var _ parcel.Parcelable = (*ComplexNumber)(nil)

func (s *ComplexNumber) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat64(s.Real)
	p.WriteFloat64(s.Imaginary)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *ComplexNumber) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.Real, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}

	s.Imaginary, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
