// Code generated by genparcelgo. DO NOT EDIT.

package euicc

import (
	"github.com/xaionaro-go/binder/parcel"
)

type DownloadSubscriptionResult struct {
	Result           int32
	ResolvableErrors int32
	CardId           int32
}

var _ parcel.Parcelable = (*DownloadSubscriptionResult)(nil)

func (s *DownloadSubscriptionResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Result)
	p.WriteInt32(s.ResolvableErrors)
	p.WriteInt32(s.CardId)
	return nil
}

func (s *DownloadSubscriptionResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Result, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.ResolvableErrors, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.CardId, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	return nil
}
