package window

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIScreenRecordingCallback = "android.window.IScreenRecordingCallback"

const (
	TransactionIScreenRecordingCallbackOnScreenRecordingStateChanged = binder.FirstCallTransaction + 0
)

type IScreenRecordingCallback interface {
	AsBinder() binder.IBinder
	OnScreenRecordingStateChanged(ctx context.Context, visibleInScreenRecording bool) error
}

type ScreenRecordingCallbackProxy struct {
	remote binder.IBinder
}

func NewScreenRecordingCallbackProxy(
	remote binder.IBinder,
) *ScreenRecordingCallbackProxy {
	return &ScreenRecordingCallbackProxy{remote: remote}
}

func (p *ScreenRecordingCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IScreenRecordingCallback = (*ScreenRecordingCallbackProxy)(nil)

func (p *ScreenRecordingCallbackProxy) OnScreenRecordingStateChanged(
	ctx context.Context,
	visibleInScreenRecording bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIScreenRecordingCallback)
	_data.WriteBool(visibleInScreenRecording)

	_code, _err := p.remote.ResolveCode(DescriptorIScreenRecordingCallback, "onScreenRecordingStateChanged")
	if _err != nil {
		_code = TransactionIScreenRecordingCallbackOnScreenRecordingStateChanged
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ScreenRecordingCallbackStub dispatches incoming binder transactions
// to a typed IScreenRecordingCallback implementation.
type ScreenRecordingCallbackStub struct {
	Impl IScreenRecordingCallback
}

var _ binder.TransactionReceiver = (*ScreenRecordingCallbackStub)(nil)

func (s *ScreenRecordingCallbackStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIScreenRecordingCallbackOnScreenRecordingStateChanged:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_visibleInScreenRecording, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnScreenRecordingStateChanged(ctx, _arg_visibleInScreenRecording)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IScreenRecordingCallbackServer is the server-side interface that user implementations
// provide to NewScreenRecordingCallbackStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IScreenRecordingCallbackServer interface {
	OnScreenRecordingStateChanged(ctx context.Context, visibleInScreenRecording bool) error
}

type screenRecordingCallbackStubWrapper struct {
	impl       IScreenRecordingCallbackServer
	stubBinder *binder.StubBinder
}

func (w *screenRecordingCallbackStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *screenRecordingCallbackStubWrapper) OnScreenRecordingStateChanged(
	ctx context.Context,
	visibleInScreenRecording bool,
) error {
	return w.impl.OnScreenRecordingStateChanged(ctx, visibleInScreenRecording)
}

var _ IScreenRecordingCallback = (*screenRecordingCallbackStubWrapper)(nil)

// NewScreenRecordingCallbackStub creates a server-side IScreenRecordingCallback wrapping the given
// server implementation. The returned value satisfies IScreenRecordingCallback
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewScreenRecordingCallbackStub(
	impl IScreenRecordingCallbackServer,
) IScreenRecordingCallback {
	wrapper := &screenRecordingCallbackStubWrapper{impl: impl}
	stub := &ScreenRecordingCallbackStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
