package tuner

import (
	"context"
	"fmt"
	tvTuner "github.com/xaionaro-go/binder/android/hardware/tv/tuner"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITunerDemux = "android.media.tv.tuner.ITunerDemux"

const (
	TransactionITunerDemuxSetFrontendDataSource     = binder.FirstCallTransaction + 0
	TransactionITunerDemuxSetFrontendDataSourceById = binder.FirstCallTransaction + 1
	TransactionITunerDemuxOpenFilter                = binder.FirstCallTransaction + 2
	TransactionITunerDemuxOpenTimeFilter            = binder.FirstCallTransaction + 3
	TransactionITunerDemuxGetAvSyncHwId             = binder.FirstCallTransaction + 4
	TransactionITunerDemuxGetAvSyncTime             = binder.FirstCallTransaction + 5
	TransactionITunerDemuxOpenDvr                   = binder.FirstCallTransaction + 6
	TransactionITunerDemuxConnectCiCam              = binder.FirstCallTransaction + 7
	TransactionITunerDemuxDisconnectCiCam           = binder.FirstCallTransaction + 8
	TransactionITunerDemuxClose                     = binder.FirstCallTransaction + 9
)

type ITunerDemux interface {
	AsBinder() binder.IBinder
	SetFrontendDataSource(ctx context.Context, frontend ITunerFrontend) error
	SetFrontendDataSourceById(ctx context.Context, frontendId int32) error
	OpenFilter(ctx context.Context, type_ tvTuner.DemuxFilterType, bufferSize int32, cb ITunerFilterCallback) (ITunerFilter, error)
	OpenTimeFilter(ctx context.Context) (ITunerTimeFilter, error)
	GetAvSyncHwId(ctx context.Context, tunerFilter ITunerFilter) (int32, error)
	GetAvSyncTime(ctx context.Context, avSyncHwId int32) (int64, error)
	OpenDvr(ctx context.Context, dvbType tvTuner.DvrType, bufferSize int32, cb ITunerDvrCallback) (ITunerDvr, error)
	ConnectCiCam(ctx context.Context, ciCamId int32) error
	DisconnectCiCam(ctx context.Context) error
	Close(ctx context.Context) error
}

type TunerDemuxProxy struct {
	remote binder.IBinder
}

func NewTunerDemuxProxy(
	remote binder.IBinder,
) *TunerDemuxProxy {
	return &TunerDemuxProxy{remote: remote}
}

func (p *TunerDemuxProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITunerDemux = (*TunerDemuxProxy)(nil)

func (p *TunerDemuxProxy) SetFrontendDataSource(
	ctx context.Context,
	frontend ITunerFrontend,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteStrongBinder(frontend.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "setFrontendDataSource")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *TunerDemuxProxy) SetFrontendDataSourceById(
	ctx context.Context,
	frontendId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteInt32(frontendId)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "setFrontendDataSourceById")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *TunerDemuxProxy) OpenFilter(
	ctx context.Context,
	type_ tvTuner.DemuxFilterType,
	bufferSize int32,
	cb ITunerFilterCallback,
) (ITunerFilter, error) {
	var _result ITunerFilter
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteInt32(1)
	if _err := type_.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(bufferSize)
	_data.WriteStrongBinder(cb.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "openFilter")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewTunerFilterProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *TunerDemuxProxy) OpenTimeFilter(
	ctx context.Context,
) (ITunerTimeFilter, error) {
	var _result ITunerTimeFilter
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "openTimeFilter")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewTunerTimeFilterProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *TunerDemuxProxy) GetAvSyncHwId(
	ctx context.Context,
	tunerFilter ITunerFilter,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteStrongBinder(tunerFilter.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "getAvSyncHwId")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *TunerDemuxProxy) GetAvSyncTime(
	ctx context.Context,
	avSyncHwId int32,
) (int64, error) {
	var _result int64
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteInt32(avSyncHwId)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "getAvSyncTime")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *TunerDemuxProxy) OpenDvr(
	ctx context.Context,
	dvbType tvTuner.DvrType,
	bufferSize int32,
	cb ITunerDvrCallback,
) (ITunerDvr, error) {
	var _result ITunerDvr
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WritePaddedByte(byte(dvbType))
	_data.WriteInt32(bufferSize)
	_data.WriteStrongBinder(cb.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "openDvr")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = NewTunerDvrProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

func (p *TunerDemuxProxy) ConnectCiCam(
	ctx context.Context,
	ciCamId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)
	_data.WriteInt32(ciCamId)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "connectCiCam")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *TunerDemuxProxy) DisconnectCiCam(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "disconnectCiCam")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *TunerDemuxProxy) Close(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITunerDemux)

	_code, _err := p.remote.ResolveCode(DescriptorITunerDemux, "close")
	if _err != nil {
		return _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// TunerDemuxStub dispatches incoming binder transactions
// to a typed ITunerDemux implementation.
type TunerDemuxStub struct {
	Impl ITunerDemux
}

var _ binder.TransactionReceiver = (*TunerDemuxStub)(nil)

func (s *TunerDemuxStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionITunerDemuxSetFrontendDataSource:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_frontend ITunerFrontend
		_ = _arg_frontend
		_err := s.Impl.SetFrontendDataSource(ctx, _arg_frontend)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionITunerDemuxSetFrontendDataSourceById:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_frontendId, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetFrontendDataSourceById(ctx, _arg_frontendId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionITunerDemuxOpenFilter:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_type_ tvTuner.DemuxFilterType
		{
			_nullInd, _err := data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_type_.UnmarshalParcel(data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_bufferSize, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_cb ITunerFilterCallback
		_ = _arg_cb
		_result, _err := s.Impl.OpenFilter(ctx, _arg_type_, _arg_bufferSize, _arg_cb)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionITunerDemuxOpenTimeFilter:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.OpenTimeFilter(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionITunerDemuxGetAvSyncHwId:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_tunerFilter ITunerFilter
		_ = _arg_tunerFilter
		_result, _err := s.Impl.GetAvSyncHwId(ctx, _arg_tunerFilter)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionITunerDemuxGetAvSyncTime:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_avSyncHwId, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetAvSyncTime(ctx, _arg_avSyncHwId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt64(_result)
		return _reply, nil
	case TransactionITunerDemuxOpenDvr:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_raw_dvbType, _err := data.ReadPaddedByte()
		if _err != nil {
			return nil, _err
		}
		_arg_dvbType := tvTuner.DvrType(_raw_dvbType)
		_arg_bufferSize, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_cb ITunerDvrCallback
		_ = _arg_cb
		_result, _err := s.Impl.OpenDvr(ctx, _arg_dvbType, _arg_bufferSize, _arg_cb)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionITunerDemuxConnectCiCam:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_ciCamId, _err := data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.ConnectCiCam(ctx, _arg_ciCamId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionITunerDemuxDisconnectCiCam:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.DisconnectCiCam(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionITunerDemuxClose:
		if _, _err := data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.Close(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}
