package rollback

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PackageRollbackInfo struct {
	IsApex      bool
	IsApkInApex bool
}

var _ parcel.Parcelable = (*PackageRollbackInfo)(nil)

func (s *PackageRollbackInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(-1) // null VersionRolledBackFrom
	p.WriteInt32(-1) // null VersionRolledBackTo
	p.WriteBool(s.IsApex)
	p.WriteBool(s.IsApkInApex)
	return nil
}

func (s *PackageRollbackInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	return nil // opaque VersionRolledBackFrom: cannot skip without known wire format
}
