// Code generated by genparcelgo. DO NOT EDIT.

package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

type CorrelationVector struct {
	SamplingWidthMeters            float64
	SamplingStartMeters            float64
	FrequencyOffsetMetersPerSecond float64
	// Magnitude.length: opaque type — not yet supported
	// Magnitude: opaque type — not yet supported
}

var _ parcel.Parcelable = (*CorrelationVector)(nil)

func (s *CorrelationVector) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteFloat64(s.SamplingWidthMeters)
	p.WriteFloat64(s.SamplingStartMeters)
	p.WriteFloat64(s.FrequencyOffsetMetersPerSecond)
	return nil
}

func (s *CorrelationVector) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.SamplingWidthMeters, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.SamplingStartMeters, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.FrequencyOffsetMetersPerSecond, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
