// Code generated by genparcelgo. DO NOT EDIT.

package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

type Criteria struct {
	HorizontalAccuracy int32
	VerticalAccuracy   int32
	SpeedAccuracy      int32
	BearingAccuracy    int32
	PowerRequirement   int32
	// AltitudeRequired?1:0: opaque type — not yet supported
	// BearingRequired?1:0: opaque type — not yet supported
	// SpeedRequired?1:0: opaque type — not yet supported
	// CostAllowed?1:0: opaque type — not yet supported
}

var _ parcel.Parcelable = (*Criteria)(nil)

func (s *Criteria) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.HorizontalAccuracy)
	p.WriteInt32(s.VerticalAccuracy)
	p.WriteInt32(s.SpeedAccuracy)
	p.WriteInt32(s.BearingAccuracy)
	p.WriteInt32(s.PowerRequirement)
	return nil
}

func (s *Criteria) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.HorizontalAccuracy, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.VerticalAccuracy, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.SpeedAccuracy, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.BearingAccuracy, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.PowerRequirement, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
