package location

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GnssMeasurementsEvent struct {
	Flag           int32
	IsFullTracking bool
}

var _ parcel.Parcelable = (*GnssMeasurementsEvent)(nil)

func (s *GnssMeasurementsEvent) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Flag)
	p.WriteInt32(0)  // null Clock
	p.WriteInt32(-1) // null Measurements
	p.WriteInt32(-1) // null GnssAgcs
	p.WriteBool(s.IsFullTracking)
	return nil
}

func (s *GnssMeasurementsEvent) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Flag, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null Clock: cannot skip unknown-size typed object
		}
	}
	return nil // opaque Measurements: cannot skip without known wire format
}
