package location

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GnssMeasurementCorrections struct {
	LatitudeDegrees                     float64
	LongitudeDegrees                    float64
	AltitudeMeters                      float64
	HorizontalPositionUncertaintyMeters float64
	VerticalPositionUncertaintyMeters   float64
	ToaGpsNanosecondsOfWeek             int64
	HasEnvironmentBearing               bool
}

var _ parcel.Parcelable = (*GnssMeasurementCorrections)(nil)

func (s *GnssMeasurementCorrections) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteFloat64(s.LatitudeDegrees)
	p.WriteFloat64(s.LongitudeDegrees)
	p.WriteFloat64(s.AltitudeMeters)
	p.WriteFloat64(s.HorizontalPositionUncertaintyMeters)
	p.WriteFloat64(s.VerticalPositionUncertaintyMeters)
	p.WriteInt64(s.ToaGpsNanosecondsOfWeek)
	p.WriteInt32(0) // null SingleSatCorrectionList
	p.WriteBool(s.HasEnvironmentBearing)
	p.WriteInt32(0) // null EnvironmentBearingDegrees
	p.WriteInt32(0) // null EnvironmentBearingUncertaintyDegrees
	return nil
}

func (s *GnssMeasurementCorrections) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.LatitudeDegrees, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.LongitudeDegrees, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.AltitudeMeters, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.HorizontalPositionUncertaintyMeters, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.VerticalPositionUncertaintyMeters, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.ToaGpsNanosecondsOfWeek, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	s.HasEnvironmentBearing, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null EnvironmentBearingDegrees: cannot skip unknown-size typed object
		}
	}
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null EnvironmentBearingUncertaintyDegrees: cannot skip unknown-size typed object
		}
	}
	return nil
}
