package accessibility

import (
	"context"
	"fmt"
	content "github.com/xaionaro-go/binder/android/content"
	accessibilityIAccessibilityManager "github.com/xaionaro-go/binder/android/view/accessibility/IAccessibilityManager"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAccessibilityManager = "android.view.accessibility.IAccessibilityManager"

const (
	TransactionIAccessibilityManagerInterrupt                                    = binder.FirstCallTransaction + 0
	TransactionIAccessibilityManagerSendAccessibilityEvent                       = binder.FirstCallTransaction + 1
	TransactionIAccessibilityManagerAddClient                                    = binder.FirstCallTransaction + 2
	TransactionIAccessibilityManagerRemoveClient                                 = binder.FirstCallTransaction + 3
	TransactionIAccessibilityManagerGetInstalledAccessibilityServiceList         = binder.FirstCallTransaction + 4
	TransactionIAccessibilityManagerGetEnabledAccessibilityServiceList           = binder.FirstCallTransaction + 5
	TransactionIAccessibilityManagerAddAccessibilityInteractionConnection        = binder.FirstCallTransaction + 6
	TransactionIAccessibilityManagerRemoveAccessibilityInteractionConnection     = binder.FirstCallTransaction + 7
	TransactionIAccessibilityManagerSetPictureInPictureActionReplacingConnection = binder.FirstCallTransaction + 8
	TransactionIAccessibilityManagerRegisterUiTestAutomationService              = binder.FirstCallTransaction + 9
	TransactionIAccessibilityManagerUnregisterUiTestAutomationService            = binder.FirstCallTransaction + 10
	TransactionIAccessibilityManagerGetWindowToken                               = binder.FirstCallTransaction + 11
	TransactionIAccessibilityManagerNotifyAccessibilityButtonClicked             = binder.FirstCallTransaction + 12
	TransactionIAccessibilityManagerNotifyAccessibilityButtonLongClicked         = binder.FirstCallTransaction + 13
	TransactionIAccessibilityManagerNotifyAccessibilityButtonVisibilityChanged   = binder.FirstCallTransaction + 14
	TransactionIAccessibilityManagerPerformAccessibilityShortcut                 = binder.FirstCallTransaction + 15
	TransactionIAccessibilityManagerGetAccessibilityShortcutTargets              = binder.FirstCallTransaction + 16
	TransactionIAccessibilityManagerSendFingerprintGesture                       = binder.FirstCallTransaction + 17
	TransactionIAccessibilityManagerGetAccessibilityWindowId                     = binder.FirstCallTransaction + 18
	TransactionIAccessibilityManagerGetRecommendedTimeoutMillis                  = binder.FirstCallTransaction + 19
	TransactionIAccessibilityManagerRegisterSystemAction                         = binder.FirstCallTransaction + 20
	TransactionIAccessibilityManagerUnregisterSystemAction                       = binder.FirstCallTransaction + 21
	TransactionIAccessibilityManagerSetMagnificationConnection                   = binder.FirstCallTransaction + 22
	TransactionIAccessibilityManagerAssociateEmbeddedHierarchy                   = binder.FirstCallTransaction + 23
	TransactionIAccessibilityManagerDisassociateEmbeddedHierarchy                = binder.FirstCallTransaction + 24
	TransactionIAccessibilityManagerGetFocusStrokeWidth                          = binder.FirstCallTransaction + 25
	TransactionIAccessibilityManagerGetFocusColor                                = binder.FirstCallTransaction + 26
	TransactionIAccessibilityManagerIsAudioDescriptionByDefaultEnabled           = binder.FirstCallTransaction + 27
	TransactionIAccessibilityManagerSetSystemAudioCaptioningEnabled              = binder.FirstCallTransaction + 28
	TransactionIAccessibilityManagerIsSystemAudioCaptioningUiEnabled             = binder.FirstCallTransaction + 29
	TransactionIAccessibilityManagerSetSystemAudioCaptioningUiEnabled            = binder.FirstCallTransaction + 30
	TransactionIAccessibilityManagerSetAccessibilityWindowAttributes             = binder.FirstCallTransaction + 31
	TransactionIAccessibilityManagerRegisterProxyForDisplay                      = binder.FirstCallTransaction + 32
	TransactionIAccessibilityManagerUnregisterProxyForDisplay                    = binder.FirstCallTransaction + 33
	TransactionIAccessibilityManagerInjectInputEventToInputFilter                = binder.FirstCallTransaction + 34
	TransactionIAccessibilityManagerStartFlashNotificationSequence               = binder.FirstCallTransaction + 35
	TransactionIAccessibilityManagerStopFlashNotificationSequence                = binder.FirstCallTransaction + 36
	TransactionIAccessibilityManagerStartFlashNotificationEvent                  = binder.FirstCallTransaction + 37
	TransactionIAccessibilityManagerIsAccessibilityTargetAllowed                 = binder.FirstCallTransaction + 38
	TransactionIAccessibilityManagerSendRestrictedDialogIntent                   = binder.FirstCallTransaction + 39
	TransactionIAccessibilityManagerIsAccessibilityServiceWarningRequired        = binder.FirstCallTransaction + 40
	TransactionIAccessibilityManagerGetWindowTransformationSpec                  = binder.FirstCallTransaction + 41
	TransactionIAccessibilityManagerAttachAccessibilityOverlayToDisplay          = binder.FirstCallTransaction + 42
	TransactionIAccessibilityManagerNotifyQuickSettingsTilesChanged              = binder.FirstCallTransaction + 43
	TransactionIAccessibilityManagerEnableShortcutsForTargets                    = binder.FirstCallTransaction + 44
	TransactionIAccessibilityManagerGetA11yFeatureToTileMap                      = binder.FirstCallTransaction + 45
	TransactionIAccessibilityManagerRegisterUserInitializationCompleteCallback   = binder.FirstCallTransaction + 46
	TransactionIAccessibilityManagerUnregisterUserInitializationCompleteCallback = binder.FirstCallTransaction + 47
)

type IAccessibilityManager interface {
	AsBinder() binder.IBinder
	Interrupt(ctx context.Context) error
	SendAccessibilityEvent(ctx context.Context, uiEvent AccessibilityEvent) error
	AddClient(ctx context.Context, client IAccessibilityManagerClient) (int64, error)
	RemoveClient(ctx context.Context, client IAccessibilityManagerClient) (bool, error)
	GetInstalledAccessibilityServiceList(ctx context.Context) (interface{}, error)
	GetEnabledAccessibilityServiceList(ctx context.Context, feedbackType int32) ([]interface{}, error)
	AddAccessibilityInteractionConnection(ctx context.Context, windowToken interface{}, leashToken binder.IBinder, connection IAccessibilityInteractionConnection, packageName string) (int32, error)
	RemoveAccessibilityInteractionConnection(ctx context.Context, windowToken interface{}) error
	SetPictureInPictureActionReplacingConnection(ctx context.Context, connection IAccessibilityInteractionConnection) error
	RegisterUiTestAutomationService(ctx context.Context, owner binder.IBinder, client interface{}, info interface{}, flags int32) error
	UnregisterUiTestAutomationService(ctx context.Context, client interface{}) error
	GetWindowToken(ctx context.Context, windowId int32) (binder.IBinder, error)
	NotifyAccessibilityButtonClicked(ctx context.Context, displayId int32, targetName string) error
	NotifyAccessibilityButtonLongClicked(ctx context.Context, displayId int32) error
	NotifyAccessibilityButtonVisibilityChanged(ctx context.Context, available bool) error
	PerformAccessibilityShortcut(ctx context.Context, displayId int32, shortcutType int32, targetName string) error
	GetAccessibilityShortcutTargets(ctx context.Context, shortcutType int32) ([]string, error)
	SendFingerprintGesture(ctx context.Context, gestureKeyCode int32) (bool, error)
	GetAccessibilityWindowId(ctx context.Context, windowToken binder.IBinder) (int32, error)
	GetRecommendedTimeoutMillis(ctx context.Context) (int64, error)
	RegisterSystemAction(ctx context.Context, action interface{}, actionId int32) error
	UnregisterSystemAction(ctx context.Context, actionId int32) error
	SetMagnificationConnection(ctx context.Context, connection IMagnificationConnection) error
	AssociateEmbeddedHierarchy(ctx context.Context, host binder.IBinder, embedded binder.IBinder) error
	DisassociateEmbeddedHierarchy(ctx context.Context, token binder.IBinder) error
	GetFocusStrokeWidth(ctx context.Context) (int32, error)
	GetFocusColor(ctx context.Context) (int32, error)
	IsAudioDescriptionByDefaultEnabled(ctx context.Context) (bool, error)
	SetSystemAudioCaptioningEnabled(ctx context.Context, isEnabled bool) error
	IsSystemAudioCaptioningUiEnabled(ctx context.Context) (bool, error)
	SetSystemAudioCaptioningUiEnabled(ctx context.Context, isEnabled bool) error
	SetAccessibilityWindowAttributes(ctx context.Context, displayId int32, windowId int32, attributes AccessibilityWindowAttributes) error
	RegisterProxyForDisplay(ctx context.Context, proxy interface{}, displayId int32) (bool, error)
	UnregisterProxyForDisplay(ctx context.Context, displayId int32) (bool, error)
	InjectInputEventToInputFilter(ctx context.Context, event interface{}) error
	StartFlashNotificationSequence(ctx context.Context, opPkg string, reason int32, token binder.IBinder) (bool, error)
	StopFlashNotificationSequence(ctx context.Context, opPkg string) (bool, error)
	StartFlashNotificationEvent(ctx context.Context, opPkg string, reason int32, reasonPkg string) (bool, error)
	IsAccessibilityTargetAllowed(ctx context.Context, packageName string, uid int32) (bool, error)
	SendRestrictedDialogIntent(ctx context.Context, packageName string, uid int32) (bool, error)
	IsAccessibilityServiceWarningRequired(ctx context.Context, info interface{}) (bool, error)
	GetWindowTransformationSpec(ctx context.Context, windowId int32) (accessibilityIAccessibilityManager.WindowTransformationSpec, error)
	AttachAccessibilityOverlayToDisplay(ctx context.Context, displayId int32, surfaceControl interface{}) error
	NotifyQuickSettingsTilesChanged(ctx context.Context, tileComponentNames []content.ComponentName) error
	EnableShortcutsForTargets(ctx context.Context, enable bool, shortcutTypes int32, shortcutTargets []string) error
	GetA11yFeatureToTileMap(ctx context.Context) (interface{}, error)
	RegisterUserInitializationCompleteCallback(ctx context.Context, callback IUserInitializationCompleteCallback) error
	UnregisterUserInitializationCompleteCallback(ctx context.Context, callback IUserInitializationCompleteCallback) error
}

type AccessibilityManagerProxy struct {
	remote binder.IBinder
}

func NewAccessibilityManagerProxy(
	remote binder.IBinder,
) *AccessibilityManagerProxy {
	return &AccessibilityManagerProxy{remote: remote}
}

func (p *AccessibilityManagerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAccessibilityManager = (*AccessibilityManagerProxy)(nil)

func (p *AccessibilityManagerProxy) Interrupt(
	ctx context.Context,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "interrupt")
	if _err != nil {
		_code = TransactionIAccessibilityManagerInterrupt
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) SendAccessibilityEvent(
	ctx context.Context,
	uiEvent AccessibilityEvent,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(1)
	if _err := uiEvent.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "sendAccessibilityEvent")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSendAccessibilityEvent
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) AddClient(
	ctx context.Context,
	client IAccessibilityManagerClient,
) (int64, error) {
	var _result int64
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "addClient")
	if _err != nil {
		_code = TransactionIAccessibilityManagerAddClient
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) RemoveClient(
	ctx context.Context,
	client IAccessibilityManagerClient,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "removeClient")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRemoveClient
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) GetInstalledAccessibilityServiceList(
	ctx context.Context,
) (interface{}, error) {
	var _result interface{}
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getInstalledAccessibilityServiceList")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetInstalledAccessibilityServiceList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *AccessibilityManagerProxy) GetEnabledAccessibilityServiceList(
	ctx context.Context,
	feedbackType int32,
) ([]interface{}, error) {
	var _result []interface{}
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(feedbackType)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getEnabledAccessibilityServiceList")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetEnabledAccessibilityServiceList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]interface{}, _count)
		for _i := int32(0); _i < _count; _i++ {
		}
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) AddAccessibilityInteractionConnection(
	ctx context.Context,
	windowToken interface{},
	leashToken binder.IBinder,
	connection IAccessibilityInteractionConnection,
	packageName string,
) (int32, error) {
	var _result int32
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, leashToken, p.remote.Transport())
	binder.WriteBinderToParcel(ctx, _data, connection.AsBinder(), p.remote.Transport())
	_data.WriteString16(packageName)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "addAccessibilityInteractionConnection")
	if _err != nil {
		_code = TransactionIAccessibilityManagerAddAccessibilityInteractionConnection
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) RemoveAccessibilityInteractionConnection(
	ctx context.Context,
	windowToken interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "removeAccessibilityInteractionConnection")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRemoveAccessibilityInteractionConnection
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) SetPictureInPictureActionReplacingConnection(
	ctx context.Context,
	connection IAccessibilityInteractionConnection,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, connection.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "setPictureInPictureActionReplacingConnection")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSetPictureInPictureActionReplacingConnection
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) RegisterUiTestAutomationService(
	ctx context.Context,
	owner binder.IBinder,
	client interface{},
	info interface{},
	flags int32,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, owner, p.remote.Transport())
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(flags)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "registerUiTestAutomationService")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRegisterUiTestAutomationService
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) UnregisterUiTestAutomationService(
	ctx context.Context,
	client interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "unregisterUiTestAutomationService")
	if _err != nil {
		_code = TransactionIAccessibilityManagerUnregisterUiTestAutomationService
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) GetWindowToken(
	ctx context.Context,
	windowId int32,
) (binder.IBinder, error) {
	var _result binder.IBinder
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(windowId)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getWindowToken")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetWindowToken
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle)
	return _result, nil
}

func (p *AccessibilityManagerProxy) NotifyAccessibilityButtonClicked(
	ctx context.Context,
	displayId int32,
	targetName string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)
	_data.WriteString16(targetName)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "notifyAccessibilityButtonClicked")
	if _err != nil {
		_code = TransactionIAccessibilityManagerNotifyAccessibilityButtonClicked
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) NotifyAccessibilityButtonLongClicked(
	ctx context.Context,
	displayId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "notifyAccessibilityButtonLongClicked")
	if _err != nil {
		_code = TransactionIAccessibilityManagerNotifyAccessibilityButtonLongClicked
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) NotifyAccessibilityButtonVisibilityChanged(
	ctx context.Context,
	available bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteBool(available)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "notifyAccessibilityButtonVisibilityChanged")
	if _err != nil {
		_code = TransactionIAccessibilityManagerNotifyAccessibilityButtonVisibilityChanged
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) PerformAccessibilityShortcut(
	ctx context.Context,
	displayId int32,
	shortcutType int32,
	targetName string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)
	_data.WriteInt32(shortcutType)
	_data.WriteString16(targetName)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "performAccessibilityShortcut")
	if _err != nil {
		_code = TransactionIAccessibilityManagerPerformAccessibilityShortcut
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) GetAccessibilityShortcutTargets(
	ctx context.Context,
	shortcutType int32,
) ([]string, error) {
	var _result []string
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(shortcutType)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getAccessibilityShortcutTargets")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetAccessibilityShortcutTargets
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]string, _count)
		for _i := int32(0); _i < _count; _i++ {
			_result[_i], _err = _reply.ReadString16()
			if _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) SendFingerprintGesture(
	ctx context.Context,
	gestureKeyCode int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(gestureKeyCode)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "sendFingerprintGesture")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSendFingerprintGesture
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) GetAccessibilityWindowId(
	ctx context.Context,
	windowToken binder.IBinder,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, windowToken, p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getAccessibilityWindowId")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetAccessibilityWindowId
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) GetRecommendedTimeoutMillis(
	ctx context.Context,
) (int64, error) {
	var _result int64
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getRecommendedTimeoutMillis")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetRecommendedTimeoutMillis
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt64()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) RegisterSystemAction(
	ctx context.Context,
	action interface{},
	actionId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(actionId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "registerSystemAction")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRegisterSystemAction
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) UnregisterSystemAction(
	ctx context.Context,
	actionId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(actionId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "unregisterSystemAction")
	if _err != nil {
		_code = TransactionIAccessibilityManagerUnregisterSystemAction
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) SetMagnificationConnection(
	ctx context.Context,
	connection IMagnificationConnection,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, connection.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "setMagnificationConnection")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSetMagnificationConnection
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) AssociateEmbeddedHierarchy(
	ctx context.Context,
	host binder.IBinder,
	embedded binder.IBinder,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, host, p.remote.Transport())
	binder.WriteBinderToParcel(ctx, _data, embedded, p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "associateEmbeddedHierarchy")
	if _err != nil {
		_code = TransactionIAccessibilityManagerAssociateEmbeddedHierarchy
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) DisassociateEmbeddedHierarchy(
	ctx context.Context,
	token binder.IBinder,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, token, p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "disassociateEmbeddedHierarchy")
	if _err != nil {
		_code = TransactionIAccessibilityManagerDisassociateEmbeddedHierarchy
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) GetFocusStrokeWidth(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getFocusStrokeWidth")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetFocusStrokeWidth
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) GetFocusColor(
	ctx context.Context,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getFocusColor")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetFocusColor
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) IsAudioDescriptionByDefaultEnabled(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "isAudioDescriptionByDefaultEnabled")
	if _err != nil {
		_code = TransactionIAccessibilityManagerIsAudioDescriptionByDefaultEnabled
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) SetSystemAudioCaptioningEnabled(
	ctx context.Context,
	isEnabled bool,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteBool(isEnabled)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "setSystemAudioCaptioningEnabled")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSetSystemAudioCaptioningEnabled
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) IsSystemAudioCaptioningUiEnabled(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "isSystemAudioCaptioningUiEnabled")
	if _err != nil {
		_code = TransactionIAccessibilityManagerIsSystemAudioCaptioningUiEnabled
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) SetSystemAudioCaptioningUiEnabled(
	ctx context.Context,
	isEnabled bool,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteBool(isEnabled)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "setSystemAudioCaptioningUiEnabled")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSetSystemAudioCaptioningUiEnabled
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) SetAccessibilityWindowAttributes(
	ctx context.Context,
	displayId int32,
	windowId int32,
	attributes AccessibilityWindowAttributes,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)
	_data.WriteInt32(windowId)
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(1)
	if _err := attributes.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "setAccessibilityWindowAttributes")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSetAccessibilityWindowAttributes
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) RegisterProxyForDisplay(
	ctx context.Context,
	proxy interface{},
	displayId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "registerProxyForDisplay")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRegisterProxyForDisplay
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) UnregisterProxyForDisplay(
	ctx context.Context,
	displayId int32,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "unregisterProxyForDisplay")
	if _err != nil {
		_code = TransactionIAccessibilityManagerUnregisterProxyForDisplay
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) InjectInputEventToInputFilter(
	ctx context.Context,
	event interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "injectInputEventToInputFilter")
	if _err != nil {
		_code = TransactionIAccessibilityManagerInjectInputEventToInputFilter
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) StartFlashNotificationSequence(
	ctx context.Context,
	opPkg string,
	reason int32,
	token binder.IBinder,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteString16(opPkg)
	_data.WriteInt32(reason)
	binder.WriteBinderToParcel(ctx, _data, token, p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "startFlashNotificationSequence")
	if _err != nil {
		_code = TransactionIAccessibilityManagerStartFlashNotificationSequence
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) StopFlashNotificationSequence(
	ctx context.Context,
	opPkg string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteString16(opPkg)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "stopFlashNotificationSequence")
	if _err != nil {
		_code = TransactionIAccessibilityManagerStopFlashNotificationSequence
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) StartFlashNotificationEvent(
	ctx context.Context,
	opPkg string,
	reason int32,
	reasonPkg string,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteString16(opPkg)
	_data.WriteInt32(reason)
	_data.WriteString16(reasonPkg)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "startFlashNotificationEvent")
	if _err != nil {
		_code = TransactionIAccessibilityManagerStartFlashNotificationEvent
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) IsAccessibilityTargetAllowed(
	ctx context.Context,
	packageName string,
	uid int32,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteString16(packageName)
	_data.WriteInt32(uid)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "isAccessibilityTargetAllowed")
	if _err != nil {
		_code = TransactionIAccessibilityManagerIsAccessibilityTargetAllowed
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) SendRestrictedDialogIntent(
	ctx context.Context,
	packageName string,
	uid int32,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteString16(packageName)
	_data.WriteInt32(uid)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "sendRestrictedDialogIntent")
	if _err != nil {
		_code = TransactionIAccessibilityManagerSendRestrictedDialogIntent
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) IsAccessibilityServiceWarningRequired(
	ctx context.Context,
	info interface{},
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "isAccessibilityServiceWarningRequired")
	if _err != nil {
		_code = TransactionIAccessibilityManagerIsAccessibilityServiceWarningRequired
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) GetWindowTransformationSpec(
	ctx context.Context,
	windowId int32,
) (accessibilityIAccessibilityManager.WindowTransformationSpec, error) {
	var _result accessibilityIAccessibilityManager.WindowTransformationSpec
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(windowId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getWindowTransformationSpec")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetWindowTransformationSpec
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *AccessibilityManagerProxy) AttachAccessibilityOverlayToDisplay(
	ctx context.Context,
	displayId int32,
	surfaceControl interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "attachAccessibilityOverlayToDisplay")
	if _err != nil {
		_code = TransactionIAccessibilityManagerAttachAccessibilityOverlayToDisplay
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) NotifyQuickSettingsTilesChanged(
	ctx context.Context,
	tileComponentNames []content.ComponentName,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(_identity.UserID)
	if tileComponentNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(tileComponentNames)))
		for _, _item := range tileComponentNames {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "notifyQuickSettingsTilesChanged")
	if _err != nil {
		_code = TransactionIAccessibilityManagerNotifyQuickSettingsTilesChanged
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) EnableShortcutsForTargets(
	ctx context.Context,
	enable bool,
	shortcutTypes int32,
	shortcutTargets []string,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteBool(enable)
	_data.WriteInt32(shortcutTypes)
	if shortcutTargets == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(shortcutTargets)))
		for _, _item := range shortcutTargets {
			_data.WriteString16(_item)
		}
	}
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "enableShortcutsForTargets")
	if _err != nil {
		_code = TransactionIAccessibilityManagerEnableShortcutsForTargets
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *AccessibilityManagerProxy) GetA11yFeatureToTileMap(
	ctx context.Context,
) (interface{}, error) {
	var _result interface{}
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "getA11yFeatureToTileMap")
	if _err != nil {
		_code = TransactionIAccessibilityManagerGetA11yFeatureToTileMap
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	return _result, nil
}

func (p *AccessibilityManagerProxy) RegisterUserInitializationCompleteCallback(
	ctx context.Context,
	callback IUserInitializationCompleteCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "registerUserInitializationCompleteCallback")
	if _err != nil {
		_code = TransactionIAccessibilityManagerRegisterUserInitializationCompleteCallback
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *AccessibilityManagerProxy) UnregisterUserInitializationCompleteCallback(
	ctx context.Context,
	callback IUserInitializationCompleteCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAccessibilityManager)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIAccessibilityManager, "unregisterUserInitializationCompleteCallback")
	if _err != nil {
		_code = TransactionIAccessibilityManagerUnregisterUserInitializationCompleteCallback
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// AccessibilityManagerStub dispatches incoming binder transactions
// to a typed IAccessibilityManager implementation.
type AccessibilityManagerStub struct {
	Impl IAccessibilityManager
}

var _ binder.TransactionReceiver = (*AccessibilityManagerStub)(nil)

func (s *AccessibilityManagerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIAccessibilityManagerInterrupt:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.Interrupt(ctx)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerSendAccessibilityEvent:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_uiEvent AccessibilityEvent
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_uiEvent.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.SendAccessibilityEvent(ctx, _arg_uiEvent)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerAddClient:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client IAccessibilityManagerClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.AddClient(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt64(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerRemoveClient:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client IAccessibilityManagerClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.RemoveClient(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerGetInstalledAccessibilityServiceList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetInstalledAccessibilityServiceList(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_ = _result
		return _reply, nil
	case TransactionIAccessibilityManagerGetEnabledAccessibilityServiceList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_feedbackType, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetEnabledAccessibilityServiceList(ctx, _arg_feedbackType)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIAccessibilityManagerAddAccessibilityInteractionConnection:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_windowToken interface{}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_leashToken binder.IBinder
		_ = _arg_leashToken
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_connection IAccessibilityInteractionConnection
		_ = _arg_connection
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.AddAccessibilityInteractionConnection(ctx, _arg_windowToken, _arg_leashToken, _arg_connection, _arg_packageName)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerRemoveAccessibilityInteractionConnection:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_windowToken interface{}
		_err := s.Impl.RemoveAccessibilityInteractionConnection(ctx, _arg_windowToken)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerSetPictureInPictureActionReplacingConnection:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_connection IAccessibilityInteractionConnection
		_ = _arg_connection
		_err := s.Impl.SetPictureInPictureActionReplacingConnection(ctx, _arg_connection)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerRegisterUiTestAutomationService:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_owner binder.IBinder
		_ = _arg_owner
		var _arg_client interface{}
		var _arg_info interface{}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.RegisterUiTestAutomationService(ctx, _arg_owner, _arg_client, _arg_info, _arg_flags)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerUnregisterUiTestAutomationService:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_client interface{}
		_err := s.Impl.UnregisterUiTestAutomationService(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerGetWindowToken:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_windowId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetWindowToken(ctx, _arg_windowId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIAccessibilityManagerNotifyAccessibilityButtonClicked:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_targetName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.NotifyAccessibilityButtonClicked(ctx, _arg_displayId, _arg_targetName)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerNotifyAccessibilityButtonLongClicked:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.NotifyAccessibilityButtonLongClicked(ctx, _arg_displayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerNotifyAccessibilityButtonVisibilityChanged:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_available, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.NotifyAccessibilityButtonVisibilityChanged(ctx, _arg_available)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerPerformAccessibilityShortcut:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_shortcutType, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_targetName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.PerformAccessibilityShortcut(ctx, _arg_displayId, _arg_shortcutType, _arg_targetName)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerGetAccessibilityShortcutTargets:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_shortcutType, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetAccessibilityShortcutTargets(ctx, _arg_shortcutType)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIAccessibilityManagerSendFingerprintGesture:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_gestureKeyCode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.SendFingerprintGesture(ctx, _arg_gestureKeyCode)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerGetAccessibilityWindowId:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken binder.IBinder
		_ = _arg_windowToken
		_result, _err := s.Impl.GetAccessibilityWindowId(ctx, _arg_windowToken)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerGetRecommendedTimeoutMillis:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetRecommendedTimeoutMillis(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt64(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerRegisterSystemAction:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_action interface{}
		_arg_actionId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.RegisterSystemAction(ctx, _arg_action, _arg_actionId)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerUnregisterSystemAction:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_actionId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.UnregisterSystemAction(ctx, _arg_actionId)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerSetMagnificationConnection:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_connection IMagnificationConnection
		_ = _arg_connection
		_err := s.Impl.SetMagnificationConnection(ctx, _arg_connection)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerAssociateEmbeddedHierarchy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_host binder.IBinder
		_ = _arg_host
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_embedded binder.IBinder
		_ = _arg_embedded
		_err := s.Impl.AssociateEmbeddedHierarchy(ctx, _arg_host, _arg_embedded)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerDisassociateEmbeddedHierarchy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_token binder.IBinder
		_ = _arg_token
		_err := s.Impl.DisassociateEmbeddedHierarchy(ctx, _arg_token)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerGetFocusStrokeWidth:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetFocusStrokeWidth(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerGetFocusColor:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetFocusColor(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerIsAudioDescriptionByDefaultEnabled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsAudioDescriptionByDefaultEnabled(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerSetSystemAudioCaptioningEnabled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_isEnabled, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetSystemAudioCaptioningEnabled(ctx, _arg_isEnabled)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerIsSystemAudioCaptioningUiEnabled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsSystemAudioCaptioningUiEnabled(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerSetSystemAudioCaptioningUiEnabled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_isEnabled, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetSystemAudioCaptioningUiEnabled(ctx, _arg_isEnabled)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerSetAccessibilityWindowAttributes:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_windowId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		var _arg_attributes AccessibilityWindowAttributes
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_attributes.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.SetAccessibilityWindowAttributes(ctx, _arg_displayId, _arg_windowId, _arg_attributes)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerRegisterProxyForDisplay:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_proxy interface{}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.RegisterProxyForDisplay(ctx, _arg_proxy, _arg_displayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerUnregisterProxyForDisplay:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.UnregisterProxyForDisplay(ctx, _arg_displayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerInjectInputEventToInputFilter:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_event interface{}
		_err := s.Impl.InjectInputEventToInputFilter(ctx, _arg_event)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerStartFlashNotificationSequence:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_opPkg, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_token binder.IBinder
		_ = _arg_token
		_result, _err := s.Impl.StartFlashNotificationSequence(ctx, _arg_opPkg, _arg_reason, _arg_token)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerStopFlashNotificationSequence:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_opPkg, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.StopFlashNotificationSequence(ctx, _arg_opPkg)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerStartFlashNotificationEvent:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_opPkg, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_reasonPkg, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.StartFlashNotificationEvent(ctx, _arg_opPkg, _arg_reason, _arg_reasonPkg)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerIsAccessibilityTargetAllowed:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_uid, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsAccessibilityTargetAllowed(ctx, _arg_packageName, _arg_uid)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerSendRestrictedDialogIntent:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_uid, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.SendRestrictedDialogIntent(ctx, _arg_packageName, _arg_uid)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerIsAccessibilityServiceWarningRequired:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_info interface{}
		_result, _err := s.Impl.IsAccessibilityServiceWarningRequired(ctx, _arg_info)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIAccessibilityManagerGetWindowTransformationSpec:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_windowId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetWindowTransformationSpec(ctx, _arg_windowId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIAccessibilityManagerAttachAccessibilityOverlayToDisplay:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_surfaceControl interface{}
		_err = s.Impl.AttachAccessibilityOverlayToDisplay(ctx, _arg_displayId, _arg_surfaceControl)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerNotifyQuickSettingsTilesChanged:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_tileComponentNames []content.ComponentName
		_ = _arg_tileComponentNames
		_err := s.Impl.NotifyQuickSettingsTilesChanged(ctx, _arg_tileComponentNames)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerEnableShortcutsForTargets:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_enable, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_shortcutTypes, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_shortcutTargets []string
		_ = _arg_shortcutTargets
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err = s.Impl.EnableShortcutsForTargets(ctx, _arg_enable, _arg_shortcutTypes, _arg_shortcutTargets)
		_ = _err
		return nil, nil
	case TransactionIAccessibilityManagerGetA11yFeatureToTileMap:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetA11yFeatureToTileMap(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_ = _result
		return _reply, nil
	case TransactionIAccessibilityManagerRegisterUserInitializationCompleteCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IUserInitializationCompleteCallback
		_ = _arg_callback
		_err := s.Impl.RegisterUserInitializationCompleteCallback(ctx, _arg_callback)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIAccessibilityManagerUnregisterUserInitializationCompleteCallback:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback IUserInitializationCompleteCallback
		_ = _arg_callback
		_err := s.Impl.UnregisterUserInitializationCompleteCallback(ctx, _arg_callback)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IAccessibilityManagerServer is the server-side interface that user implementations
// provide to NewAccessibilityManagerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IAccessibilityManagerServer interface {
	Interrupt(ctx context.Context) error
	SendAccessibilityEvent(ctx context.Context, uiEvent AccessibilityEvent) error
	AddClient(ctx context.Context, client IAccessibilityManagerClient) (int64, error)
	RemoveClient(ctx context.Context, client IAccessibilityManagerClient) (bool, error)
	GetInstalledAccessibilityServiceList(ctx context.Context) (interface{}, error)
	GetEnabledAccessibilityServiceList(ctx context.Context, feedbackType int32) ([]interface{}, error)
	AddAccessibilityInteractionConnection(ctx context.Context, windowToken interface{}, leashToken binder.IBinder, connection IAccessibilityInteractionConnection, packageName string) (int32, error)
	RemoveAccessibilityInteractionConnection(ctx context.Context, windowToken interface{}) error
	SetPictureInPictureActionReplacingConnection(ctx context.Context, connection IAccessibilityInteractionConnection) error
	RegisterUiTestAutomationService(ctx context.Context, owner binder.IBinder, client interface{}, info interface{}, flags int32) error
	UnregisterUiTestAutomationService(ctx context.Context, client interface{}) error
	GetWindowToken(ctx context.Context, windowId int32) (binder.IBinder, error)
	NotifyAccessibilityButtonClicked(ctx context.Context, displayId int32, targetName string) error
	NotifyAccessibilityButtonLongClicked(ctx context.Context, displayId int32) error
	NotifyAccessibilityButtonVisibilityChanged(ctx context.Context, available bool) error
	PerformAccessibilityShortcut(ctx context.Context, displayId int32, shortcutType int32, targetName string) error
	GetAccessibilityShortcutTargets(ctx context.Context, shortcutType int32) ([]string, error)
	SendFingerprintGesture(ctx context.Context, gestureKeyCode int32) (bool, error)
	GetAccessibilityWindowId(ctx context.Context, windowToken binder.IBinder) (int32, error)
	GetRecommendedTimeoutMillis(ctx context.Context) (int64, error)
	RegisterSystemAction(ctx context.Context, action interface{}, actionId int32) error
	UnregisterSystemAction(ctx context.Context, actionId int32) error
	SetMagnificationConnection(ctx context.Context, connection IMagnificationConnection) error
	AssociateEmbeddedHierarchy(ctx context.Context, host binder.IBinder, embedded binder.IBinder) error
	DisassociateEmbeddedHierarchy(ctx context.Context, token binder.IBinder) error
	GetFocusStrokeWidth(ctx context.Context) (int32, error)
	GetFocusColor(ctx context.Context) (int32, error)
	IsAudioDescriptionByDefaultEnabled(ctx context.Context) (bool, error)
	SetSystemAudioCaptioningEnabled(ctx context.Context, isEnabled bool) error
	IsSystemAudioCaptioningUiEnabled(ctx context.Context) (bool, error)
	SetSystemAudioCaptioningUiEnabled(ctx context.Context, isEnabled bool) error
	SetAccessibilityWindowAttributes(ctx context.Context, displayId int32, windowId int32, attributes AccessibilityWindowAttributes) error
	RegisterProxyForDisplay(ctx context.Context, proxy interface{}, displayId int32) (bool, error)
	UnregisterProxyForDisplay(ctx context.Context, displayId int32) (bool, error)
	InjectInputEventToInputFilter(ctx context.Context, event interface{}) error
	StartFlashNotificationSequence(ctx context.Context, opPkg string, reason int32, token binder.IBinder) (bool, error)
	StopFlashNotificationSequence(ctx context.Context, opPkg string) (bool, error)
	StartFlashNotificationEvent(ctx context.Context, opPkg string, reason int32, reasonPkg string) (bool, error)
	IsAccessibilityTargetAllowed(ctx context.Context, packageName string, uid int32) (bool, error)
	SendRestrictedDialogIntent(ctx context.Context, packageName string, uid int32) (bool, error)
	IsAccessibilityServiceWarningRequired(ctx context.Context, info interface{}) (bool, error)
	GetWindowTransformationSpec(ctx context.Context, windowId int32) (accessibilityIAccessibilityManager.WindowTransformationSpec, error)
	AttachAccessibilityOverlayToDisplay(ctx context.Context, displayId int32, surfaceControl interface{}) error
	NotifyQuickSettingsTilesChanged(ctx context.Context, tileComponentNames []content.ComponentName) error
	EnableShortcutsForTargets(ctx context.Context, enable bool, shortcutTypes int32, shortcutTargets []string) error
	GetA11yFeatureToTileMap(ctx context.Context) (interface{}, error)
	RegisterUserInitializationCompleteCallback(ctx context.Context, callback IUserInitializationCompleteCallback) error
	UnregisterUserInitializationCompleteCallback(ctx context.Context, callback IUserInitializationCompleteCallback) error
}

type accessibilityManagerStubWrapper struct {
	impl       IAccessibilityManagerServer
	stubBinder *binder.StubBinder
}

func (w *accessibilityManagerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *accessibilityManagerStubWrapper) Interrupt(
	ctx context.Context,
) error {
	return w.impl.Interrupt(ctx)
}

func (w *accessibilityManagerStubWrapper) SendAccessibilityEvent(
	ctx context.Context,
	uiEvent AccessibilityEvent,
) error {
	return w.impl.SendAccessibilityEvent(ctx, uiEvent)
}

func (w *accessibilityManagerStubWrapper) AddClient(
	ctx context.Context,
	client IAccessibilityManagerClient,
) (int64, error) {
	return w.impl.AddClient(ctx, client)
}

func (w *accessibilityManagerStubWrapper) RemoveClient(
	ctx context.Context,
	client IAccessibilityManagerClient,
) (bool, error) {
	return w.impl.RemoveClient(ctx, client)
}

func (w *accessibilityManagerStubWrapper) GetInstalledAccessibilityServiceList(
	ctx context.Context,
) (interface{}, error) {
	return w.impl.GetInstalledAccessibilityServiceList(ctx)
}

func (w *accessibilityManagerStubWrapper) GetEnabledAccessibilityServiceList(
	ctx context.Context,
	feedbackType int32,
) ([]interface{}, error) {
	return w.impl.GetEnabledAccessibilityServiceList(ctx, feedbackType)
}

func (w *accessibilityManagerStubWrapper) AddAccessibilityInteractionConnection(
	ctx context.Context,
	windowToken interface{},
	leashToken binder.IBinder,
	connection IAccessibilityInteractionConnection,
	packageName string,
) (int32, error) {
	return w.impl.AddAccessibilityInteractionConnection(ctx, windowToken, leashToken, connection, packageName)
}

func (w *accessibilityManagerStubWrapper) RemoveAccessibilityInteractionConnection(
	ctx context.Context,
	windowToken interface{},
) error {
	return w.impl.RemoveAccessibilityInteractionConnection(ctx, windowToken)
}

func (w *accessibilityManagerStubWrapper) SetPictureInPictureActionReplacingConnection(
	ctx context.Context,
	connection IAccessibilityInteractionConnection,
) error {
	return w.impl.SetPictureInPictureActionReplacingConnection(ctx, connection)
}

func (w *accessibilityManagerStubWrapper) RegisterUiTestAutomationService(
	ctx context.Context,
	owner binder.IBinder,
	client interface{},
	info interface{},
	flags int32,
) error {
	return w.impl.RegisterUiTestAutomationService(ctx, owner, client, info, flags)
}

func (w *accessibilityManagerStubWrapper) UnregisterUiTestAutomationService(
	ctx context.Context,
	client interface{},
) error {
	return w.impl.UnregisterUiTestAutomationService(ctx, client)
}

func (w *accessibilityManagerStubWrapper) GetWindowToken(
	ctx context.Context,
	windowId int32,
) (binder.IBinder, error) {
	return w.impl.GetWindowToken(ctx, windowId)
}

func (w *accessibilityManagerStubWrapper) NotifyAccessibilityButtonClicked(
	ctx context.Context,
	displayId int32,
	targetName string,
) error {
	return w.impl.NotifyAccessibilityButtonClicked(ctx, displayId, targetName)
}

func (w *accessibilityManagerStubWrapper) NotifyAccessibilityButtonLongClicked(
	ctx context.Context,
	displayId int32,
) error {
	return w.impl.NotifyAccessibilityButtonLongClicked(ctx, displayId)
}

func (w *accessibilityManagerStubWrapper) NotifyAccessibilityButtonVisibilityChanged(
	ctx context.Context,
	available bool,
) error {
	return w.impl.NotifyAccessibilityButtonVisibilityChanged(ctx, available)
}

func (w *accessibilityManagerStubWrapper) PerformAccessibilityShortcut(
	ctx context.Context,
	displayId int32,
	shortcutType int32,
	targetName string,
) error {
	return w.impl.PerformAccessibilityShortcut(ctx, displayId, shortcutType, targetName)
}

func (w *accessibilityManagerStubWrapper) GetAccessibilityShortcutTargets(
	ctx context.Context,
	shortcutType int32,
) ([]string, error) {
	return w.impl.GetAccessibilityShortcutTargets(ctx, shortcutType)
}

func (w *accessibilityManagerStubWrapper) SendFingerprintGesture(
	ctx context.Context,
	gestureKeyCode int32,
) (bool, error) {
	return w.impl.SendFingerprintGesture(ctx, gestureKeyCode)
}

func (w *accessibilityManagerStubWrapper) GetAccessibilityWindowId(
	ctx context.Context,
	windowToken binder.IBinder,
) (int32, error) {
	return w.impl.GetAccessibilityWindowId(ctx, windowToken)
}

func (w *accessibilityManagerStubWrapper) GetRecommendedTimeoutMillis(
	ctx context.Context,
) (int64, error) {
	return w.impl.GetRecommendedTimeoutMillis(ctx)
}

func (w *accessibilityManagerStubWrapper) RegisterSystemAction(
	ctx context.Context,
	action interface{},
	actionId int32,
) error {
	return w.impl.RegisterSystemAction(ctx, action, actionId)
}

func (w *accessibilityManagerStubWrapper) UnregisterSystemAction(
	ctx context.Context,
	actionId int32,
) error {
	return w.impl.UnregisterSystemAction(ctx, actionId)
}

func (w *accessibilityManagerStubWrapper) SetMagnificationConnection(
	ctx context.Context,
	connection IMagnificationConnection,
) error {
	return w.impl.SetMagnificationConnection(ctx, connection)
}

func (w *accessibilityManagerStubWrapper) AssociateEmbeddedHierarchy(
	ctx context.Context,
	host binder.IBinder,
	embedded binder.IBinder,
) error {
	return w.impl.AssociateEmbeddedHierarchy(ctx, host, embedded)
}

func (w *accessibilityManagerStubWrapper) DisassociateEmbeddedHierarchy(
	ctx context.Context,
	token binder.IBinder,
) error {
	return w.impl.DisassociateEmbeddedHierarchy(ctx, token)
}

func (w *accessibilityManagerStubWrapper) GetFocusStrokeWidth(
	ctx context.Context,
) (int32, error) {
	return w.impl.GetFocusStrokeWidth(ctx)
}

func (w *accessibilityManagerStubWrapper) GetFocusColor(
	ctx context.Context,
) (int32, error) {
	return w.impl.GetFocusColor(ctx)
}

func (w *accessibilityManagerStubWrapper) IsAudioDescriptionByDefaultEnabled(
	ctx context.Context,
) (bool, error) {
	return w.impl.IsAudioDescriptionByDefaultEnabled(ctx)
}

func (w *accessibilityManagerStubWrapper) SetSystemAudioCaptioningEnabled(
	ctx context.Context,
	isEnabled bool,
) error {
	return w.impl.SetSystemAudioCaptioningEnabled(ctx, isEnabled)
}

func (w *accessibilityManagerStubWrapper) IsSystemAudioCaptioningUiEnabled(
	ctx context.Context,
) (bool, error) {
	return w.impl.IsSystemAudioCaptioningUiEnabled(ctx)
}

func (w *accessibilityManagerStubWrapper) SetSystemAudioCaptioningUiEnabled(
	ctx context.Context,
	isEnabled bool,
) error {
	return w.impl.SetSystemAudioCaptioningUiEnabled(ctx, isEnabled)
}

func (w *accessibilityManagerStubWrapper) SetAccessibilityWindowAttributes(
	ctx context.Context,
	displayId int32,
	windowId int32,
	attributes AccessibilityWindowAttributes,
) error {
	return w.impl.SetAccessibilityWindowAttributes(ctx, displayId, windowId, attributes)
}

func (w *accessibilityManagerStubWrapper) RegisterProxyForDisplay(
	ctx context.Context,
	proxy interface{},
	displayId int32,
) (bool, error) {
	return w.impl.RegisterProxyForDisplay(ctx, proxy, displayId)
}

func (w *accessibilityManagerStubWrapper) UnregisterProxyForDisplay(
	ctx context.Context,
	displayId int32,
) (bool, error) {
	return w.impl.UnregisterProxyForDisplay(ctx, displayId)
}

func (w *accessibilityManagerStubWrapper) InjectInputEventToInputFilter(
	ctx context.Context,
	event interface{},
) error {
	return w.impl.InjectInputEventToInputFilter(ctx, event)
}

func (w *accessibilityManagerStubWrapper) StartFlashNotificationSequence(
	ctx context.Context,
	opPkg string,
	reason int32,
	token binder.IBinder,
) (bool, error) {
	return w.impl.StartFlashNotificationSequence(ctx, opPkg, reason, token)
}

func (w *accessibilityManagerStubWrapper) StopFlashNotificationSequence(
	ctx context.Context,
	opPkg string,
) (bool, error) {
	return w.impl.StopFlashNotificationSequence(ctx, opPkg)
}

func (w *accessibilityManagerStubWrapper) StartFlashNotificationEvent(
	ctx context.Context,
	opPkg string,
	reason int32,
	reasonPkg string,
) (bool, error) {
	return w.impl.StartFlashNotificationEvent(ctx, opPkg, reason, reasonPkg)
}

func (w *accessibilityManagerStubWrapper) IsAccessibilityTargetAllowed(
	ctx context.Context,
	packageName string,
	uid int32,
) (bool, error) {
	return w.impl.IsAccessibilityTargetAllowed(ctx, packageName, uid)
}

func (w *accessibilityManagerStubWrapper) SendRestrictedDialogIntent(
	ctx context.Context,
	packageName string,
	uid int32,
) (bool, error) {
	return w.impl.SendRestrictedDialogIntent(ctx, packageName, uid)
}

func (w *accessibilityManagerStubWrapper) IsAccessibilityServiceWarningRequired(
	ctx context.Context,
	info interface{},
) (bool, error) {
	return w.impl.IsAccessibilityServiceWarningRequired(ctx, info)
}

func (w *accessibilityManagerStubWrapper) GetWindowTransformationSpec(
	ctx context.Context,
	windowId int32,
) (accessibilityIAccessibilityManager.WindowTransformationSpec, error) {
	return w.impl.GetWindowTransformationSpec(ctx, windowId)
}

func (w *accessibilityManagerStubWrapper) AttachAccessibilityOverlayToDisplay(
	ctx context.Context,
	displayId int32,
	surfaceControl interface{},
) error {
	return w.impl.AttachAccessibilityOverlayToDisplay(ctx, displayId, surfaceControl)
}

func (w *accessibilityManagerStubWrapper) NotifyQuickSettingsTilesChanged(
	ctx context.Context,
	tileComponentNames []content.ComponentName,
) error {
	return w.impl.NotifyQuickSettingsTilesChanged(ctx, tileComponentNames)
}

func (w *accessibilityManagerStubWrapper) EnableShortcutsForTargets(
	ctx context.Context,
	enable bool,
	shortcutTypes int32,
	shortcutTargets []string,
) error {
	return w.impl.EnableShortcutsForTargets(ctx, enable, shortcutTypes, shortcutTargets)
}

func (w *accessibilityManagerStubWrapper) GetA11yFeatureToTileMap(
	ctx context.Context,
) (interface{}, error) {
	return w.impl.GetA11yFeatureToTileMap(ctx)
}

func (w *accessibilityManagerStubWrapper) RegisterUserInitializationCompleteCallback(
	ctx context.Context,
	callback IUserInitializationCompleteCallback,
) error {
	return w.impl.RegisterUserInitializationCompleteCallback(ctx, callback)
}

func (w *accessibilityManagerStubWrapper) UnregisterUserInitializationCompleteCallback(
	ctx context.Context,
	callback IUserInitializationCompleteCallback,
) error {
	return w.impl.UnregisterUserInitializationCompleteCallback(ctx, callback)
}

var _ IAccessibilityManager = (*accessibilityManagerStubWrapper)(nil)

// NewAccessibilityManagerStub creates a server-side IAccessibilityManager wrapping the given
// server implementation. The returned value satisfies IAccessibilityManager
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewAccessibilityManagerStub(
	impl IAccessibilityManagerServer,
) IAccessibilityManager {
	wrapper := &accessibilityManagerStubWrapper{impl: impl}
	stub := &AccessibilityManagerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
