package slice

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorISliceListener = "android.app.slice.ISliceListener"

const (
	TransactionISliceListenerOnSliceUpdated = binder.FirstCallTransaction + 0
)

const (
	MethodISliceListenerOnSliceUpdated = "onSliceUpdated"
)

type ISliceListener interface {
	AsBinder() binder.IBinder
	OnSliceUpdated(ctx context.Context, s_ Slice) error
}

type SliceListenerProxy struct {
	Remote binder.IBinder
}

func NewSliceListenerProxy(
	remote binder.IBinder,
) *SliceListenerProxy {
	return &SliceListenerProxy{Remote: remote}
}

func (p *SliceListenerProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ ISliceListener = (*SliceListenerProxy)(nil)

func (p *SliceListenerProxy) OnSliceUpdated(
	ctx context.Context,
	s_ Slice,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorISliceListener)
	_data.WriteInt32(1)
	if _err := s_.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorISliceListener, MethodISliceListenerOnSliceUpdated)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorISliceListener, MethodISliceListenerOnSliceUpdated, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// SliceListenerStub dispatches incoming binder transactions
// to a typed ISliceListener implementation.
type SliceListenerStub struct {
	Impl      ISliceListener
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*SliceListenerStub)(nil)

func (s *SliceListenerStub) Descriptor() string {
	return DescriptorISliceListener
}

func (s *SliceListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionISliceListenerOnSliceUpdated:
		var _arg_s_ Slice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_s_.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.OnSliceUpdated(ctx, _arg_s_)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// ISliceListenerServer is the server-side interface that user implementations
// provide to NewSliceListenerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type ISliceListenerServer interface {
	OnSliceUpdated(ctx context.Context, s_ Slice) error
}

type sliceListenerStubWrapper struct {
	impl       ISliceListenerServer
	stubBinder *binder.StubBinder
}

func (w *sliceListenerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *sliceListenerStubWrapper) OnSliceUpdated(
	ctx context.Context,
	s_ Slice,
) error {
	return w.impl.OnSliceUpdated(ctx, s_)
}

var _ ISliceListener = (*sliceListenerStubWrapper)(nil)

// NewSliceListenerStub creates a server-side ISliceListener wrapping the given
// server implementation. The returned value satisfies ISliceListener
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewSliceListenerStub(
	impl ISliceListenerServer,
) ISliceListener {
	wrapper := &sliceListenerStubWrapper{impl: impl}
	stub := &SliceListenerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
