package view

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	viewInputmethod "github.com/xaionaro-go/binder/android/view/inputmethod"
	window "github.com/xaionaro-go/binder/android/window"
	"github.com/xaionaro-go/binder/binder"
	internalInputmethod "github.com/xaionaro-go/binder/com/android/internal_/inputmethod"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIInputMethodManager = "com.android.internal.view.IInputMethodManager"

const (
	TransactionIInputMethodManagerAddClient                               = binder.FirstCallTransaction + 0
	TransactionIInputMethodManagerGetCurrentInputMethodInfoAsUser         = binder.FirstCallTransaction + 1
	TransactionIInputMethodManagerGetInputMethodList                      = binder.FirstCallTransaction + 2
	TransactionIInputMethodManagerGetEnabledInputMethodList               = binder.FirstCallTransaction + 3
	TransactionIInputMethodManagerGetInputMethodListLegacy                = binder.FirstCallTransaction + 4
	TransactionIInputMethodManagerGetEnabledInputMethodListLegacy         = binder.FirstCallTransaction + 5
	TransactionIInputMethodManagerGetEnabledInputMethodSubtypeList        = binder.FirstCallTransaction + 6
	TransactionIInputMethodManagerGetLastInputMethodSubtype               = binder.FirstCallTransaction + 7
	TransactionIInputMethodManagerShowSoftInput                           = binder.FirstCallTransaction + 8
	TransactionIInputMethodManagerHideSoftInput                           = binder.FirstCallTransaction + 9
	TransactionIInputMethodManagerHideSoftInputFromServerForTest          = binder.FirstCallTransaction + 10
	TransactionIInputMethodManagerStartInputOrWindowGainedFocus           = binder.FirstCallTransaction + 11
	TransactionIInputMethodManagerStartInputOrWindowGainedFocusAsync      = binder.FirstCallTransaction + 12
	TransactionIInputMethodManagerShowInputMethodPickerFromClient         = binder.FirstCallTransaction + 13
	TransactionIInputMethodManagerShowInputMethodPickerFromSystem         = binder.FirstCallTransaction + 14
	TransactionIInputMethodManagerIsInputMethodPickerShownForTest         = binder.FirstCallTransaction + 15
	TransactionIInputMethodManagerOnImeSwitchButtonClickFromSystem        = binder.FirstCallTransaction + 16
	TransactionIInputMethodManagerGetCurrentInputMethodSubtype            = binder.FirstCallTransaction + 17
	TransactionIInputMethodManagerSetAdditionalInputMethodSubtypes        = binder.FirstCallTransaction + 18
	TransactionIInputMethodManagerSetExplicitlyEnabledInputMethodSubtypes = binder.FirstCallTransaction + 19
	TransactionIInputMethodManagerGetInputMethodWindowVisibleHeight       = binder.FirstCallTransaction + 20
	TransactionIInputMethodManagerReportPerceptibleAsync                  = binder.FirstCallTransaction + 21
	TransactionIInputMethodManagerRemoveImeSurface                        = binder.FirstCallTransaction + 22
	TransactionIInputMethodManagerRemoveImeSurfaceFromWindowAsync         = binder.FirstCallTransaction + 23
	TransactionIInputMethodManagerStartProtoDump                          = binder.FirstCallTransaction + 24
	TransactionIInputMethodManagerIsImeTraceEnabled                       = binder.FirstCallTransaction + 25
	TransactionIInputMethodManagerStartImeTrace                           = binder.FirstCallTransaction + 26
	TransactionIInputMethodManagerStopImeTrace                            = binder.FirstCallTransaction + 27
	TransactionIInputMethodManagerStartStylusHandwriting                  = binder.FirstCallTransaction + 28
	TransactionIInputMethodManagerStartConnectionlessStylusHandwriting    = binder.FirstCallTransaction + 29
	TransactionIInputMethodManagerPrepareStylusHandwritingDelegation      = binder.FirstCallTransaction + 30
	TransactionIInputMethodManagerAcceptStylusHandwritingDelegation       = binder.FirstCallTransaction + 31
	TransactionIInputMethodManagerAcceptStylusHandwritingDelegationAsync  = binder.FirstCallTransaction + 32
	TransactionIInputMethodManagerIsStylusHandwritingAvailableAsUser      = binder.FirstCallTransaction + 33
	TransactionIInputMethodManagerAddVirtualStylusIdForTestSession        = binder.FirstCallTransaction + 34
	TransactionIInputMethodManagerSetStylusWindowIdleTimeoutForTest       = binder.FirstCallTransaction + 35
	TransactionIInputMethodManagerGetImeTrackerService                    = binder.FirstCallTransaction + 36
)

type IInputMethodManager interface {
	AsBinder() binder.IBinder
	AddClient(ctx context.Context, client internalInputmethod.IInputMethodClient, inputmethod internalInputmethod.IRemoteInputConnection, untrustedDisplayId int32) error
	GetCurrentInputMethodInfoAsUser(ctx context.Context) (viewInputmethod.InputMethodInfo, error)
	GetInputMethodList(ctx context.Context, directBootAwareness int32) (internalInputmethod.InputMethodInfoSafeList, error)
	GetEnabledInputMethodList(ctx context.Context) (internalInputmethod.InputMethodInfoSafeList, error)
	GetInputMethodListLegacy(ctx context.Context, directBootAwareness int32) ([]viewInputmethod.InputMethodInfo, error)
	GetEnabledInputMethodListLegacy(ctx context.Context) ([]viewInputmethod.InputMethodInfo, error)
	GetEnabledInputMethodSubtypeList(ctx context.Context, imiId string, allowsImplicitlyEnabledSubtypes bool) ([]viewInputmethod.InputMethodSubtype, error)
	GetLastInputMethodSubtype(ctx context.Context) (viewInputmethod.InputMethodSubtype, error)
	ShowSoftInput(ctx context.Context, client internalInputmethod.IInputMethodClient, windowToken binder.IBinder, statsToken viewInputmethod.ImeTrackerToken, flags int32, lastClickToolType int32, resultReceiver *os.ResultReceiver, reason int32, async bool) (bool, error)
	HideSoftInput(ctx context.Context, client internalInputmethod.IInputMethodClient, windowToken binder.IBinder, statsToken viewInputmethod.ImeTrackerToken, flags int32, resultReceiver *os.ResultReceiver, reason int32, async bool) (bool, error)
	HideSoftInputFromServerForTest(ctx context.Context) error
	StartInputOrWindowGainedFocus(ctx context.Context, startInputReason int32, client internalInputmethod.IInputMethodClient, windowToken *binder.IBinder, startInputFlags int32, softInputMode int32, windowFlags int32, editorInfo *viewInputmethod.EditorInfo, inputConnection *internalInputmethod.IRemoteInputConnection, remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection, unverifiedTargetSdkVersion int32, imeDispatcher window.ImeOnBackInvokedDispatcher) (internalInputmethod.InputBindResult, error)
	StartInputOrWindowGainedFocusAsync(ctx context.Context, startInputReason int32, client internalInputmethod.IInputMethodClient, windowToken *binder.IBinder, startInputFlags int32, softInputMode int32, windowFlags int32, editorInfo *viewInputmethod.EditorInfo, inputConnection *internalInputmethod.IRemoteInputConnection, remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection, unverifiedTargetSdkVersion int32, imeDispatcher window.ImeOnBackInvokedDispatcher, startInputSeq int32, useAsyncShowHideMethod bool) error
	ShowInputMethodPickerFromClient(ctx context.Context, client internalInputmethod.IInputMethodClient, auxiliarySubtypeMode int32) error
	ShowInputMethodPickerFromSystem(ctx context.Context, auxiliarySubtypeMode int32, displayId int32) error
	IsInputMethodPickerShownForTest(ctx context.Context) (bool, error)
	OnImeSwitchButtonClickFromSystem(ctx context.Context, displayId int32) error
	GetCurrentInputMethodSubtype(ctx context.Context) (viewInputmethod.InputMethodSubtype, error)
	SetAdditionalInputMethodSubtypes(ctx context.Context, id string, subtypes []viewInputmethod.InputMethodSubtype) error
	SetExplicitlyEnabledInputMethodSubtypes(ctx context.Context, imeId string, subtypeHashCodes []int32) error
	GetInputMethodWindowVisibleHeight(ctx context.Context, client internalInputmethod.IInputMethodClient) (int32, error)
	ReportPerceptibleAsync(ctx context.Context, windowToken binder.IBinder, perceptible bool) error
	RemoveImeSurface(ctx context.Context, displayId int32) error
	RemoveImeSurfaceFromWindowAsync(ctx context.Context, windowToken binder.IBinder) error
	StartProtoDump(ctx context.Context, protoDump []byte, source int32, where string) error
	IsImeTraceEnabled(ctx context.Context) (bool, error)
	StartImeTrace(ctx context.Context) error
	StopImeTrace(ctx context.Context) error
	StartStylusHandwriting(ctx context.Context, client internalInputmethod.IInputMethodClient) error
	StartConnectionlessStylusHandwriting(ctx context.Context, client internalInputmethod.IInputMethodClient, cursorAnchorInfo viewInputmethod.CursorAnchorInfo, delegatePackageName string, delegatorPackageName string, callback internalInputmethod.IConnectionlessHandwritingCallback) error
	PrepareStylusHandwritingDelegation(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string) error
	AcceptStylusHandwritingDelegation(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string, flags int32) (bool, error)
	AcceptStylusHandwritingDelegationAsync(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string, flags int32, callback internalInputmethod.IBooleanListener) error
	IsStylusHandwritingAvailableAsUser(ctx context.Context, connectionless bool) (bool, error)
	AddVirtualStylusIdForTestSession(ctx context.Context, client internalInputmethod.IInputMethodClient) error
	SetStylusWindowIdleTimeoutForTest(ctx context.Context, client internalInputmethod.IInputMethodClient, timeout int64) error
	GetImeTrackerService(ctx context.Context) (internalInputmethod.IImeTracker, error)
}

type InputMethodManagerProxy struct {
	remote binder.IBinder
}

func NewInputMethodManagerProxy(
	remote binder.IBinder,
) *InputMethodManagerProxy {
	return &InputMethodManagerProxy{remote: remote}
}

func (p *InputMethodManagerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IInputMethodManager = (*InputMethodManagerProxy)(nil)

func (p *InputMethodManagerProxy) AddClient(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	inputmethod internalInputmethod.IRemoteInputConnection,
	untrustedDisplayId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	binder.WriteBinderToParcel(ctx, _data, inputmethod.AsBinder(), p.remote.Transport())
	_data.WriteInt32(untrustedDisplayId)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "addClient")
	if _err != nil {
		_code = TransactionIInputMethodManagerAddClient
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) GetCurrentInputMethodInfoAsUser(
	ctx context.Context,
) (viewInputmethod.InputMethodInfo, error) {
	var _result viewInputmethod.InputMethodInfo
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getCurrentInputMethodInfoAsUser")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetCurrentInputMethodInfoAsUser
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetInputMethodList(
	ctx context.Context,
	directBootAwareness int32,
) (internalInputmethod.InputMethodInfoSafeList, error) {
	var _result internalInputmethod.InputMethodInfoSafeList
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(directBootAwareness)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getInputMethodList")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetInputMethodList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetEnabledInputMethodList(
	ctx context.Context,
) (internalInputmethod.InputMethodInfoSafeList, error) {
	var _result internalInputmethod.InputMethodInfoSafeList
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getEnabledInputMethodList")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetEnabledInputMethodList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetInputMethodListLegacy(
	ctx context.Context,
	directBootAwareness int32,
) ([]viewInputmethod.InputMethodInfo, error) {
	var _result []viewInputmethod.InputMethodInfo
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(directBootAwareness)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getInputMethodListLegacy")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetInputMethodListLegacy
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]viewInputmethod.InputMethodInfo, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetEnabledInputMethodListLegacy(
	ctx context.Context,
) ([]viewInputmethod.InputMethodInfo, error) {
	var _result []viewInputmethod.InputMethodInfo
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getEnabledInputMethodListLegacy")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetEnabledInputMethodListLegacy
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]viewInputmethod.InputMethodInfo, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetEnabledInputMethodSubtypeList(
	ctx context.Context,
	imiId string,
	allowsImplicitlyEnabledSubtypes bool,
) ([]viewInputmethod.InputMethodSubtype, error) {
	var _result []viewInputmethod.InputMethodSubtype
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteString16(imiId)
	_data.WriteBool(allowsImplicitlyEnabledSubtypes)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getEnabledInputMethodSubtypeList")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetEnabledInputMethodSubtypeList
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]viewInputmethod.InputMethodSubtype, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) GetLastInputMethodSubtype(
	ctx context.Context,
) (viewInputmethod.InputMethodSubtype, error) {
	var _result viewInputmethod.InputMethodSubtype
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getLastInputMethodSubtype")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetLastInputMethodSubtype
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) ShowSoftInput(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	windowToken binder.IBinder,
	statsToken viewInputmethod.ImeTrackerToken,
	flags int32,
	lastClickToolType int32,
	resultReceiver *os.ResultReceiver,
	reason int32,
	async bool,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	binder.WriteBinderToParcel(ctx, _data, windowToken, p.remote.Transport())
	_data.WriteInt32(1)
	if _err := statsToken.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(flags)
	_data.WriteInt32(lastClickToolType)
	if resultReceiver != nil {
		if _err := (*resultReceiver).MarshalParcel(_data); _err != nil {
			return _result, _err
		}
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(reason)
	_data.WriteBool(async)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "showSoftInput")
	if _err != nil {
		_code = TransactionIInputMethodManagerShowSoftInput
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) HideSoftInput(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	windowToken binder.IBinder,
	statsToken viewInputmethod.ImeTrackerToken,
	flags int32,
	resultReceiver *os.ResultReceiver,
	reason int32,
	async bool,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	binder.WriteBinderToParcel(ctx, _data, windowToken, p.remote.Transport())
	_data.WriteInt32(1)
	if _err := statsToken.MarshalParcel(_data); _err != nil {
		return _result, _err
	}
	_data.WriteInt32(flags)
	if resultReceiver != nil {
		if _err := (*resultReceiver).MarshalParcel(_data); _err != nil {
			return _result, _err
		}
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(reason)
	_data.WriteBool(async)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "hideSoftInput")
	if _err != nil {
		_code = TransactionIInputMethodManagerHideSoftInput
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) HideSoftInputFromServerForTest(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "hideSoftInputFromServerForTest")
	if _err != nil {
		_code = TransactionIInputMethodManagerHideSoftInputFromServerForTest
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) StartInputOrWindowGainedFocus(
	ctx context.Context,
	startInputReason int32,
	client internalInputmethod.IInputMethodClient,
	windowToken *binder.IBinder,
	startInputFlags int32,
	softInputMode int32,
	windowFlags int32,
	editorInfo *viewInputmethod.EditorInfo,
	inputConnection *internalInputmethod.IRemoteInputConnection,
	remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection,
	unverifiedTargetSdkVersion int32,
	imeDispatcher window.ImeOnBackInvokedDispatcher,
) (internalInputmethod.InputBindResult, error) {
	var _result internalInputmethod.InputBindResult
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(startInputReason)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	if windowToken != nil {
		_data.WriteStrongBinder((*windowToken).Handle())
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(startInputFlags)
	_data.WriteInt32(softInputMode)
	_data.WriteInt32(windowFlags)
	if editorInfo != nil {
		if _err := (*editorInfo).MarshalParcel(_data); _err != nil {
			return _result, _err
		}
	} else {
		_data.WriteInt32(-1)
	}
	if inputConnection != nil {
		_data.WriteStrongBinder((*inputConnection).AsBinder().Handle())
	} else {
		_data.WriteInt32(-1)
	}
	if remoteAccessibilityInputConnection != nil {
		_data.WriteStrongBinder((*remoteAccessibilityInputConnection).AsBinder().Handle())
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(unverifiedTargetSdkVersion)
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(1)
	if _err := imeDispatcher.MarshalParcel(_data); _err != nil {
		return _result, _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startInputOrWindowGainedFocus")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartInputOrWindowGainedFocus
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) StartInputOrWindowGainedFocusAsync(
	ctx context.Context,
	startInputReason int32,
	client internalInputmethod.IInputMethodClient,
	windowToken *binder.IBinder,
	startInputFlags int32,
	softInputMode int32,
	windowFlags int32,
	editorInfo *viewInputmethod.EditorInfo,
	inputConnection *internalInputmethod.IRemoteInputConnection,
	remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection,
	unverifiedTargetSdkVersion int32,
	imeDispatcher window.ImeOnBackInvokedDispatcher,
	startInputSeq int32,
	useAsyncShowHideMethod bool,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(startInputReason)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	if windowToken != nil {
		_data.WriteStrongBinder((*windowToken).Handle())
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(startInputFlags)
	_data.WriteInt32(softInputMode)
	_data.WriteInt32(windowFlags)
	if editorInfo != nil {
		if _err := (*editorInfo).MarshalParcel(_data); _err != nil {
			return _err
		}
	} else {
		_data.WriteInt32(-1)
	}
	if inputConnection != nil {
		_data.WriteStrongBinder((*inputConnection).AsBinder().Handle())
	} else {
		_data.WriteInt32(-1)
	}
	if remoteAccessibilityInputConnection != nil {
		_data.WriteStrongBinder((*remoteAccessibilityInputConnection).AsBinder().Handle())
	} else {
		_data.WriteInt32(-1)
	}
	_data.WriteInt32(unverifiedTargetSdkVersion)
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(1)
	if _err := imeDispatcher.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(startInputSeq)
	_data.WriteBool(useAsyncShowHideMethod)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startInputOrWindowGainedFocusAsync")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartInputOrWindowGainedFocusAsync
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) ShowInputMethodPickerFromClient(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	auxiliarySubtypeMode int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(auxiliarySubtypeMode)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "showInputMethodPickerFromClient")
	if _err != nil {
		_code = TransactionIInputMethodManagerShowInputMethodPickerFromClient
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) ShowInputMethodPickerFromSystem(
	ctx context.Context,
	auxiliarySubtypeMode int32,
	displayId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(auxiliarySubtypeMode)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "showInputMethodPickerFromSystem")
	if _err != nil {
		_code = TransactionIInputMethodManagerShowInputMethodPickerFromSystem
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) IsInputMethodPickerShownForTest(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "isInputMethodPickerShownForTest")
	if _err != nil {
		_code = TransactionIInputMethodManagerIsInputMethodPickerShownForTest
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) OnImeSwitchButtonClickFromSystem(
	ctx context.Context,
	displayId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "onImeSwitchButtonClickFromSystem")
	if _err != nil {
		_code = TransactionIInputMethodManagerOnImeSwitchButtonClickFromSystem
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InputMethodManagerProxy) GetCurrentInputMethodSubtype(
	ctx context.Context,
) (viewInputmethod.InputMethodSubtype, error) {
	var _result viewInputmethod.InputMethodSubtype
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getCurrentInputMethodSubtype")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetCurrentInputMethodSubtype
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_nullIndicator, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	if _nullIndicator != 0 {
		if _err = _result.UnmarshalParcel(_reply); _err != nil {
			return _result, _err
		}
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) SetAdditionalInputMethodSubtypes(
	ctx context.Context,
	id string,
	subtypes []viewInputmethod.InputMethodSubtype,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteString16(id)
	if subtypes == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(subtypes)))
		for _, _item := range subtypes {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "setAdditionalInputMethodSubtypes")
	if _err != nil {
		_code = TransactionIInputMethodManagerSetAdditionalInputMethodSubtypes
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) SetExplicitlyEnabledInputMethodSubtypes(
	ctx context.Context,
	imeId string,
	subtypeHashCodes []int32,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteString16(imeId)
	if subtypeHashCodes == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(subtypeHashCodes)))
		for _, _item := range subtypeHashCodes {
			_data.WriteInt32(_item)
		}
	}
	_data.WriteInt32(_identity.UserID)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "setExplicitlyEnabledInputMethodSubtypes")
	if _err != nil {
		_code = TransactionIInputMethodManagerSetExplicitlyEnabledInputMethodSubtypes
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) GetInputMethodWindowVisibleHeight(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) (int32, error) {
	var _result int32
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getInputMethodWindowVisibleHeight")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetInputMethodWindowVisibleHeight
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) ReportPerceptibleAsync(
	ctx context.Context,
	windowToken binder.IBinder,
	perceptible bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, windowToken, p.remote.Transport())
	_data.WriteBool(perceptible)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "reportPerceptibleAsync")
	if _err != nil {
		_code = TransactionIInputMethodManagerReportPerceptibleAsync
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InputMethodManagerProxy) RemoveImeSurface(
	ctx context.Context,
	displayId int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(displayId)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "removeImeSurface")
	if _err != nil {
		_code = TransactionIInputMethodManagerRemoveImeSurface
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) RemoveImeSurfaceFromWindowAsync(
	ctx context.Context,
	windowToken binder.IBinder,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, windowToken, p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "removeImeSurfaceFromWindowAsync")
	if _err != nil {
		_code = TransactionIInputMethodManagerRemoveImeSurfaceFromWindowAsync
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InputMethodManagerProxy) StartProtoDump(
	ctx context.Context,
	protoDump []byte,
	source int32,
	where string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	if protoDump == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(protoDump)))
		for _, _item := range protoDump {
			_data.WritePaddedByte(_item)
		}
	}
	_data.WriteInt32(source)
	_data.WriteString16(where)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startProtoDump")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartProtoDump
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) IsImeTraceEnabled(
	ctx context.Context,
) (bool, error) {
	var _result bool
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "isImeTraceEnabled")
	if _err != nil {
		_code = TransactionIInputMethodManagerIsImeTraceEnabled
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) StartImeTrace(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startImeTrace")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartImeTrace
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) StopImeTrace(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "stopImeTrace")
	if _err != nil {
		_code = TransactionIInputMethodManagerStopImeTrace
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) StartStylusHandwriting(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startStylusHandwriting")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartStylusHandwriting
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) StartConnectionlessStylusHandwriting(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	cursorAnchorInfo viewInputmethod.CursorAnchorInfo,
	delegatePackageName string,
	delegatorPackageName string,
	callback internalInputmethod.IConnectionlessHandwritingCallback,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)
	_data.WriteInt32(1)
	if _err := cursorAnchorInfo.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(delegatePackageName)
	_data.WriteString16(delegatorPackageName)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "startConnectionlessStylusHandwriting")
	if _err != nil {
		_code = TransactionIInputMethodManagerStartConnectionlessStylusHandwriting
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InputMethodManagerProxy) PrepareStylusHandwritingDelegation(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)
	_data.WriteString16(delegatePackageName)
	_data.WriteString16(delegatorPackageName)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "prepareStylusHandwritingDelegation")
	if _err != nil {
		_code = TransactionIInputMethodManagerPrepareStylusHandwritingDelegation
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) AcceptStylusHandwritingDelegation(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
	flags int32,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)
	_data.WriteString16(delegatePackageName)
	_data.WriteString16(delegatorPackageName)
	_data.WriteInt32(flags)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "acceptStylusHandwritingDelegation")
	if _err != nil {
		_code = TransactionIInputMethodManagerAcceptStylusHandwritingDelegation
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) AcceptStylusHandwritingDelegationAsync(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
	flags int32,
	callback internalInputmethod.IBooleanListener,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt32(_identity.UserID)
	_data.WriteString16(delegatePackageName)
	_data.WriteString16(delegatorPackageName)
	_data.WriteInt32(flags)
	binder.WriteBinderToParcel(ctx, _data, callback.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "acceptStylusHandwritingDelegationAsync")
	if _err != nil {
		_code = TransactionIInputMethodManagerAcceptStylusHandwritingDelegationAsync
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *InputMethodManagerProxy) IsStylusHandwritingAvailableAsUser(
	ctx context.Context,
	connectionless bool,
) (bool, error) {
	var _result bool
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	_data.WriteInt32(_identity.UserID)
	_data.WriteBool(connectionless)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "isStylusHandwritingAvailableAsUser")
	if _err != nil {
		_code = TransactionIInputMethodManagerIsStylusHandwritingAvailableAsUser
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_result, _err = _reply.ReadBool()
	if _err != nil {
		return _result, _err
	}
	return _result, nil
}

func (p *InputMethodManagerProxy) AddVirtualStylusIdForTestSession(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "addVirtualStylusIdForTestSession")
	if _err != nil {
		_code = TransactionIInputMethodManagerAddVirtualStylusIdForTestSession
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) SetStylusWindowIdleTimeoutForTest(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	timeout int64,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)
	binder.WriteBinderToParcel(ctx, _data, client.AsBinder(), p.remote.Transport())
	_data.WriteInt64(timeout)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "setStylusWindowIdleTimeoutForTest")
	if _err != nil {
		_code = TransactionIInputMethodManagerSetStylusWindowIdleTimeoutForTest
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *InputMethodManagerProxy) GetImeTrackerService(
	ctx context.Context,
) (internalInputmethod.IImeTracker, error) {
	var _result internalInputmethod.IImeTracker
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIInputMethodManager)

	_code, _err := p.remote.ResolveCode(DescriptorIInputMethodManager, "getImeTrackerService")
	if _err != nil {
		_code = TransactionIInputMethodManagerGetImeTrackerService
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_handle, _err := _reply.ReadStrongBinder()
	if _err != nil {
		return _result, _err
	}
	_result = internalInputmethod.NewImeTrackerProxy(binder.NewProxyBinder(p.remote.Transport(), p.remote.Identity(), _handle))
	return _result, nil
}

// InputMethodManagerStub dispatches incoming binder transactions
// to a typed IInputMethodManager implementation.
type InputMethodManagerStub struct {
	Impl IInputMethodManager
}

var _ binder.TransactionReceiver = (*InputMethodManagerStub)(nil)

func (s *InputMethodManagerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIInputMethodManagerAddClient:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_inputmethod internalInputmethod.IRemoteInputConnection
		_ = _arg_inputmethod
		_arg_untrustedDisplayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.AddClient(ctx, _arg_client, _arg_inputmethod, _arg_untrustedDisplayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerGetCurrentInputMethodInfoAsUser:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetCurrentInputMethodInfoAsUser(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerGetInputMethodList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_directBootAwareness, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetInputMethodList(ctx, _arg_directBootAwareness)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerGetEnabledInputMethodList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetEnabledInputMethodList(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerGetInputMethodListLegacy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_directBootAwareness, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetInputMethodListLegacy(ctx, _arg_directBootAwareness)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIInputMethodManagerGetEnabledInputMethodListLegacy:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetEnabledInputMethodListLegacy(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIInputMethodManagerGetEnabledInputMethodSubtypeList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_imiId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_allowsImplicitlyEnabledSubtypes, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetEnabledInputMethodSubtypeList(ctx, _arg_imiId, _arg_allowsImplicitlyEnabledSubtypes)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: array/list return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	case TransactionIInputMethodManagerGetLastInputMethodSubtype:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetLastInputMethodSubtype(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerShowSoftInput:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken binder.IBinder
		_ = _arg_windowToken
		var _arg_statsToken viewInputmethod.ImeTrackerToken
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_statsToken.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_lastClickToolType, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_resultReceiver *os.ResultReceiver
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_resultReceiver.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_async, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.ShowSoftInput(ctx, _arg_client, _arg_windowToken, _arg_statsToken, _arg_flags, _arg_lastClickToolType, _arg_resultReceiver, _arg_reason, _arg_async)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerHideSoftInput:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken binder.IBinder
		_ = _arg_windowToken
		var _arg_statsToken viewInputmethod.ImeTrackerToken
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_statsToken.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_resultReceiver *os.ResultReceiver
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_resultReceiver.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_async, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.HideSoftInput(ctx, _arg_client, _arg_windowToken, _arg_statsToken, _arg_flags, _arg_resultReceiver, _arg_reason, _arg_async)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerHideSoftInputFromServerForTest:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.HideSoftInputFromServerForTest(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerStartInputOrWindowGainedFocus:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_startInputReason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken *binder.IBinder
		_ = _arg_windowToken
		_arg_startInputFlags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_softInputMode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_windowFlags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_editorInfo *viewInputmethod.EditorInfo
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_editorInfo.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_inputConnection *internalInputmethod.IRemoteInputConnection
		_ = _arg_inputConnection
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection
		_ = _arg_remoteAccessibilityInputConnection
		_arg_unverifiedTargetSdkVersion, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		var _arg_imeDispatcher window.ImeOnBackInvokedDispatcher
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_imeDispatcher.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_result, _err := s.Impl.StartInputOrWindowGainedFocus(ctx, _arg_startInputReason, _arg_client, _arg_windowToken, _arg_startInputFlags, _arg_softInputMode, _arg_windowFlags, _arg_editorInfo, _arg_inputConnection, _arg_remoteAccessibilityInputConnection, _arg_unverifiedTargetSdkVersion, _arg_imeDispatcher)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerStartInputOrWindowGainedFocusAsync:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_startInputReason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken *binder.IBinder
		_ = _arg_windowToken
		_arg_startInputFlags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_softInputMode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_windowFlags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_editorInfo *viewInputmethod.EditorInfo
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_editorInfo.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_inputConnection *internalInputmethod.IRemoteInputConnection
		_ = _arg_inputConnection
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection
		_ = _arg_remoteAccessibilityInputConnection
		_arg_unverifiedTargetSdkVersion, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		var _arg_imeDispatcher window.ImeOnBackInvokedDispatcher
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_imeDispatcher.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_startInputSeq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_useAsyncShowHideMethod, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.StartInputOrWindowGainedFocusAsync(ctx, _arg_startInputReason, _arg_client, _arg_windowToken, _arg_startInputFlags, _arg_softInputMode, _arg_windowFlags, _arg_editorInfo, _arg_inputConnection, _arg_remoteAccessibilityInputConnection, _arg_unverifiedTargetSdkVersion, _arg_imeDispatcher, _arg_startInputSeq, _arg_useAsyncShowHideMethod)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerShowInputMethodPickerFromClient:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		_arg_auxiliarySubtypeMode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.ShowInputMethodPickerFromClient(ctx, _arg_client, _arg_auxiliarySubtypeMode)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerShowInputMethodPickerFromSystem:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_auxiliarySubtypeMode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.ShowInputMethodPickerFromSystem(ctx, _arg_auxiliarySubtypeMode, _arg_displayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerIsInputMethodPickerShownForTest:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsInputMethodPickerShownForTest(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerOnImeSwitchButtonClickFromSystem:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnImeSwitchButtonClickFromSystem(ctx, _arg_displayId)
		_ = _err
		return nil, nil
	case TransactionIInputMethodManagerGetCurrentInputMethodSubtype:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetCurrentInputMethodSubtype(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(1)
		if _err := _result.MarshalParcel(_reply); _err != nil {
			return nil, _err
		}
		return _reply, nil
	case TransactionIInputMethodManagerSetAdditionalInputMethodSubtypes:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_id, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_subtypes []viewInputmethod.InputMethodSubtype
		_ = _arg_subtypes
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetAdditionalInputMethodSubtypes(ctx, _arg_id, _arg_subtypes)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerSetExplicitlyEnabledInputMethodSubtypes:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_imeId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_subtypeHashCodes []int32
		_ = _arg_subtypeHashCodes
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetExplicitlyEnabledInputMethodSubtypes(ctx, _arg_imeId, _arg_subtypeHashCodes)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerGetInputMethodWindowVisibleHeight:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		_result, _err := s.Impl.GetInputMethodWindowVisibleHeight(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteInt32(_result)
		return _reply, nil
	case TransactionIInputMethodManagerReportPerceptibleAsync:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken binder.IBinder
		_ = _arg_windowToken
		_arg_perceptible, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.ReportPerceptibleAsync(ctx, _arg_windowToken, _arg_perceptible)
		_ = _err
		return nil, nil
	case TransactionIInputMethodManagerRemoveImeSurface:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_displayId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.RemoveImeSurface(ctx, _arg_displayId)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerRemoveImeSurfaceFromWindowAsync:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_windowToken binder.IBinder
		_ = _arg_windowToken
		_err := s.Impl.RemoveImeSurfaceFromWindowAsync(ctx, _arg_windowToken)
		_ = _err
		return nil, nil
	case TransactionIInputMethodManagerStartProtoDump:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_protoDump []byte
		_ = _arg_protoDump
		_arg_source, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_where, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.StartProtoDump(ctx, _arg_protoDump, _arg_source, _arg_where)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerIsImeTraceEnabled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsImeTraceEnabled(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerStartImeTrace:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.StartImeTrace(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerStopImeTrace:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.StopImeTrace(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerStartStylusHandwriting:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		_err := s.Impl.StartStylusHandwriting(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerStartConnectionlessStylusHandwriting:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		var _arg_cursorAnchorInfo viewInputmethod.CursorAnchorInfo
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_cursorAnchorInfo.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_delegatePackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_delegatorPackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback internalInputmethod.IConnectionlessHandwritingCallback
		_ = _arg_callback
		_err = s.Impl.StartConnectionlessStylusHandwriting(ctx, _arg_client, _arg_cursorAnchorInfo, _arg_delegatePackageName, _arg_delegatorPackageName, _arg_callback)
		_ = _err
		return nil, nil
	case TransactionIInputMethodManagerPrepareStylusHandwritingDelegation:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_delegatePackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_delegatorPackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.PrepareStylusHandwritingDelegation(ctx, _arg_client, _arg_delegatePackageName, _arg_delegatorPackageName)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerAcceptStylusHandwritingDelegation:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_delegatePackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_delegatorPackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.AcceptStylusHandwritingDelegation(ctx, _arg_client, _arg_delegatePackageName, _arg_delegatorPackageName, _arg_flags)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerAcceptStylusHandwritingDelegationAsync:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_delegatePackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_delegatorPackageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_flags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_callback internalInputmethod.IBooleanListener
		_ = _arg_callback
		_err = s.Impl.AcceptStylusHandwritingDelegationAsync(ctx, _arg_client, _arg_delegatePackageName, _arg_delegatorPackageName, _arg_flags, _arg_callback)
		_ = _err
		return nil, nil
	case TransactionIInputMethodManagerIsStylusHandwritingAvailableAsUser:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		_arg_connectionless, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.IsStylusHandwritingAvailableAsUser(ctx, _arg_connectionless)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		_reply.WriteBool(_result)
		return _reply, nil
	case TransactionIInputMethodManagerAddVirtualStylusIdForTestSession:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		_err := s.Impl.AddVirtualStylusIdForTestSession(ctx, _arg_client)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerSetStylusWindowIdleTimeoutForTest:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_client internalInputmethod.IInputMethodClient
		_ = _arg_client
		_arg_timeout, _err := _data.ReadInt64()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.SetStylusWindowIdleTimeoutForTest(ctx, _arg_client, _arg_timeout)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIInputMethodManagerGetImeTrackerService:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_result, _err := s.Impl.GetImeTrackerService(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		// TODO: interface/IBinder return marshaling not yet supported in stubs
		_ = _result
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IInputMethodManagerServer is the server-side interface that user implementations
// provide to NewInputMethodManagerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IInputMethodManagerServer interface {
	AddClient(ctx context.Context, client internalInputmethod.IInputMethodClient, inputmethod internalInputmethod.IRemoteInputConnection, untrustedDisplayId int32) error
	GetCurrentInputMethodInfoAsUser(ctx context.Context) (viewInputmethod.InputMethodInfo, error)
	GetInputMethodList(ctx context.Context, directBootAwareness int32) (internalInputmethod.InputMethodInfoSafeList, error)
	GetEnabledInputMethodList(ctx context.Context) (internalInputmethod.InputMethodInfoSafeList, error)
	GetInputMethodListLegacy(ctx context.Context, directBootAwareness int32) ([]viewInputmethod.InputMethodInfo, error)
	GetEnabledInputMethodListLegacy(ctx context.Context) ([]viewInputmethod.InputMethodInfo, error)
	GetEnabledInputMethodSubtypeList(ctx context.Context, imiId string, allowsImplicitlyEnabledSubtypes bool) ([]viewInputmethod.InputMethodSubtype, error)
	GetLastInputMethodSubtype(ctx context.Context) (viewInputmethod.InputMethodSubtype, error)
	ShowSoftInput(ctx context.Context, client internalInputmethod.IInputMethodClient, windowToken binder.IBinder, statsToken viewInputmethod.ImeTrackerToken, flags int32, lastClickToolType int32, resultReceiver *os.ResultReceiver, reason int32, async bool) (bool, error)
	HideSoftInput(ctx context.Context, client internalInputmethod.IInputMethodClient, windowToken binder.IBinder, statsToken viewInputmethod.ImeTrackerToken, flags int32, resultReceiver *os.ResultReceiver, reason int32, async bool) (bool, error)
	HideSoftInputFromServerForTest(ctx context.Context) error
	StartInputOrWindowGainedFocus(ctx context.Context, startInputReason int32, client internalInputmethod.IInputMethodClient, windowToken *binder.IBinder, startInputFlags int32, softInputMode int32, windowFlags int32, editorInfo *viewInputmethod.EditorInfo, inputConnection *internalInputmethod.IRemoteInputConnection, remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection, unverifiedTargetSdkVersion int32, imeDispatcher window.ImeOnBackInvokedDispatcher) (internalInputmethod.InputBindResult, error)
	StartInputOrWindowGainedFocusAsync(ctx context.Context, startInputReason int32, client internalInputmethod.IInputMethodClient, windowToken *binder.IBinder, startInputFlags int32, softInputMode int32, windowFlags int32, editorInfo *viewInputmethod.EditorInfo, inputConnection *internalInputmethod.IRemoteInputConnection, remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection, unverifiedTargetSdkVersion int32, imeDispatcher window.ImeOnBackInvokedDispatcher, startInputSeq int32, useAsyncShowHideMethod bool) error
	ShowInputMethodPickerFromClient(ctx context.Context, client internalInputmethod.IInputMethodClient, auxiliarySubtypeMode int32) error
	ShowInputMethodPickerFromSystem(ctx context.Context, auxiliarySubtypeMode int32, displayId int32) error
	IsInputMethodPickerShownForTest(ctx context.Context) (bool, error)
	OnImeSwitchButtonClickFromSystem(ctx context.Context, displayId int32) error
	GetCurrentInputMethodSubtype(ctx context.Context) (viewInputmethod.InputMethodSubtype, error)
	SetAdditionalInputMethodSubtypes(ctx context.Context, id string, subtypes []viewInputmethod.InputMethodSubtype) error
	SetExplicitlyEnabledInputMethodSubtypes(ctx context.Context, imeId string, subtypeHashCodes []int32) error
	GetInputMethodWindowVisibleHeight(ctx context.Context, client internalInputmethod.IInputMethodClient) (int32, error)
	ReportPerceptibleAsync(ctx context.Context, windowToken binder.IBinder, perceptible bool) error
	RemoveImeSurface(ctx context.Context, displayId int32) error
	RemoveImeSurfaceFromWindowAsync(ctx context.Context, windowToken binder.IBinder) error
	StartProtoDump(ctx context.Context, protoDump []byte, source int32, where string) error
	IsImeTraceEnabled(ctx context.Context) (bool, error)
	StartImeTrace(ctx context.Context) error
	StopImeTrace(ctx context.Context) error
	StartStylusHandwriting(ctx context.Context, client internalInputmethod.IInputMethodClient) error
	StartConnectionlessStylusHandwriting(ctx context.Context, client internalInputmethod.IInputMethodClient, cursorAnchorInfo viewInputmethod.CursorAnchorInfo, delegatePackageName string, delegatorPackageName string, callback internalInputmethod.IConnectionlessHandwritingCallback) error
	PrepareStylusHandwritingDelegation(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string) error
	AcceptStylusHandwritingDelegation(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string, flags int32) (bool, error)
	AcceptStylusHandwritingDelegationAsync(ctx context.Context, client internalInputmethod.IInputMethodClient, delegatePackageName string, delegatorPackageName string, flags int32, callback internalInputmethod.IBooleanListener) error
	IsStylusHandwritingAvailableAsUser(ctx context.Context, connectionless bool) (bool, error)
	AddVirtualStylusIdForTestSession(ctx context.Context, client internalInputmethod.IInputMethodClient) error
	SetStylusWindowIdleTimeoutForTest(ctx context.Context, client internalInputmethod.IInputMethodClient, timeout int64) error
	GetImeTrackerService(ctx context.Context) (internalInputmethod.IImeTracker, error)
}

type inputMethodManagerStubWrapper struct {
	impl       IInputMethodManagerServer
	stubBinder *binder.StubBinder
}

func (w *inputMethodManagerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *inputMethodManagerStubWrapper) AddClient(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	inputmethod internalInputmethod.IRemoteInputConnection,
	untrustedDisplayId int32,
) error {
	return w.impl.AddClient(ctx, client, inputmethod, untrustedDisplayId)
}

func (w *inputMethodManagerStubWrapper) GetCurrentInputMethodInfoAsUser(
	ctx context.Context,
) (viewInputmethod.InputMethodInfo, error) {
	return w.impl.GetCurrentInputMethodInfoAsUser(ctx)
}

func (w *inputMethodManagerStubWrapper) GetInputMethodList(
	ctx context.Context,
	directBootAwareness int32,
) (internalInputmethod.InputMethodInfoSafeList, error) {
	return w.impl.GetInputMethodList(ctx, directBootAwareness)
}

func (w *inputMethodManagerStubWrapper) GetEnabledInputMethodList(
	ctx context.Context,
) (internalInputmethod.InputMethodInfoSafeList, error) {
	return w.impl.GetEnabledInputMethodList(ctx)
}

func (w *inputMethodManagerStubWrapper) GetInputMethodListLegacy(
	ctx context.Context,
	directBootAwareness int32,
) ([]viewInputmethod.InputMethodInfo, error) {
	return w.impl.GetInputMethodListLegacy(ctx, directBootAwareness)
}

func (w *inputMethodManagerStubWrapper) GetEnabledInputMethodListLegacy(
	ctx context.Context,
) ([]viewInputmethod.InputMethodInfo, error) {
	return w.impl.GetEnabledInputMethodListLegacy(ctx)
}

func (w *inputMethodManagerStubWrapper) GetEnabledInputMethodSubtypeList(
	ctx context.Context,
	imiId string,
	allowsImplicitlyEnabledSubtypes bool,
) ([]viewInputmethod.InputMethodSubtype, error) {
	return w.impl.GetEnabledInputMethodSubtypeList(ctx, imiId, allowsImplicitlyEnabledSubtypes)
}

func (w *inputMethodManagerStubWrapper) GetLastInputMethodSubtype(
	ctx context.Context,
) (viewInputmethod.InputMethodSubtype, error) {
	return w.impl.GetLastInputMethodSubtype(ctx)
}

func (w *inputMethodManagerStubWrapper) ShowSoftInput(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	windowToken binder.IBinder,
	statsToken viewInputmethod.ImeTrackerToken,
	flags int32,
	lastClickToolType int32,
	resultReceiver *os.ResultReceiver,
	reason int32,
	async bool,
) (bool, error) {
	return w.impl.ShowSoftInput(ctx, client, windowToken, statsToken, flags, lastClickToolType, resultReceiver, reason, async)
}

func (w *inputMethodManagerStubWrapper) HideSoftInput(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	windowToken binder.IBinder,
	statsToken viewInputmethod.ImeTrackerToken,
	flags int32,
	resultReceiver *os.ResultReceiver,
	reason int32,
	async bool,
) (bool, error) {
	return w.impl.HideSoftInput(ctx, client, windowToken, statsToken, flags, resultReceiver, reason, async)
}

func (w *inputMethodManagerStubWrapper) HideSoftInputFromServerForTest(
	ctx context.Context,
) error {
	return w.impl.HideSoftInputFromServerForTest(ctx)
}

func (w *inputMethodManagerStubWrapper) StartInputOrWindowGainedFocus(
	ctx context.Context,
	startInputReason int32,
	client internalInputmethod.IInputMethodClient,
	windowToken *binder.IBinder,
	startInputFlags int32,
	softInputMode int32,
	windowFlags int32,
	editorInfo *viewInputmethod.EditorInfo,
	inputConnection *internalInputmethod.IRemoteInputConnection,
	remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection,
	unverifiedTargetSdkVersion int32,
	imeDispatcher window.ImeOnBackInvokedDispatcher,
) (internalInputmethod.InputBindResult, error) {
	return w.impl.StartInputOrWindowGainedFocus(ctx, startInputReason, client, windowToken, startInputFlags, softInputMode, windowFlags, editorInfo, inputConnection, remoteAccessibilityInputConnection, unverifiedTargetSdkVersion, imeDispatcher)
}

func (w *inputMethodManagerStubWrapper) StartInputOrWindowGainedFocusAsync(
	ctx context.Context,
	startInputReason int32,
	client internalInputmethod.IInputMethodClient,
	windowToken *binder.IBinder,
	startInputFlags int32,
	softInputMode int32,
	windowFlags int32,
	editorInfo *viewInputmethod.EditorInfo,
	inputConnection *internalInputmethod.IRemoteInputConnection,
	remoteAccessibilityInputConnection *internalInputmethod.IRemoteAccessibilityInputConnection,
	unverifiedTargetSdkVersion int32,
	imeDispatcher window.ImeOnBackInvokedDispatcher,
	startInputSeq int32,
	useAsyncShowHideMethod bool,
) error {
	return w.impl.StartInputOrWindowGainedFocusAsync(ctx, startInputReason, client, windowToken, startInputFlags, softInputMode, windowFlags, editorInfo, inputConnection, remoteAccessibilityInputConnection, unverifiedTargetSdkVersion, imeDispatcher, startInputSeq, useAsyncShowHideMethod)
}

func (w *inputMethodManagerStubWrapper) ShowInputMethodPickerFromClient(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	auxiliarySubtypeMode int32,
) error {
	return w.impl.ShowInputMethodPickerFromClient(ctx, client, auxiliarySubtypeMode)
}

func (w *inputMethodManagerStubWrapper) ShowInputMethodPickerFromSystem(
	ctx context.Context,
	auxiliarySubtypeMode int32,
	displayId int32,
) error {
	return w.impl.ShowInputMethodPickerFromSystem(ctx, auxiliarySubtypeMode, displayId)
}

func (w *inputMethodManagerStubWrapper) IsInputMethodPickerShownForTest(
	ctx context.Context,
) (bool, error) {
	return w.impl.IsInputMethodPickerShownForTest(ctx)
}

func (w *inputMethodManagerStubWrapper) OnImeSwitchButtonClickFromSystem(
	ctx context.Context,
	displayId int32,
) error {
	return w.impl.OnImeSwitchButtonClickFromSystem(ctx, displayId)
}

func (w *inputMethodManagerStubWrapper) GetCurrentInputMethodSubtype(
	ctx context.Context,
) (viewInputmethod.InputMethodSubtype, error) {
	return w.impl.GetCurrentInputMethodSubtype(ctx)
}

func (w *inputMethodManagerStubWrapper) SetAdditionalInputMethodSubtypes(
	ctx context.Context,
	id string,
	subtypes []viewInputmethod.InputMethodSubtype,
) error {
	return w.impl.SetAdditionalInputMethodSubtypes(ctx, id, subtypes)
}

func (w *inputMethodManagerStubWrapper) SetExplicitlyEnabledInputMethodSubtypes(
	ctx context.Context,
	imeId string,
	subtypeHashCodes []int32,
) error {
	return w.impl.SetExplicitlyEnabledInputMethodSubtypes(ctx, imeId, subtypeHashCodes)
}

func (w *inputMethodManagerStubWrapper) GetInputMethodWindowVisibleHeight(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) (int32, error) {
	return w.impl.GetInputMethodWindowVisibleHeight(ctx, client)
}

func (w *inputMethodManagerStubWrapper) ReportPerceptibleAsync(
	ctx context.Context,
	windowToken binder.IBinder,
	perceptible bool,
) error {
	return w.impl.ReportPerceptibleAsync(ctx, windowToken, perceptible)
}

func (w *inputMethodManagerStubWrapper) RemoveImeSurface(
	ctx context.Context,
	displayId int32,
) error {
	return w.impl.RemoveImeSurface(ctx, displayId)
}

func (w *inputMethodManagerStubWrapper) RemoveImeSurfaceFromWindowAsync(
	ctx context.Context,
	windowToken binder.IBinder,
) error {
	return w.impl.RemoveImeSurfaceFromWindowAsync(ctx, windowToken)
}

func (w *inputMethodManagerStubWrapper) StartProtoDump(
	ctx context.Context,
	protoDump []byte,
	source int32,
	where string,
) error {
	return w.impl.StartProtoDump(ctx, protoDump, source, where)
}

func (w *inputMethodManagerStubWrapper) IsImeTraceEnabled(
	ctx context.Context,
) (bool, error) {
	return w.impl.IsImeTraceEnabled(ctx)
}

func (w *inputMethodManagerStubWrapper) StartImeTrace(
	ctx context.Context,
) error {
	return w.impl.StartImeTrace(ctx)
}

func (w *inputMethodManagerStubWrapper) StopImeTrace(
	ctx context.Context,
) error {
	return w.impl.StopImeTrace(ctx)
}

func (w *inputMethodManagerStubWrapper) StartStylusHandwriting(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) error {
	return w.impl.StartStylusHandwriting(ctx, client)
}

func (w *inputMethodManagerStubWrapper) StartConnectionlessStylusHandwriting(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	cursorAnchorInfo viewInputmethod.CursorAnchorInfo,
	delegatePackageName string,
	delegatorPackageName string,
	callback internalInputmethod.IConnectionlessHandwritingCallback,
) error {
	return w.impl.StartConnectionlessStylusHandwriting(ctx, client, cursorAnchorInfo, delegatePackageName, delegatorPackageName, callback)
}

func (w *inputMethodManagerStubWrapper) PrepareStylusHandwritingDelegation(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
) error {
	return w.impl.PrepareStylusHandwritingDelegation(ctx, client, delegatePackageName, delegatorPackageName)
}

func (w *inputMethodManagerStubWrapper) AcceptStylusHandwritingDelegation(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
	flags int32,
) (bool, error) {
	return w.impl.AcceptStylusHandwritingDelegation(ctx, client, delegatePackageName, delegatorPackageName, flags)
}

func (w *inputMethodManagerStubWrapper) AcceptStylusHandwritingDelegationAsync(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	delegatePackageName string,
	delegatorPackageName string,
	flags int32,
	callback internalInputmethod.IBooleanListener,
) error {
	return w.impl.AcceptStylusHandwritingDelegationAsync(ctx, client, delegatePackageName, delegatorPackageName, flags, callback)
}

func (w *inputMethodManagerStubWrapper) IsStylusHandwritingAvailableAsUser(
	ctx context.Context,
	connectionless bool,
) (bool, error) {
	return w.impl.IsStylusHandwritingAvailableAsUser(ctx, connectionless)
}

func (w *inputMethodManagerStubWrapper) AddVirtualStylusIdForTestSession(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
) error {
	return w.impl.AddVirtualStylusIdForTestSession(ctx, client)
}

func (w *inputMethodManagerStubWrapper) SetStylusWindowIdleTimeoutForTest(
	ctx context.Context,
	client internalInputmethod.IInputMethodClient,
	timeout int64,
) error {
	return w.impl.SetStylusWindowIdleTimeoutForTest(ctx, client, timeout)
}

func (w *inputMethodManagerStubWrapper) GetImeTrackerService(
	ctx context.Context,
) (internalInputmethod.IImeTracker, error) {
	return w.impl.GetImeTrackerService(ctx)
}

var _ IInputMethodManager = (*inputMethodManagerStubWrapper)(nil)

// NewInputMethodManagerStub creates a server-side IInputMethodManager wrapping the given
// server implementation. The returned value satisfies IInputMethodManager
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewInputMethodManagerStub(
	impl IInputMethodManagerServer,
) IInputMethodManager {
	wrapper := &inputMethodManagerStubWrapper{impl: impl}
	stub := &InputMethodManagerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
