// Code generated by genparcelgo. DO NOT EDIT.

package translation

import (
	"github.com/xaionaro-go/binder/parcel"
)

type TranslationRequest struct {
	Flags int32
	// TranslationRequestValues: opaque type — not yet supported
	// ViewTranslationRequests: opaque type — not yet supported
}

var _ parcel.Parcelable = (*TranslationRequest)(nil)

func (s *TranslationRequest) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(s.Flags)
	return nil
}

func (s *TranslationRequest) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Flags, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
