package gui

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type Color struct {
	R float32
	G float32
	B float32
	A float32
}

var _ parcel.Parcelable = (*Color)(nil)

func (s *Color) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.R)
	p.WriteFloat32(s.G)
	p.WriteFloat32(s.B)
	p.WriteFloat32(s.A)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *Color) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.R, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.G, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.B, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.A, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
