package gui

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIJankListener = "android.gui.IJankListener"

const (
	TransactionIJankListenerOnJankData = binder.FirstCallTransaction + 0
)

type IJankListener interface {
	AsBinder() binder.IBinder
	OnJankData(ctx context.Context, data []JankData) error
}

type JankListenerProxy struct {
	remote binder.IBinder
}

func NewJankListenerProxy(
	remote binder.IBinder,
) *JankListenerProxy {
	return &JankListenerProxy{remote: remote}
}

func (p *JankListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IJankListener = (*JankListenerProxy)(nil)

func (p *JankListenerProxy) OnJankData(
	ctx context.Context,
	data []JankData,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIJankListener)
	if data == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(data)))
		for _, _item := range data {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIJankListener, "onJankData")
	if _err != nil {
		_code = TransactionIJankListenerOnJankData
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// JankListenerStub dispatches incoming binder transactions
// to a typed IJankListener implementation.
type JankListenerStub struct {
	Impl IJankListener
}

var _ binder.TransactionReceiver = (*JankListenerStub)(nil)

func (s *JankListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIJankListenerOnJankData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_data []JankData
		_ = _arg_data
		_err := s.Impl.OnJankData(ctx, _arg_data)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IJankListenerServer is the server-side interface that user implementations
// provide to NewJankListenerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IJankListenerServer interface {
	OnJankData(ctx context.Context, data []JankData) error
}

type jankListenerStubWrapper struct {
	impl       IJankListenerServer
	stubBinder *binder.StubBinder
}

func (w *jankListenerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *jankListenerStubWrapper) OnJankData(
	ctx context.Context,
	data []JankData,
) error {
	return w.impl.OnJankData(ctx, data)
}

var _ IJankListener = (*jankListenerStubWrapper)(nil)

// NewJankListenerStub creates a server-side IJankListener wrapping the given
// server implementation. The returned value satisfies IJankListener
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewJankListenerStub(
	impl IJankListenerServer,
) IJankListener {
	wrapper := &jankListenerStubWrapper{impl: impl}
	stub := &JankListenerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
