package IBluetoothAudioProvider

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type StreamConfig struct {
	AudioContext interface{}
	StreamMap    []interface{}
}

var _ parcel.Parcelable = (*StreamConfig)(nil)

func (s *StreamConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if s.StreamMap == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.StreamMap)))
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *StreamConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.StreamMap = make([]interface{}, _count0)
		for _i := int32(0); _i < _count0; _i++ {
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
