package satellite

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SatelliteCapabilities struct {
	IsPointingRequired          bool
	MaxBytesPerOutgoingDatagram int32
}

var _ parcel.Parcelable = (*SatelliteCapabilities)(nil)

func (s *SatelliteCapabilities) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(0) // null SupportedRadioTechnologies.size()
	p.WriteBool(s.IsPointingRequired)
	p.WriteInt32(s.MaxBytesPerOutgoingDatagram)
	p.WriteInt32(0) // null Size
	return nil
}

func (s *SatelliteCapabilities) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null SupportedRadioTechnologies.size(): cannot skip unknown-size typed object
		}
	}
	s.IsPointingRequired, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.MaxBytesPerOutgoingDatagram, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null Size: cannot skip unknown-size typed object
		}
	}
	return nil
}
