package os

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIDumpstate = "android.os.IDumpstate"

const (
	TransactionIDumpstatePreDumpUiData     = binder.FirstCallTransaction + 0
	TransactionIDumpstateStartBugreport    = binder.FirstCallTransaction + 1
	TransactionIDumpstateCancelBugreport   = binder.FirstCallTransaction + 2
	TransactionIDumpstateRetrieveBugreport = binder.FirstCallTransaction + 3
)

type IDumpstate interface {
	AsBinder() binder.IBinder
	PreDumpUiData(ctx context.Context) error
	StartBugreport(ctx context.Context, bugreportFd interface{}, screenshotFd interface{}, bugreportMode int32, bugreportFlags int32, listener IDumpstateListener, isScreenshotRequested bool, skipUserConsent bool) error
	CancelBugreport(ctx context.Context) error
	RetrieveBugreport(ctx context.Context, bugreportFd interface{}, bugreportFile string, keepBugreportOnRetrieval bool, skipUserConsent bool, listener IDumpstateListener) error
}

const (
	IDumpstateBugreportModeFull                     int32 = 0
	IDumpstateBugreportModeInteractive              int32 = 1
	IDumpstateBugreportModeRemote                   int32 = 2
	IDumpstateBugreportModeWear                     int32 = 3
	IDumpstateBugreportModeTelephony                int32 = 4
	IDumpstateBugreportModeWifi                     int32 = 5
	IDumpstateBugreportModeDefault                  int32 = 6
	IDumpstateBugreportModeOnboarding               int32 = 7
	IDumpstateBugreportFlagUsePredumpedUiData       int32 = 1
	IDumpstateBugreportFlagDeferConsent             int32 = 2
	IDumpstateBugreportFlagKeepBugreportOnRetrieval int32 = 4
)

type DumpstateProxy struct {
	remote binder.IBinder
}

func NewDumpstateProxy(
	remote binder.IBinder,
) *DumpstateProxy {
	return &DumpstateProxy{remote: remote}
}

func (p *DumpstateProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IDumpstate = (*DumpstateProxy)(nil)

func (p *DumpstateProxy) PreDumpUiData(
	ctx context.Context,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIDumpstate)
	_data.WriteString16(_identity.PackageName)

	_code, _err := p.remote.ResolveCode(DescriptorIDumpstate, "preDumpUiData")
	if _err != nil {
		_code = TransactionIDumpstatePreDumpUiData
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *DumpstateProxy) StartBugreport(
	ctx context.Context,
	bugreportFd interface{},
	screenshotFd interface{},
	bugreportMode int32,
	bugreportFlags int32,
	listener IDumpstateListener,
	isScreenshotRequested bool,
	skipUserConsent bool,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIDumpstate)
	_data.WriteInt32(_identity.UID)
	_data.WriteString16(_identity.PackageName)
	_data.WriteInt32(bugreportMode)
	_data.WriteInt32(bugreportFlags)
	binder.WriteBinderToParcel(ctx, _data, listener.AsBinder(), p.remote.Transport())
	_data.WriteBool(isScreenshotRequested)
	_data.WriteBool(skipUserConsent)

	_code, _err := p.remote.ResolveCode(DescriptorIDumpstate, "startBugreport")
	if _err != nil {
		_code = TransactionIDumpstateStartBugreport
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *DumpstateProxy) CancelBugreport(
	ctx context.Context,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIDumpstate)
	_data.WriteInt32(_identity.UID)
	_data.WriteString16(_identity.PackageName)

	_code, _err := p.remote.ResolveCode(DescriptorIDumpstate, "cancelBugreport")
	if _err != nil {
		_code = TransactionIDumpstateCancelBugreport
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

func (p *DumpstateProxy) RetrieveBugreport(
	ctx context.Context,
	bugreportFd interface{},
	bugreportFile string,
	keepBugreportOnRetrieval bool,
	skipUserConsent bool,
	listener IDumpstateListener,
) error {
	_identity := p.remote.Identity()
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIDumpstate)
	_data.WriteInt32(_identity.UID)
	_data.WriteString16(_identity.PackageName)
	_data.WriteInt32(_identity.UserID)
	_data.WriteString16(bugreportFile)
	_data.WriteBool(keepBugreportOnRetrieval)
	_data.WriteBool(skipUserConsent)
	binder.WriteBinderToParcel(ctx, _data, listener.AsBinder(), p.remote.Transport())

	_code, _err := p.remote.ResolveCode(DescriptorIDumpstate, "retrieveBugreport")
	if _err != nil {
		_code = TransactionIDumpstateRetrieveBugreport
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// DumpstateStub dispatches incoming binder transactions
// to a typed IDumpstate implementation.
type DumpstateStub struct {
	Impl IDumpstate
}

var _ binder.TransactionReceiver = (*DumpstateStub)(nil)

func (s *DumpstateStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIDumpstatePreDumpUiData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.PreDumpUiData(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIDumpstateStartBugreport:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		var _arg_bugreportFd interface{}
		var _arg_screenshotFd interface{}
		_arg_bugreportMode, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_bugreportFlags, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_listener IDumpstateListener
		_ = _arg_listener
		_arg_isScreenshotRequested, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_skipUserConsent, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.StartBugreport(ctx, _arg_bugreportFd, _arg_screenshotFd, _arg_bugreportMode, _arg_bugreportFlags, _arg_listener, _arg_isScreenshotRequested, _arg_skipUserConsent)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIDumpstateCancelBugreport:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.CancelBugreport(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	case TransactionIDumpstateRetrieveBugreport:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		if _, _err := _data.ReadInt32(); _err != nil {
			return nil, _err
		}
		var _arg_bugreportFd interface{}
		_arg_bugreportFile, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_keepBugreportOnRetrieval, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_arg_skipUserConsent, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_listener IDumpstateListener
		_ = _arg_listener
		_err = s.Impl.RetrieveBugreport(ctx, _arg_bugreportFd, _arg_bugreportFile, _arg_keepBugreportOnRetrieval, _arg_skipUserConsent, _arg_listener)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IDumpstateServer is the server-side interface that user implementations
// provide to NewDumpstateStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IDumpstateServer interface {
	PreDumpUiData(ctx context.Context) error
	StartBugreport(ctx context.Context, bugreportFd interface{}, screenshotFd interface{}, bugreportMode int32, bugreportFlags int32, listener IDumpstateListener, isScreenshotRequested bool, skipUserConsent bool) error
	CancelBugreport(ctx context.Context) error
	RetrieveBugreport(ctx context.Context, bugreportFd interface{}, bugreportFile string, keepBugreportOnRetrieval bool, skipUserConsent bool, listener IDumpstateListener) error
}

type dumpstateStubWrapper struct {
	impl       IDumpstateServer
	stubBinder *binder.StubBinder
}

func (w *dumpstateStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *dumpstateStubWrapper) PreDumpUiData(
	ctx context.Context,
) error {
	return w.impl.PreDumpUiData(ctx)
}

func (w *dumpstateStubWrapper) StartBugreport(
	ctx context.Context,
	bugreportFd interface{},
	screenshotFd interface{},
	bugreportMode int32,
	bugreportFlags int32,
	listener IDumpstateListener,
	isScreenshotRequested bool,
	skipUserConsent bool,
) error {
	return w.impl.StartBugreport(ctx, bugreportFd, screenshotFd, bugreportMode, bugreportFlags, listener, isScreenshotRequested, skipUserConsent)
}

func (w *dumpstateStubWrapper) CancelBugreport(
	ctx context.Context,
) error {
	return w.impl.CancelBugreport(ctx)
}

func (w *dumpstateStubWrapper) RetrieveBugreport(
	ctx context.Context,
	bugreportFd interface{},
	bugreportFile string,
	keepBugreportOnRetrieval bool,
	skipUserConsent bool,
	listener IDumpstateListener,
) error {
	return w.impl.RetrieveBugreport(ctx, bugreportFd, bugreportFile, keepBugreportOnRetrieval, skipUserConsent, listener)
}

var _ IDumpstate = (*dumpstateStubWrapper)(nil)

// NewDumpstateStub creates a server-side IDumpstate wrapping the given
// server implementation. The returned value satisfies IDumpstate
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewDumpstateStub(
	impl IDumpstateServer,
) IDumpstate {
	wrapper := &dumpstateStubWrapper{impl: impl}
	stub := &DumpstateStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
