package recents

import (
	"context"
	"fmt"
	graphics "github.com/xaionaro-go/binder/android/graphics"
	os "github.com/xaionaro-go/binder/android/os"
	view "github.com/xaionaro-go/binder/android/view"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIRecentsAnimationRunner = "com.android.wm.shell.recents.IRecentsAnimationRunner"

const (
	TransactionIRecentsAnimationRunnerOnAnimationCanceled = binder.FirstCallTransaction + 0
	TransactionIRecentsAnimationRunnerOnAnimationStart    = binder.FirstCallTransaction + 1
	TransactionIRecentsAnimationRunnerOnTasksAppeared     = binder.FirstCallTransaction + 2
)

type IRecentsAnimationRunner interface {
	AsBinder() binder.IBinder
	OnAnimationCanceled(ctx context.Context, taskIds []int32, taskSnapshots []view.WindowManagerTaskSnapshot) error
	OnAnimationStart(ctx context.Context, controller IRecentsAnimationController, apps []view.RemoteAnimationTarget, wallpapers []view.RemoteAnimationTarget, homeContentInsets graphics.Rect, minimizedHomeBounds graphics.Rect, extras os.Bundle) error
	OnTasksAppeared(ctx context.Context, app []view.RemoteAnimationTarget) error
}

type RecentsAnimationRunnerProxy struct {
	remote binder.IBinder
}

func NewRecentsAnimationRunnerProxy(
	remote binder.IBinder,
) *RecentsAnimationRunnerProxy {
	return &RecentsAnimationRunnerProxy{remote: remote}
}

func (p *RecentsAnimationRunnerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IRecentsAnimationRunner = (*RecentsAnimationRunnerProxy)(nil)

func (p *RecentsAnimationRunnerProxy) OnAnimationCanceled(
	ctx context.Context,
	taskIds []int32,
	taskSnapshots []view.WindowManagerTaskSnapshot,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecentsAnimationRunner)
	if taskIds == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(taskIds)))
		for _, _item := range taskIds {
			_data.WriteInt32(_item)
		}
	}
	if taskSnapshots == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(taskSnapshots)))
		for _, _item := range taskSnapshots {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIRecentsAnimationRunner, "onAnimationCanceled")
	if _err != nil {
		_code = TransactionIRecentsAnimationRunnerOnAnimationCanceled
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *RecentsAnimationRunnerProxy) OnAnimationStart(
	ctx context.Context,
	controller IRecentsAnimationController,
	apps []view.RemoteAnimationTarget,
	wallpapers []view.RemoteAnimationTarget,
	homeContentInsets graphics.Rect,
	minimizedHomeBounds graphics.Rect,
	extras os.Bundle,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecentsAnimationRunner)
	binder.WriteBinderToParcel(ctx, _data, controller.AsBinder(), p.remote.Transport())
	if apps == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(apps)))
		for _, _item := range apps {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}
	if wallpapers == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(wallpapers)))
		for _, _item := range wallpapers {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}
	_data.WriteInt32(1)
	if _err := homeContentInsets.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := minimizedHomeBounds.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(1)
	if _err := extras.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIRecentsAnimationRunner, "onAnimationStart")
	if _err != nil {
		_code = TransactionIRecentsAnimationRunnerOnAnimationStart
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *RecentsAnimationRunnerProxy) OnTasksAppeared(
	ctx context.Context,
	app []view.RemoteAnimationTarget,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIRecentsAnimationRunner)
	if app == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(app)))
		for _, _item := range app {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIRecentsAnimationRunner, "onTasksAppeared")
	if _err != nil {
		_code = TransactionIRecentsAnimationRunnerOnTasksAppeared
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// RecentsAnimationRunnerStub dispatches incoming binder transactions
// to a typed IRecentsAnimationRunner implementation.
type RecentsAnimationRunnerStub struct {
	Impl IRecentsAnimationRunner
}

var _ binder.TransactionReceiver = (*RecentsAnimationRunnerStub)(nil)

func (s *RecentsAnimationRunnerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIRecentsAnimationRunnerOnAnimationCanceled:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_taskIds []int32
		_ = _arg_taskIds
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_taskSnapshots []view.WindowManagerTaskSnapshot
		_ = _arg_taskSnapshots
		_err := s.Impl.OnAnimationCanceled(ctx, _arg_taskIds, _arg_taskSnapshots)
		_ = _err
		return nil, nil
	case TransactionIRecentsAnimationRunnerOnAnimationStart:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_controller IRecentsAnimationController
		_ = _arg_controller
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_apps []view.RemoteAnimationTarget
		_ = _arg_apps
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_wallpapers []view.RemoteAnimationTarget
		_ = _arg_wallpapers
		var _arg_homeContentInsets graphics.Rect
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_homeContentInsets.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_minimizedHomeBounds graphics.Rect
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_minimizedHomeBounds.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_extras os.Bundle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_extras.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.OnAnimationStart(ctx, _arg_controller, _arg_apps, _arg_wallpapers, _arg_homeContentInsets, _arg_minimizedHomeBounds, _arg_extras)
		_ = _err
		return nil, nil
	case TransactionIRecentsAnimationRunnerOnTasksAppeared:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_app []view.RemoteAnimationTarget
		_ = _arg_app
		_err := s.Impl.OnTasksAppeared(ctx, _arg_app)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IRecentsAnimationRunnerServer is the server-side interface that user implementations
// provide to NewRecentsAnimationRunnerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IRecentsAnimationRunnerServer interface {
	OnAnimationCanceled(ctx context.Context, taskIds []int32, taskSnapshots []view.WindowManagerTaskSnapshot) error
	OnAnimationStart(ctx context.Context, controller IRecentsAnimationController, apps []view.RemoteAnimationTarget, wallpapers []view.RemoteAnimationTarget, homeContentInsets graphics.Rect, minimizedHomeBounds graphics.Rect, extras os.Bundle) error
	OnTasksAppeared(ctx context.Context, app []view.RemoteAnimationTarget) error
}

type recentsAnimationRunnerStubWrapper struct {
	impl       IRecentsAnimationRunnerServer
	stubBinder *binder.StubBinder
}

func (w *recentsAnimationRunnerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *recentsAnimationRunnerStubWrapper) OnAnimationCanceled(
	ctx context.Context,
	taskIds []int32,
	taskSnapshots []view.WindowManagerTaskSnapshot,
) error {
	return w.impl.OnAnimationCanceled(ctx, taskIds, taskSnapshots)
}

func (w *recentsAnimationRunnerStubWrapper) OnAnimationStart(
	ctx context.Context,
	controller IRecentsAnimationController,
	apps []view.RemoteAnimationTarget,
	wallpapers []view.RemoteAnimationTarget,
	homeContentInsets graphics.Rect,
	minimizedHomeBounds graphics.Rect,
	extras os.Bundle,
) error {
	return w.impl.OnAnimationStart(ctx, controller, apps, wallpapers, homeContentInsets, minimizedHomeBounds, extras)
}

func (w *recentsAnimationRunnerStubWrapper) OnTasksAppeared(
	ctx context.Context,
	app []view.RemoteAnimationTarget,
) error {
	return w.impl.OnTasksAppeared(ctx, app)
}

var _ IRecentsAnimationRunner = (*recentsAnimationRunnerStubWrapper)(nil)

// NewRecentsAnimationRunnerStub creates a server-side IRecentsAnimationRunner wrapping the given
// server implementation. The returned value satisfies IRecentsAnimationRunner
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewRecentsAnimationRunnerStub(
	impl IRecentsAnimationRunnerServer,
) IRecentsAnimationRunner {
	wrapper := &recentsAnimationRunnerStubWrapper{impl: impl}
	stub := &RecentsAnimationRunnerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
