package time

import (
	res "github.com/xaionaro-go/binder/android/content/res"
	neuralnetworks "github.com/xaionaro-go/binder/android/hardware/neuralnetworks"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TimeZoneCapabilitiesAndConfig struct {
	Capabilities  *neuralnetworks.Capabilities
	Configuration *res.Configuration
}

var _ parcel.Parcelable = (*TimeZoneCapabilitiesAndConfig)(nil)

func (s *TimeZoneCapabilitiesAndConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt32(0) // null DetectorStatus
	if s.Capabilities != nil {
		p.WriteInt32(1)
		if _err := s.Capabilities.MarshalParcel(p); _err != nil {
			return _err
		}
	} else {
		p.WriteInt32(0)
	}
	if s.Configuration != nil {
		p.WriteInt32(1)
		if _err := s.Configuration.MarshalParcel(p); _err != nil {
			return _err
		}
	} else {
		p.WriteInt32(0)
	}
	return nil
}

func (s *TimeZoneCapabilitiesAndConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	{
		_opaqueFlag, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueFlag != 0 {
			return nil // non-null DetectorStatus: cannot skip unknown-size typed object
		}
	}
	{
		_flag, _err := p.ReadInt32()
		if _err != nil {
			return _err
		}
		if _flag != 0 {
			s.Capabilities = &neuralnetworks.Capabilities{}
			if _err = s.Capabilities.UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}
	{
		_flag, _err := p.ReadInt32()
		if _err != nil {
			return _err
		}
		if _flag != 0 {
			s.Configuration = &res.Configuration{}
			if _err = s.Configuration.UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}
	return nil
}
