// Code generated by genparcelgo. DO NOT EDIT.

package inputmethod

import (
	"github.com/xaionaro-go/binder/parcel"
)

type TextAttribute struct {
	// TextConversionSuggestions: opaque type — not yet supported
	// Extras: opaque type — not yet supported
}

var _ parcel.Parcelable = (*TextAttribute)(nil)

func (s *TextAttribute) MarshalParcel(
	p *parcel.Parcel,
) error {
	return nil
}

func (s *TextAttribute) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
