package audio

import (
	audioCodecCapabilities "github.com/xaionaro-go/binder/android/hardware/bluetooth/audio/CodecCapabilities"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type CodecCapabilities struct {
	CodecType    CodecType
	Capabilities audioCodecCapabilities.Capabilities
}

var _ parcel.Parcelable = (*CodecCapabilities)(nil)

func (s *CodecCapabilities) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(int32(s.CodecType))
	if _err := s.Capabilities.MarshalParcel(p); _err != nil {
		return _err
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *CodecCapabilities) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	_codecTypeRaw, _err := p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.CodecType = CodecType(_codecTypeRaw)

	if _err = s.Capabilities.UnmarshalParcel(p); _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
