package core

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type IModuleSupportedPlaybackRateFactors struct {
	MinSpeed float32
	MaxSpeed float32
	MinPitch float32
	MaxPitch float32
}

var _ parcel.Parcelable = (*IModuleSupportedPlaybackRateFactors)(nil)

func (s *IModuleSupportedPlaybackRateFactors) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.MinSpeed)
	p.WriteFloat32(s.MaxSpeed)
	p.WriteFloat32(s.MinPitch)
	p.WriteFloat32(s.MaxPitch)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *IModuleSupportedPlaybackRateFactors) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.MinSpeed, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.MaxSpeed, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.MinPitch, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.MaxPitch, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
