// Code generated by genparcelgo. DO NOT EDIT.

package timezone

import (
	"github.com/xaionaro-go/binder/parcel"
)

type TimeZoneProviderSuggestion struct {
	ElapsedRealtimeMillis int64
	// TimeZoneIds: opaque type — not yet supported
}

var _ parcel.Parcelable = (*TimeZoneProviderSuggestion)(nil)

func (s *TimeZoneProviderSuggestion) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteInt64(s.ElapsedRealtimeMillis)
	return nil
}

func (s *TimeZoneProviderSuggestion) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.ElapsedRealtimeMillis, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
