package vehicle

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GetValueResult struct {
	RequestId int64
	Status    StatusCode
	Prop      VehiclePropValue
}

var _ parcel.Parcelable = (*GetValueResult)(nil)

func (s *GetValueResult) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt64(s.RequestId)
	p.WriteInt32(int32(s.Status))
	if _err := s.Prop.MarshalParcel(p); _err != nil {
		return _err
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *GetValueResult) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.RequestId, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}

	_statusRaw, _err := p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.Status = StatusCode(_statusRaw)

	if _err = s.Prop.UnmarshalParcel(p); _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
