package vehicle

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SetValueResults struct {
	Payloads       []SetValueResult
	SharedMemoryFd int32
}

var _ parcel.Parcelable = (*SetValueResults)(nil)

func (s *SetValueResults) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if s.Payloads == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.Payloads)))
		for _, _item := range s.Payloads {
			p.WriteInt32(1)
			if _err := _item.MarshalParcel(p); _err != nil {
				return _err
			}
		}
	}
	p.WriteParcelFileDescriptor(s.SharedMemoryFd)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *SetValueResults) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.Payloads = make([]SetValueResult, _count0)
		for _i := int32(0); _i < _count0; _i++ {
			if _, _err = p.ReadInt32(); _err != nil {
				return _err
			}
			if _err = s.Payloads[_i].UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.SharedMemoryFd, _err = p.ReadParcelFileDescriptor()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
