package network

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type CellInfoCdma struct {
	CellIdentityCdma   CellIdentityCdma
	SignalStrengthCdma CdmaSignalStrength
	SignalStrengthEvdo EvdoSignalStrength
}

var _ parcel.Parcelable = (*CellInfoCdma)(nil)

func (s *CellInfoCdma) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if _err := s.CellIdentityCdma.MarshalParcel(p); _err != nil {
		return _err
	}
	if _err := s.SignalStrengthCdma.MarshalParcel(p); _err != nil {
		return _err
	}
	if _err := s.SignalStrengthEvdo.MarshalParcel(p); _err != nil {
		return _err
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *CellInfoCdma) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _err = s.CellIdentityCdma.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _err = s.SignalStrengthCdma.UnmarshalParcel(p); _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	if _err = s.SignalStrengthEvdo.UnmarshalParcel(p); _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
