package neuralnetworks

import (
	"fmt"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const (
	OperandExtraParamsTagChannelQuant int32 = 0
	OperandExtraParamsTagExtension    int32 = 1
)

type OperandExtraParams struct {
	Tag          int32
	ChannelQuant SymmPerChannelQuantParams
	Extension    []byte
}

var _ parcel.Parcelable = (*OperandExtraParams)(nil)

func (u *OperandExtraParams) GetChannelQuant() (SymmPerChannelQuantParams, bool) {
	if u.Tag != OperandExtraParamsTagChannelQuant {
		var _zero SymmPerChannelQuantParams
		return _zero, false
	}
	return u.ChannelQuant, true
}

func (u *OperandExtraParams) SetChannelQuant(
	v SymmPerChannelQuantParams,
) {
	u.Tag = OperandExtraParamsTagChannelQuant
	u.ChannelQuant = v
}

func (u *OperandExtraParams) GetExtension() ([]byte, bool) {
	if u.Tag != OperandExtraParamsTagExtension {
		var _zero []byte
		return _zero, false
	}
	return u.Extension, true
}

func (u *OperandExtraParams) SetExtension(
	v []byte,
) {
	u.Tag = OperandExtraParamsTagExtension
	u.Extension = v
}

func (u *OperandExtraParams) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(u.Tag)

	switch u.Tag {
	case OperandExtraParamsTagChannelQuant:
		if _err := u.ChannelQuant.MarshalParcel(p); _err != nil {
			return _err
		}
	case OperandExtraParamsTagExtension:
		if u.Extension == nil {
			p.WriteInt32(-1)
		} else {
			p.WriteInt32(int32(len(u.Extension)))
			for _, _item := range u.Extension {
				p.WritePaddedByte(_item)
			}
		}
	default:
		return fmt.Errorf("unknown union tag %d for OperandExtraParams", u.Tag)
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (u *OperandExtraParams) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	u.Tag, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	switch u.Tag {
	case OperandExtraParamsTagChannelQuant:
		if _err = u.ChannelQuant.UnmarshalParcel(p); _err != nil {
			return _err
		}
	case OperandExtraParamsTagExtension:

		var _count0 int32
		_count0, _err = p.ReadInt32()
		if _err != nil {
			return _err
		}
		if _count0 >= 0 {
			u.Extension = make([]byte, _count0)
			for _i := int32(0); _i < _count0; _i++ {
				u.Extension[_i], _err = p.ReadPaddedByte()
				if _err != nil {
					return _err
				}
			}
		}
	default:
		return fmt.Errorf("unknown union tag %d for OperandExtraParams", u.Tag)
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
