package neuralnetworks

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type PerformanceInfo struct {
	ExecTime   float32
	PowerUsage float32
}

var _ parcel.Parcelable = (*PerformanceInfo)(nil)

func (s *PerformanceInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.ExecTime)
	p.WriteFloat32(s.PowerUsage)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *PerformanceInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.ExecTime, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.PowerUsage, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
