package ondeviceintelligence

import (
	"context"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIResponseCallback = "android.app.ondeviceintelligence.IResponseCallback"

const (
	TransactionIResponseCallbackOnSuccess            = binder.FirstCallTransaction + 0
	TransactionIResponseCallbackOnFailure            = binder.FirstCallTransaction + 1
	TransactionIResponseCallbackOnDataAugmentRequest = binder.FirstCallTransaction + 2
)

type IResponseCallback interface {
	AsBinder() binder.IBinder
	OnSuccess(ctx context.Context, resultBundle interface{}) error
	OnFailure(ctx context.Context, errorCode int32, errorMessage string, errorParams interface{}) error
	OnDataAugmentRequest(ctx context.Context, processedContent interface{}, responseCallback interface{}) error
}

type ResponseCallbackProxy struct {
	remote binder.IBinder
}

func NewResponseCallbackProxy(
	remote binder.IBinder,
) *ResponseCallbackProxy {
	return &ResponseCallbackProxy{remote: remote}
}

func (p *ResponseCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IResponseCallback = (*ResponseCallbackProxy)(nil)

func (p *ResponseCallbackProxy) OnSuccess(
	ctx context.Context,
	resultBundle interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIResponseCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIResponseCallback, "onSuccess")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ResponseCallbackProxy) OnFailure(
	ctx context.Context,
	errorCode int32,
	errorMessage string,
	errorParams interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIResponseCallback)
	_data.WriteInt32(errorCode)
	_data.WriteString16(errorMessage)

	_code, _err := p.remote.ResolveCode(DescriptorIResponseCallback, "onFailure")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ResponseCallbackProxy) OnDataAugmentRequest(
	ctx context.Context,
	processedContent interface{},
	responseCallback interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIResponseCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIResponseCallback, "onDataAugmentRequest")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
