package debug

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAdbCallback = "android.debug.IAdbCallback"

const (
	TransactionIAdbCallbackOnDebuggingChanged = binder.FirstCallTransaction + 0
)

type IAdbCallback interface {
	AsBinder() binder.IBinder
	OnDebuggingChanged(ctx context.Context, enabled bool, type_ AdbTransportType) error
}

type AdbCallbackProxy struct {
	remote binder.IBinder
}

func NewAdbCallbackProxy(
	remote binder.IBinder,
) *AdbCallbackProxy {
	return &AdbCallbackProxy{remote: remote}
}

func (p *AdbCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAdbCallback = (*AdbCallbackProxy)(nil)

func (p *AdbCallbackProxy) OnDebuggingChanged(
	ctx context.Context,
	enabled bool,
	type_ AdbTransportType,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAdbCallback)
	_data.WriteBool(enabled)
	_data.WritePaddedByte(byte(type_))

	_code, _err := p.remote.ResolveCode(DescriptorIAdbCallback, "onDebuggingChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
