package virtual

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIVirtualDeviceSoundEffectListener = "android.companion.virtual.IVirtualDeviceSoundEffectListener"

const (
	TransactionIVirtualDeviceSoundEffectListenerOnPlaySoundEffect = binder.FirstCallTransaction + 0
)

const (
	MethodIVirtualDeviceSoundEffectListenerOnPlaySoundEffect = "onPlaySoundEffect"
)

type IVirtualDeviceSoundEffectListener interface {
	AsBinder() binder.IBinder
	OnPlaySoundEffect(ctx context.Context, effectType int32) error
}

type VirtualDeviceSoundEffectListenerProxy struct {
	Remote binder.IBinder
}

func NewVirtualDeviceSoundEffectListenerProxy(
	remote binder.IBinder,
) *VirtualDeviceSoundEffectListenerProxy {
	return &VirtualDeviceSoundEffectListenerProxy{Remote: remote}
}

func (p *VirtualDeviceSoundEffectListenerProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IVirtualDeviceSoundEffectListener = (*VirtualDeviceSoundEffectListenerProxy)(nil)

func (p *VirtualDeviceSoundEffectListenerProxy) OnPlaySoundEffect(
	ctx context.Context,
	effectType int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIVirtualDeviceSoundEffectListener)
	_data.WriteInt32(effectType)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIVirtualDeviceSoundEffectListener, MethodIVirtualDeviceSoundEffectListenerOnPlaySoundEffect)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIVirtualDeviceSoundEffectListener, MethodIVirtualDeviceSoundEffectListenerOnPlaySoundEffect, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// VirtualDeviceSoundEffectListenerStub dispatches incoming binder transactions
// to a typed IVirtualDeviceSoundEffectListener implementation.
type VirtualDeviceSoundEffectListenerStub struct {
	Impl      IVirtualDeviceSoundEffectListener
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*VirtualDeviceSoundEffectListenerStub)(nil)

func (s *VirtualDeviceSoundEffectListenerStub) Descriptor() string {
	return DescriptorIVirtualDeviceSoundEffectListener
}

func (s *VirtualDeviceSoundEffectListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIVirtualDeviceSoundEffectListenerOnPlaySoundEffect:
		_arg_effectType, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPlaySoundEffect(ctx, _arg_effectType)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IVirtualDeviceSoundEffectListenerServer is the server-side interface that user implementations
// provide to NewVirtualDeviceSoundEffectListenerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IVirtualDeviceSoundEffectListenerServer interface {
	OnPlaySoundEffect(ctx context.Context, effectType int32) error
}

type virtualDeviceSoundEffectListenerStubWrapper struct {
	impl       IVirtualDeviceSoundEffectListenerServer
	stubBinder *binder.StubBinder
}

func (w *virtualDeviceSoundEffectListenerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *virtualDeviceSoundEffectListenerStubWrapper) OnPlaySoundEffect(
	ctx context.Context,
	effectType int32,
) error {
	return w.impl.OnPlaySoundEffect(ctx, effectType)
}

var _ IVirtualDeviceSoundEffectListener = (*virtualDeviceSoundEffectListenerStubWrapper)(nil)

// NewVirtualDeviceSoundEffectListenerStub creates a server-side IVirtualDeviceSoundEffectListener wrapping the given
// server implementation. The returned value satisfies IVirtualDeviceSoundEffectListener
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewVirtualDeviceSoundEffectListenerStub(
	impl IVirtualDeviceSoundEffectListenerServer,
) IVirtualDeviceSoundEffectListener {
	wrapper := &virtualDeviceSoundEffectListenerStubWrapper{impl: impl}
	stub := &VirtualDeviceSoundEffectListenerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
