package common

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type AudioHalCapCriterionType struct {
	Name        string
	IsInclusive bool
	Values      []string
}

var _ parcel.Parcelable = (*AudioHalCapCriterionType)(nil)

func (s *AudioHalCapCriterionType) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteString16(s.Name)
	p.WriteBool(s.IsInclusive)
	if s.Values == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.Values)))
		for _, _item := range s.Values {
			p.WriteString16(_item)
		}
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *AudioHalCapCriterionType) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.Name, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	s.IsInclusive, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.Values = make([]string, _count0)
		for _i := int32(0); _i < _count0; _i++ {
			s.Values[_i], _err = p.ReadString16()
			if _err != nil {
				return _err
			}
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
