package eraser

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type ClassificationConfig struct {
	Classifications     []Classification
	ConfidenceThreshold float32
	GainFactor          float32
}

var _ parcel.Parcelable = (*ClassificationConfig)(nil)

func (s *ClassificationConfig) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if s.Classifications == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.Classifications)))
		for _, _item := range s.Classifications {
			if _err := _item.MarshalParcel(p); _err != nil {
				return _err
			}
		}
	}
	p.WriteFloat32(s.ConfidenceThreshold)
	p.WriteFloat32(s.GainFactor)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *ClassificationConfig) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.Classifications = make([]Classification, _count0)
		for _i := int32(0); _i < _count0; _i++ {
			if _err = s.Classifications[_i].UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}

	s.ConfidenceThreshold, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	s.GainFactor, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
