package audiocontrol

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type AudioZoneContext struct {
	AudioContextInfos []AudioZoneContextInfo
}

var _ parcel.Parcelable = (*AudioZoneContext)(nil)

func (s *AudioZoneContext) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if s.AudioContextInfos == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.AudioContextInfos)))
		for _, _item := range s.AudioContextInfos {
			if _err := _item.MarshalParcel(p); _err != nil {
				return _err
			}
		}
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *AudioZoneContext) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.AudioContextInfos = make([]AudioZoneContextInfo, _count0)
		for _i := int32(0); _i < _count0; _i++ {
			if _err = s.AudioContextInfos[_i].UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
