package biometrics

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBiometricSysuiReceiver = "android.hardware.biometrics.IBiometricSysuiReceiver"

const (
	TransactionIBiometricSysuiReceiverOnDialogDismissed         = binder.FirstCallTransaction + 0
	TransactionIBiometricSysuiReceiverOnTryAgainPressed         = binder.FirstCallTransaction + 1
	TransactionIBiometricSysuiReceiverOnDeviceCredentialPressed = binder.FirstCallTransaction + 2
	TransactionIBiometricSysuiReceiverOnSystemEvent             = binder.FirstCallTransaction + 3
	TransactionIBiometricSysuiReceiverOnDialogAnimatedIn        = binder.FirstCallTransaction + 4
	TransactionIBiometricSysuiReceiverOnStartFingerprintNow     = binder.FirstCallTransaction + 5
)

type IBiometricSysuiReceiver interface {
	AsBinder() binder.IBinder
	OnDialogDismissed(ctx context.Context, reason int32, credentialAttestation []byte) error
	OnTryAgainPressed(ctx context.Context) error
	OnDeviceCredentialPressed(ctx context.Context) error
	OnSystemEvent(ctx context.Context, event int32) error
	OnDialogAnimatedIn(ctx context.Context, startFingerprintNow bool) error
	OnStartFingerprintNow(ctx context.Context) error
}

type BiometricSysuiReceiverProxy struct {
	remote binder.IBinder
}

func NewBiometricSysuiReceiverProxy(
	remote binder.IBinder,
) *BiometricSysuiReceiverProxy {
	return &BiometricSysuiReceiverProxy{remote: remote}
}

func (p *BiometricSysuiReceiverProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBiometricSysuiReceiver = (*BiometricSysuiReceiverProxy)(nil)

func (p *BiometricSysuiReceiverProxy) OnDialogDismissed(
	ctx context.Context,
	reason int32,
	credentialAttestation []byte,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)
	_data.WriteInt32(reason)
	if credentialAttestation == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(credentialAttestation)))
		for _, _item := range credentialAttestation {
			_data.WritePaddedByte(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onDialogDismissed")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnDialogDismissed
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BiometricSysuiReceiverProxy) OnTryAgainPressed(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onTryAgainPressed")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnTryAgainPressed
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BiometricSysuiReceiverProxy) OnDeviceCredentialPressed(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onDeviceCredentialPressed")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnDeviceCredentialPressed
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BiometricSysuiReceiverProxy) OnSystemEvent(
	ctx context.Context,
	event int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)
	_data.WriteInt32(event)

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onSystemEvent")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnSystemEvent
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BiometricSysuiReceiverProxy) OnDialogAnimatedIn(
	ctx context.Context,
	startFingerprintNow bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)
	_data.WriteBool(startFingerprintNow)

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onDialogAnimatedIn")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnDialogAnimatedIn
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BiometricSysuiReceiverProxy) OnStartFingerprintNow(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBiometricSysuiReceiver)

	_code, _err := p.remote.ResolveCode(DescriptorIBiometricSysuiReceiver, "onStartFingerprintNow")
	if _err != nil {
		_code = TransactionIBiometricSysuiReceiverOnStartFingerprintNow
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// BiometricSysuiReceiverStub dispatches incoming binder transactions
// to a typed IBiometricSysuiReceiver implementation.
type BiometricSysuiReceiverStub struct {
	Impl IBiometricSysuiReceiver
}

var _ binder.TransactionReceiver = (*BiometricSysuiReceiverStub)(nil)

func (s *BiometricSysuiReceiverStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionIBiometricSysuiReceiverOnDialogDismissed:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_reason, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_credentialAttestation []byte
		_ = _arg_credentialAttestation
		_err = s.Impl.OnDialogDismissed(ctx, _arg_reason, _arg_credentialAttestation)
		_ = _err
		return nil, nil
	case TransactionIBiometricSysuiReceiverOnTryAgainPressed:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnTryAgainPressed(ctx)
		_ = _err
		return nil, nil
	case TransactionIBiometricSysuiReceiverOnDeviceCredentialPressed:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnDeviceCredentialPressed(ctx)
		_ = _err
		return nil, nil
	case TransactionIBiometricSysuiReceiverOnSystemEvent:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_event, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnSystemEvent(ctx, _arg_event)
		_ = _err
		return nil, nil
	case TransactionIBiometricSysuiReceiverOnDialogAnimatedIn:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_startFingerprintNow, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnDialogAnimatedIn(ctx, _arg_startFingerprintNow)
		_ = _err
		return nil, nil
	case TransactionIBiometricSysuiReceiverOnStartFingerprintNow:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_err := s.Impl.OnStartFingerprintNow(ctx)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IBiometricSysuiReceiverServer is the server-side interface that user implementations
// provide to NewBiometricSysuiReceiverStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IBiometricSysuiReceiverServer interface {
	OnDialogDismissed(ctx context.Context, reason int32, credentialAttestation []byte) error
	OnTryAgainPressed(ctx context.Context) error
	OnDeviceCredentialPressed(ctx context.Context) error
	OnSystemEvent(ctx context.Context, event int32) error
	OnDialogAnimatedIn(ctx context.Context, startFingerprintNow bool) error
	OnStartFingerprintNow(ctx context.Context) error
}

type biometricSysuiReceiverStubWrapper struct {
	impl       IBiometricSysuiReceiverServer
	stubBinder *binder.StubBinder
}

func (w *biometricSysuiReceiverStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *biometricSysuiReceiverStubWrapper) OnDialogDismissed(
	ctx context.Context,
	reason int32,
	credentialAttestation []byte,
) error {
	return w.impl.OnDialogDismissed(ctx, reason, credentialAttestation)
}

func (w *biometricSysuiReceiverStubWrapper) OnTryAgainPressed(
	ctx context.Context,
) error {
	return w.impl.OnTryAgainPressed(ctx)
}

func (w *biometricSysuiReceiverStubWrapper) OnDeviceCredentialPressed(
	ctx context.Context,
) error {
	return w.impl.OnDeviceCredentialPressed(ctx)
}

func (w *biometricSysuiReceiverStubWrapper) OnSystemEvent(
	ctx context.Context,
	event int32,
) error {
	return w.impl.OnSystemEvent(ctx, event)
}

func (w *biometricSysuiReceiverStubWrapper) OnDialogAnimatedIn(
	ctx context.Context,
	startFingerprintNow bool,
) error {
	return w.impl.OnDialogAnimatedIn(ctx, startFingerprintNow)
}

func (w *biometricSysuiReceiverStubWrapper) OnStartFingerprintNow(
	ctx context.Context,
) error {
	return w.impl.OnStartFingerprintNow(ctx)
}

var _ IBiometricSysuiReceiver = (*biometricSysuiReceiverStubWrapper)(nil)

// NewBiometricSysuiReceiverStub creates a server-side IBiometricSysuiReceiver wrapping the given
// server implementation. The returned value satisfies IBiometricSysuiReceiver
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewBiometricSysuiReceiverStub(
	impl IBiometricSysuiReceiverServer,
) IBiometricSysuiReceiver {
	wrapper := &biometricSysuiReceiverStubWrapper{impl: impl}
	stub := &BiometricSysuiReceiverStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
