package display

import (
	"github.com/AndroidGoLab/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type BrightnessChangeEvent struct {
	Brightness                 float32
	TimeStamp                  int64
	PackageName                string
	UserId                     int32
	UniqueDisplayId            string
	BatteryLevel               float32
	PowerBrightnessFactor      float32
	NightMode                  bool
	ColorTemperature           int32
	ReduceBrightColors         bool
	ReduceBrightColorsStrength int32
	ReduceBrightColorsOffset   float32
	LastBrightness             float32
	IsDefaultBrightnessConfig  bool
	IsUserSetBrightness        bool
	ColorSampleDuration        int64
}

var _ parcel.Parcelable = (*BrightnessChangeEvent)(nil)

func (s *BrightnessChangeEvent) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteFloat32(s.Brightness)
	p.WriteInt64(s.TimeStamp)
	p.WriteString16(s.PackageName)
	p.WriteInt32(s.UserId)
	p.WriteString16(s.UniqueDisplayId)
	p.WriteInt32(-1) // null LuxValues
	p.WriteInt32(-1) // null LuxTimestamps
	p.WriteFloat32(s.BatteryLevel)
	p.WriteFloat32(s.PowerBrightnessFactor)
	p.WriteBool(s.NightMode)
	p.WriteInt32(s.ColorTemperature)
	p.WriteBool(s.ReduceBrightColors)
	p.WriteInt32(s.ReduceBrightColorsStrength)
	p.WriteFloat32(s.ReduceBrightColorsOffset)
	p.WriteFloat32(s.LastBrightness)
	p.WriteBool(s.IsDefaultBrightnessConfig)
	p.WriteBool(s.IsUserSetBrightness)
	p.WriteInt32(-1) // null ColorValueBuckets
	p.WriteInt64(s.ColorSampleDuration)
	return nil
}

func (s *BrightnessChangeEvent) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Brightness, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}
	s.TimeStamp, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	s.UserId, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.UniqueDisplayId, _err = p.ReadString16()
	if _err != nil {
		return _err
	}
	return nil // opaque LuxValues: cannot skip without known wire format
}
