package: android.app.servertransaction
type: ActivityConfigurationChangeItem
fields:
    - name: Dest
      type: opaque
    - name: Configuration
      type: opaque
    - name: ActivityWindowInfo
      type: opaque
