package sensors

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type EventEventPayloadHeartRate struct {
	Bpm    float32
	Status SensorStatus
}

var _ parcel.Parcelable = (*EventEventPayloadHeartRate)(nil)

func (s *EventEventPayloadHeartRate) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.Bpm)
	p.WritePaddedByte(byte(s.Status))

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *EventEventPayloadHeartRate) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Bpm, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	_statusRaw, _err := p.ReadPaddedByte()
	if _err != nil {
		return _err
	}
	s.Status = SensorStatus(_statusRaw)

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
