package sensors

import (
	"github.com/xaionaro-go/binder/tools/pkg/testutil"
	"testing"
)

// Code generated by aospgen. DO NOT EDIT.

func TestSmoke_SensorsProxy(t *testing.T) {
	mock := testutil.NewMockBinder()
	proxy := NewSensorsProxy(mock)
	result := testutil.SmokeTestAllMethods(t, proxy)
	t.Logf("SensorsProxy: %d/%d passed, %d panicked, %d failed",
		result.Passed, result.Total, result.Panicked, result.Failed)
}

func TestSmoke_SensorsCallbackProxy(t *testing.T) {
	mock := testutil.NewMockBinder()
	proxy := NewSensorsCallbackProxy(mock)
	result := testutil.SmokeTestAllMethods(t, proxy)
	t.Logf("SensorsCallbackProxy: %d/%d passed, %d panicked, %d failed",
		result.Passed, result.Total, result.Panicked, result.Failed)
}
