package wifi

import (
	common "github.com/xaionaro-go/binder/android/hardware/wifi/common"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type NanPublishRequest struct {
	BaseConfigs                NanDiscoveryCommonConfig
	PublishType                NanPublishType
	TxType                     NanTxType
	AutoAcceptDataPathRequests bool
	PairingConfig              NanPairingConfig
	IdentityKey                []byte
	VendorData                 []common.OuiKeyedData
	RangingResultsRequired     bool
}

var _ parcel.Parcelable = (*NanPublishRequest)(nil)

func (s *NanPublishRequest) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	if _err := s.BaseConfigs.MarshalParcel(p); _err != nil {
		return _err
	}
	p.WriteInt32(int32(s.PublishType))
	p.WriteInt32(int32(s.TxType))
	p.WriteBool(s.AutoAcceptDataPathRequests)
	if _err := s.PairingConfig.MarshalParcel(p); _err != nil {
		return _err
	}
	if s.IdentityKey == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.IdentityKey)))
		for _, _item := range s.IdentityKey {
			p.WritePaddedByte(_item)
		}
	}
	if s.VendorData == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.VendorData)))
		for _, _item := range s.VendorData {
			if _err := _item.MarshalParcel(p); _err != nil {
				return _err
			}
		}
	}
	p.WriteBool(s.RangingResultsRequired)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *NanPublishRequest) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if _err = s.BaseConfigs.UnmarshalParcel(p); _err != nil {
		return _err
	}

	_publishTypeRaw, _err := p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.PublishType = NanPublishType(_publishTypeRaw)

	_txTypeRaw, _err := p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.TxType = NanTxType(_txTypeRaw)

	s.AutoAcceptDataPathRequests, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	if _err = s.PairingConfig.UnmarshalParcel(p); _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.IdentityKey = make([]byte, _count0)
		for _i := int32(0); _i < _count0; _i++ {
			s.IdentityKey[_i], _err = p.ReadPaddedByte()
			if _err != nil {
				return _err
			}
		}
	}

	var _count1 int32
	_count1, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count1 >= 0 {
		s.VendorData = make([]common.OuiKeyedData, _count1)
		for _i := int32(0); _i < _count1; _i++ {
			if _err = s.VendorData[_i].UnmarshalParcel(p); _err != nil {
				return _err
			}
		}
	}

	s.RangingResultsRequired, _err = p.ReadBool()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
