package projection

import (
	"context"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIMediaProjectionCallback = "android.media.projection.IMediaProjectionCallback"

const (
	TransactionIMediaProjectionCallbackOnStop                             = binder.FirstCallTransaction + 0
	TransactionIMediaProjectionCallbackOnCapturedContentResize            = binder.FirstCallTransaction + 1
	TransactionIMediaProjectionCallbackOnCapturedContentVisibilityChanged = binder.FirstCallTransaction + 2
)

type IMediaProjectionCallback interface {
	AsBinder() binder.IBinder
	OnStop(ctx context.Context) error
	OnCapturedContentResize(ctx context.Context, width int32, height int32) error
	OnCapturedContentVisibilityChanged(ctx context.Context, isVisible bool) error
}

type MediaProjectionCallbackProxy struct {
	remote binder.IBinder
}

func NewMediaProjectionCallbackProxy(
	remote binder.IBinder,
) *MediaProjectionCallbackProxy {
	return &MediaProjectionCallbackProxy{remote: remote}
}

func (p *MediaProjectionCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IMediaProjectionCallback = (*MediaProjectionCallbackProxy)(nil)

func (p *MediaProjectionCallbackProxy) OnStop(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onStop")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *MediaProjectionCallbackProxy) OnCapturedContentResize(
	ctx context.Context,
	width int32,
	height int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)
	_data.WriteInt32(width)
	_data.WriteInt32(height)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onCapturedContentResize")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *MediaProjectionCallbackProxy) OnCapturedContentVisibilityChanged(
	ctx context.Context,
	isVisible bool,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIMediaProjectionCallback)
	_data.WriteBool(isVisible)

	_code, _err := p.remote.ResolveCode(DescriptorIMediaProjectionCallback, "onCapturedContentVisibilityChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
