package common

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type FRect struct {
	Left   float32
	Top    float32
	Right  float32
	Bottom float32
}

var _ parcel.Parcelable = (*FRect)(nil)

func (s *FRect) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteFloat32(s.Left)
	p.WriteFloat32(s.Top)
	p.WriteFloat32(s.Right)
	p.WriteFloat32(s.Bottom)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *FRect) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Left, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Top, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Right, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Bottom, _err = p.ReadFloat32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
