package pm

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIOnAppsChangedListener = "android.content.pm.IOnAppsChangedListener"

const (
	TransactionIOnAppsChangedListenerOnPackageRemoved                = binder.FirstCallTransaction + 0
	TransactionIOnAppsChangedListenerOnPackageAdded                  = binder.FirstCallTransaction + 1
	TransactionIOnAppsChangedListenerOnPackageChanged                = binder.FirstCallTransaction + 2
	TransactionIOnAppsChangedListenerOnPackagesAvailable             = binder.FirstCallTransaction + 3
	TransactionIOnAppsChangedListenerOnPackagesUnavailable           = binder.FirstCallTransaction + 4
	TransactionIOnAppsChangedListenerOnPackagesSuspended             = binder.FirstCallTransaction + 5
	TransactionIOnAppsChangedListenerOnPackagesUnsuspended           = binder.FirstCallTransaction + 6
	TransactionIOnAppsChangedListenerOnShortcutChanged               = binder.FirstCallTransaction + 7
	TransactionIOnAppsChangedListenerOnPackageLoadingProgressChanged = binder.FirstCallTransaction + 8
)

const (
	MethodIOnAppsChangedListenerOnPackageRemoved                = "onPackageRemoved"
	MethodIOnAppsChangedListenerOnPackageAdded                  = "onPackageAdded"
	MethodIOnAppsChangedListenerOnPackageChanged                = "onPackageChanged"
	MethodIOnAppsChangedListenerOnPackagesAvailable             = "onPackagesAvailable"
	MethodIOnAppsChangedListenerOnPackagesUnavailable           = "onPackagesUnavailable"
	MethodIOnAppsChangedListenerOnPackagesSuspended             = "onPackagesSuspended"
	MethodIOnAppsChangedListenerOnPackagesUnsuspended           = "onPackagesUnsuspended"
	MethodIOnAppsChangedListenerOnShortcutChanged               = "onShortcutChanged"
	MethodIOnAppsChangedListenerOnPackageLoadingProgressChanged = "onPackageLoadingProgressChanged"
)

type IOnAppsChangedListener interface {
	AsBinder() binder.IBinder
	OnPackageRemoved(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackageAdded(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackageChanged(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackagesAvailable(ctx context.Context, user os.UserHandle, packageNames []string, replacing bool) error
	OnPackagesUnavailable(ctx context.Context, user os.UserHandle, packageNames []string, replacing bool) error
	OnPackagesSuspended(ctx context.Context, user os.UserHandle, packageNames []string, launcherExtras os.Bundle) error
	OnPackagesUnsuspended(ctx context.Context, user os.UserHandle, packageNames []string) error
	OnShortcutChanged(ctx context.Context, user os.UserHandle, packageName string, shortcuts ParceledListSlice) error
	OnPackageLoadingProgressChanged(ctx context.Context, user os.UserHandle, packageName string, progress float32) error
}

type OnAppsChangedListenerProxy struct {
	Remote binder.IBinder
}

func NewOnAppsChangedListenerProxy(
	remote binder.IBinder,
) *OnAppsChangedListenerProxy {
	return &OnAppsChangedListenerProxy{Remote: remote}
}

func (p *OnAppsChangedListenerProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IOnAppsChangedListener = (*OnAppsChangedListenerProxy)(nil)

func (p *OnAppsChangedListenerProxy) OnPackageRemoved(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(packageName)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageRemoved)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageRemoved, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackageAdded(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(packageName)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageAdded)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageAdded, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackageChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(packageName)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageChanged)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageChanged, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackagesAvailable(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	replacing bool,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	if packageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packageNames)))
		for _, _item := range packageNames {
			_data.WriteString16(_item)
		}
	}
	_data.WriteBool(replacing)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesAvailable)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesAvailable, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackagesUnavailable(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	replacing bool,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	if packageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packageNames)))
		for _, _item := range packageNames {
			_data.WriteString16(_item)
		}
	}
	_data.WriteBool(replacing)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesUnavailable)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesUnavailable, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackagesSuspended(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	launcherExtras os.Bundle,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	if packageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packageNames)))
		for _, _item := range packageNames {
			_data.WriteString16(_item)
		}
	}
	_data.WriteInt32(1)
	if _err := launcherExtras.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesSuspended)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesSuspended, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackagesUnsuspended(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	if packageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packageNames)))
		for _, _item := range packageNames {
			_data.WriteString16(_item)
		}
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesUnsuspended)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackagesUnsuspended, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnShortcutChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
	shortcuts ParceledListSlice,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(packageName)
	_data.WriteInt32(1)
	if _err := shortcuts.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnShortcutChanged)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnShortcutChanged, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *OnAppsChangedListenerProxy) OnPackageLoadingProgressChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
	progress float32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIOnAppsChangedListener)
	_data.WriteInt32(1)
	if _err := user.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteString16(packageName)
	_data.WriteFloat32(progress)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageLoadingProgressChanged)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIOnAppsChangedListener, MethodIOnAppsChangedListenerOnPackageLoadingProgressChanged, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// OnAppsChangedListenerStub dispatches incoming binder transactions
// to a typed IOnAppsChangedListener implementation.
type OnAppsChangedListenerStub struct {
	Impl      IOnAppsChangedListener
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*OnAppsChangedListenerStub)(nil)

func (s *OnAppsChangedListenerStub) Descriptor() string {
	return DescriptorIOnAppsChangedListener
}

func (s *OnAppsChangedListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIOnAppsChangedListenerOnPackageRemoved:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackageRemoved(ctx, _arg_user, _arg_packageName)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackageAdded:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackageAdded(ctx, _arg_user, _arg_packageName)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackageChanged:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackageChanged(ctx, _arg_user, _arg_packageName)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackagesAvailable:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_packageNames []string
		{
			_count, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _count > 1000000 {
				return nil, fmt.Errorf("array count too large: %d", _count)
			}
			if _count >= 0 {
				_arg_packageNames = make([]string, _count)
				for _i := int32(0); _i < _count; _i++ {
					_arg_packageNames[_i], _err = _data.ReadString16()
					if _err != nil {
						return nil, _err
					}
				}
			}
		}
		_arg_replacing, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackagesAvailable(ctx, _arg_user, _arg_packageNames, _arg_replacing)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackagesUnavailable:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_packageNames []string
		{
			_count, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _count > 1000000 {
				return nil, fmt.Errorf("array count too large: %d", _count)
			}
			if _count >= 0 {
				_arg_packageNames = make([]string, _count)
				for _i := int32(0); _i < _count; _i++ {
					_arg_packageNames[_i], _err = _data.ReadString16()
					if _err != nil {
						return nil, _err
					}
				}
			}
		}
		_arg_replacing, _err := _data.ReadBool()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackagesUnavailable(ctx, _arg_user, _arg_packageNames, _arg_replacing)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackagesSuspended:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_packageNames []string
		{
			_count, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _count > 1000000 {
				return nil, fmt.Errorf("array count too large: %d", _count)
			}
			if _count >= 0 {
				_arg_packageNames = make([]string, _count)
				for _i := int32(0); _i < _count; _i++ {
					_arg_packageNames[_i], _err = _data.ReadString16()
					if _err != nil {
						return nil, _err
					}
				}
			}
		}
		var _arg_launcherExtras os.Bundle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_launcherExtras.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err := s.Impl.OnPackagesSuspended(ctx, _arg_user, _arg_packageNames, _arg_launcherExtras)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackagesUnsuspended:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		var _arg_packageNames []string
		{
			_count, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _count > 1000000 {
				return nil, fmt.Errorf("array count too large: %d", _count)
			}
			if _count >= 0 {
				_arg_packageNames = make([]string, _count)
				for _i := int32(0); _i < _count; _i++ {
					_arg_packageNames[_i], _err = _data.ReadString16()
					if _err != nil {
						return nil, _err
					}
				}
			}
		}
		_err := s.Impl.OnPackagesUnsuspended(ctx, _arg_user, _arg_packageNames)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnShortcutChanged:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_shortcuts ParceledListSlice
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_shortcuts.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_err = s.Impl.OnShortcutChanged(ctx, _arg_user, _arg_packageName, _arg_shortcuts)
		return nil, _err
	case TransactionIOnAppsChangedListenerOnPackageLoadingProgressChanged:
		var _arg_user os.UserHandle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_user.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_packageName, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_progress, _err := _data.ReadFloat32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnPackageLoadingProgressChanged(ctx, _arg_user, _arg_packageName, _arg_progress)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IOnAppsChangedListenerServer is the server-side interface that user implementations
// provide to NewOnAppsChangedListenerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IOnAppsChangedListenerServer interface {
	OnPackageRemoved(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackageAdded(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackageChanged(ctx context.Context, user os.UserHandle, packageName string) error
	OnPackagesAvailable(ctx context.Context, user os.UserHandle, packageNames []string, replacing bool) error
	OnPackagesUnavailable(ctx context.Context, user os.UserHandle, packageNames []string, replacing bool) error
	OnPackagesSuspended(ctx context.Context, user os.UserHandle, packageNames []string, launcherExtras os.Bundle) error
	OnPackagesUnsuspended(ctx context.Context, user os.UserHandle, packageNames []string) error
	OnShortcutChanged(ctx context.Context, user os.UserHandle, packageName string, shortcuts ParceledListSlice) error
	OnPackageLoadingProgressChanged(ctx context.Context, user os.UserHandle, packageName string, progress float32) error
}

type onAppsChangedListenerStubWrapper struct {
	impl       IOnAppsChangedListenerServer
	stubBinder *binder.StubBinder
}

func (w *onAppsChangedListenerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *onAppsChangedListenerStubWrapper) OnPackageRemoved(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	return w.impl.OnPackageRemoved(ctx, user, packageName)
}

func (w *onAppsChangedListenerStubWrapper) OnPackageAdded(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	return w.impl.OnPackageAdded(ctx, user, packageName)
}

func (w *onAppsChangedListenerStubWrapper) OnPackageChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
) error {
	return w.impl.OnPackageChanged(ctx, user, packageName)
}

func (w *onAppsChangedListenerStubWrapper) OnPackagesAvailable(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	replacing bool,
) error {
	return w.impl.OnPackagesAvailable(ctx, user, packageNames, replacing)
}

func (w *onAppsChangedListenerStubWrapper) OnPackagesUnavailable(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	replacing bool,
) error {
	return w.impl.OnPackagesUnavailable(ctx, user, packageNames, replacing)
}

func (w *onAppsChangedListenerStubWrapper) OnPackagesSuspended(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
	launcherExtras os.Bundle,
) error {
	return w.impl.OnPackagesSuspended(ctx, user, packageNames, launcherExtras)
}

func (w *onAppsChangedListenerStubWrapper) OnPackagesUnsuspended(
	ctx context.Context,
	user os.UserHandle,
	packageNames []string,
) error {
	return w.impl.OnPackagesUnsuspended(ctx, user, packageNames)
}

func (w *onAppsChangedListenerStubWrapper) OnShortcutChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
	shortcuts ParceledListSlice,
) error {
	return w.impl.OnShortcutChanged(ctx, user, packageName, shortcuts)
}

func (w *onAppsChangedListenerStubWrapper) OnPackageLoadingProgressChanged(
	ctx context.Context,
	user os.UserHandle,
	packageName string,
	progress float32,
) error {
	return w.impl.OnPackageLoadingProgressChanged(ctx, user, packageName, progress)
}

var _ IOnAppsChangedListener = (*onAppsChangedListenerStubWrapper)(nil)

// NewOnAppsChangedListenerStub creates a server-side IOnAppsChangedListener wrapping the given
// server implementation. The returned value satisfies IOnAppsChangedListener
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewOnAppsChangedListenerStub(
	impl IOnAppsChangedListenerServer,
) IOnAppsChangedListener {
	wrapper := &onAppsChangedListenerStubWrapper{impl: impl}
	stub := &OnAppsChangedListenerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
