package pm

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIShortcutChangeCallback = "android.content.pm.IShortcutChangeCallback"

const (
	TransactionIShortcutChangeCallbackOnShortcutsAddedOrUpdated = binder.FirstCallTransaction + 0
	TransactionIShortcutChangeCallbackOnShortcutsRemoved        = binder.FirstCallTransaction + 1
)

type IShortcutChangeCallback interface {
	AsBinder() binder.IBinder
	OnShortcutsAddedOrUpdated(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
	OnShortcutsRemoved(ctx context.Context, packageName string, shortcuts []ShortcutInfo, user interface{}) error
}

type ShortcutChangeCallbackProxy struct {
	remote binder.IBinder
}

func NewShortcutChangeCallbackProxy(
	remote binder.IBinder,
) *ShortcutChangeCallbackProxy {
	return &ShortcutChangeCallbackProxy{remote: remote}
}

func (p *ShortcutChangeCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IShortcutChangeCallback = (*ShortcutChangeCallbackProxy)(nil)

func (p *ShortcutChangeCallbackProxy) OnShortcutsAddedOrUpdated(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIShortcutChangeCallback)
	_data.WriteString16(packageName)
	if shortcuts == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(shortcuts)))
		for _, _item := range shortcuts {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIShortcutChangeCallback, "onShortcutsAddedOrUpdated")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ShortcutChangeCallbackProxy) OnShortcutsRemoved(
	ctx context.Context,
	packageName string,
	shortcuts []ShortcutInfo,
	user interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIShortcutChangeCallback)
	_data.WriteString16(packageName)
	if shortcuts == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(shortcuts)))
		for _, _item := range shortcuts {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIShortcutChangeCallback, "onShortcutsRemoved")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
