package pm

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIStagedApexObserver = "android.content.pm.IStagedApexObserver"

const (
	TransactionIStagedApexObserverOnApexStaged = binder.FirstCallTransaction + 0
)

type IStagedApexObserver interface {
	AsBinder() binder.IBinder
	OnApexStaged(ctx context.Context, event ApexStagedEvent) error
}

type StagedApexObserverProxy struct {
	remote binder.IBinder
}

func NewStagedApexObserverProxy(
	remote binder.IBinder,
) *StagedApexObserverProxy {
	return &StagedApexObserverProxy{remote: remote}
}

func (p *StagedApexObserverProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IStagedApexObserver = (*StagedApexObserverProxy)(nil)

func (p *StagedApexObserverProxy) OnApexStaged(
	ctx context.Context,
	event ApexStagedEvent,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIStagedApexObserver)
	if _err := event.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIStagedApexObserver, "onApexStaged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
