// Code generated by genparcelgo. DO NOT EDIT.

package pm

import (
	"github.com/xaionaro-go/binder/parcel"
)

type PackageInfo struct {
	PackageName               string
	VersionCode               int32
	VersionCodeMajor          int32
	VersionName               string
	BaseRevisionCode          int32
	SharedUserId              string
	SharedUserLabel           int32
	FirstInstallTime          int64
	LastUpdateTime            int64
	InstallLocation           int32
	RestrictedAccountType     string
	RequiredAccountType       string
	OverlayTarget             string
	OverlayCategory           string
	OverlayPriority           int32
	OverlayIsStatic           bool
	CompileSdkVersion         int32
	CompileSdkVersionCodename string
	IsApex                    bool
	IsActiveApex              bool
	ArchiveTimeMillis         int64
	// SplitNames: opaque type — not yet supported
	// SplitRevisionCodes: opaque type — not yet supported
	// 1: opaque type — not yet supported
	// Dest: opaque type — not yet supported
	// Gids: opaque type — not yet supported
	// Activities: opaque type — not yet supported
	// Receivers: opaque type — not yet supported
	// Services: opaque type — not yet supported
	// Providers: opaque type — not yet supported
	// Instrumentation: opaque type — not yet supported
	// Permissions: opaque type — not yet supported
	// RequestedPermissions: opaque type — not yet supported
	// RequestedPermissionsFlags: opaque type — not yet supported
	// Signatures: opaque type — not yet supported
	// ConfigPreferences: opaque type — not yet supported
	// ReqFeatures: opaque type — not yet supported
	// FeatureGroups: opaque type — not yet supported
	// Attributions: opaque type — not yet supported
	// IsStub?1:0: opaque type — not yet supported
	// CoreApp?1:0: opaque type — not yet supported
	// RequiredForAllUsers?1:0: opaque type — not yet supported
	// 1: opaque type — not yet supported
	// Dest: opaque type — not yet supported
	// 1: opaque type — not yet supported
	// ApexPackageName: opaque type — not yet supported
}

var _ parcel.Parcelable = (*PackageInfo)(nil)

func (s *PackageInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString(s.PackageName)
	p.WriteInt32(s.VersionCode)
	p.WriteInt32(s.VersionCodeMajor)
	p.WriteString(s.VersionName)
	p.WriteInt32(s.BaseRevisionCode)
	p.WriteString(s.SharedUserId)
	p.WriteInt32(s.SharedUserLabel)
	p.WriteInt64(s.FirstInstallTime)
	p.WriteInt64(s.LastUpdateTime)
	p.WriteInt32(s.InstallLocation)
	p.WriteString(s.RestrictedAccountType)
	p.WriteString(s.RequiredAccountType)
	p.WriteString(s.OverlayTarget)
	p.WriteString(s.OverlayCategory)
	p.WriteInt32(s.OverlayPriority)
	p.WriteBool(s.OverlayIsStatic)
	p.WriteInt32(s.CompileSdkVersion)
	p.WriteString(s.CompileSdkVersionCodename)
	p.WriteBool(s.IsApex)
	p.WriteBool(s.IsActiveApex)
	p.WriteInt64(s.ArchiveTimeMillis)
	return nil
}

func (s *PackageInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.PackageName, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.VersionCode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.VersionCodeMajor, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.VersionName, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.BaseRevisionCode, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.SharedUserId, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.SharedUserLabel, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.FirstInstallTime, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.LastUpdateTime, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.InstallLocation, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.RestrictedAccountType, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.RequiredAccountType, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.OverlayTarget, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.OverlayCategory, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.OverlayPriority, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.OverlayIsStatic, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.CompileSdkVersion, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.CompileSdkVersionCodename, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.IsApex, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.IsActiveApex, _err = p.ReadBool()
	if _err != nil {
		return _err
	}
	s.ArchiveTimeMillis, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
