package pm

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type SignedPackageParcel struct {
	PackageName       string
	CertificateDigest []byte
}

var _ parcel.Parcelable = (*SignedPackageParcel)(nil)

func (s *SignedPackageParcel) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteString16(s.PackageName)
	p.WriteByteArray(s.CertificateDigest)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *SignedPackageParcel) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.PackageName, _err = p.ReadString16()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.CertificateDigest, _err = p.ReadByteArray()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
