package c2

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type IPooledGraphicBufferAllocatorAllocation struct {
	BufferId int32
	Fence    int32
}

var _ parcel.Parcelable = (*IPooledGraphicBufferAllocatorAllocation)(nil)

func (s *IPooledGraphicBufferAllocatorAllocation) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.BufferId)
	p.WriteParcelFileDescriptor(s.Fence)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *IPooledGraphicBufferAllocatorAllocation) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.BufferId, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Fence, _err = p.ReadParcelFileDescriptor()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
