package ad

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	view "github.com/xaionaro-go/binder/android/view"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITvAdClient = "android.media.tv.ad.ITvAdClient"

const (
	TransactionITvAdClientOnSessionCreated            = binder.FirstCallTransaction + 0
	TransactionITvAdClientOnSessionReleased           = binder.FirstCallTransaction + 1
	TransactionITvAdClientOnLayoutSurface             = binder.FirstCallTransaction + 2
	TransactionITvAdClientOnRequestCurrentVideoBounds = binder.FirstCallTransaction + 3
	TransactionITvAdClientOnRequestCurrentChannelUri  = binder.FirstCallTransaction + 4
	TransactionITvAdClientOnRequestTrackInfoList      = binder.FirstCallTransaction + 5
	TransactionITvAdClientOnRequestCurrentTvInputId   = binder.FirstCallTransaction + 6
	TransactionITvAdClientOnRequestSigning            = binder.FirstCallTransaction + 7
	TransactionITvAdClientOnTvAdSessionData           = binder.FirstCallTransaction + 8
)

type ITvAdClient interface {
	AsBinder() binder.IBinder
	OnSessionCreated(ctx context.Context, serviceId string, token binder.IBinder, channel view.InputChannel, seq int32) error
	OnSessionReleased(ctx context.Context, seq int32) error
	OnLayoutSurface(ctx context.Context, left int32, top int32, right int32, bottom int32, seq int32) error
	OnRequestCurrentVideoBounds(ctx context.Context, seq int32) error
	OnRequestCurrentChannelUri(ctx context.Context, seq int32) error
	OnRequestTrackInfoList(ctx context.Context, seq int32) error
	OnRequestCurrentTvInputId(ctx context.Context, seq int32) error
	OnRequestSigning(ctx context.Context, id string, algorithm string, alias string, data []byte, seq int32) error
	OnTvAdSessionData(ctx context.Context, type_ string, data os.Bundle, seq int32) error
}

type TvAdClientProxy struct {
	remote binder.IBinder
}

func NewTvAdClientProxy(
	remote binder.IBinder,
) *TvAdClientProxy {
	return &TvAdClientProxy{remote: remote}
}

func (p *TvAdClientProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITvAdClient = (*TvAdClientProxy)(nil)

func (p *TvAdClientProxy) OnSessionCreated(
	ctx context.Context,
	serviceId string,
	token binder.IBinder,
	channel view.InputChannel,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteString16(serviceId)
	binder.WriteBinderToParcel(ctx, _data, token, p.remote.Transport())
	_data.WriteInt32(1)
	if _err := channel.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onSessionCreated")
	if _err != nil {
		_code = TransactionITvAdClientOnSessionCreated
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnSessionReleased(
	ctx context.Context,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onSessionReleased")
	if _err != nil {
		_code = TransactionITvAdClientOnSessionReleased
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnLayoutSurface(
	ctx context.Context,
	left int32,
	top int32,
	right int32,
	bottom int32,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(left)
	_data.WriteInt32(top)
	_data.WriteInt32(right)
	_data.WriteInt32(bottom)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onLayoutSurface")
	if _err != nil {
		_code = TransactionITvAdClientOnLayoutSurface
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnRequestCurrentVideoBounds(
	ctx context.Context,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onRequestCurrentVideoBounds")
	if _err != nil {
		_code = TransactionITvAdClientOnRequestCurrentVideoBounds
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnRequestCurrentChannelUri(
	ctx context.Context,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onRequestCurrentChannelUri")
	if _err != nil {
		_code = TransactionITvAdClientOnRequestCurrentChannelUri
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnRequestTrackInfoList(
	ctx context.Context,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onRequestTrackInfoList")
	if _err != nil {
		_code = TransactionITvAdClientOnRequestTrackInfoList
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnRequestCurrentTvInputId(
	ctx context.Context,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onRequestCurrentTvInputId")
	if _err != nil {
		_code = TransactionITvAdClientOnRequestCurrentTvInputId
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnRequestSigning(
	ctx context.Context,
	id string,
	algorithm string,
	alias string,
	data []byte,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteString16(id)
	_data.WriteString16(algorithm)
	_data.WriteString16(alias)
	if data == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(data)))
		for _, _item := range data {
			_data.WritePaddedByte(_item)
		}
	}
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onRequestSigning")
	if _err != nil {
		_code = TransactionITvAdClientOnRequestSigning
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TvAdClientProxy) OnTvAdSessionData(
	ctx context.Context,
	type_ string,
	data os.Bundle,
	seq int32,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITvAdClient)
	_data.WriteString16(type_)
	_data.WriteInt32(1)
	if _err := data.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteInt32(seq)

	_code, _err := p.remote.ResolveCode(DescriptorITvAdClient, "onTvAdSessionData")
	if _err != nil {
		_code = TransactionITvAdClientOnTvAdSessionData
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// TvAdClientStub dispatches incoming binder transactions
// to a typed ITvAdClient implementation.
type TvAdClientStub struct {
	Impl ITvAdClient
}

var _ binder.TransactionReceiver = (*TvAdClientStub)(nil)

func (s *TvAdClientStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	switch code {
	case TransactionITvAdClientOnSessionCreated:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_serviceId, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: interface/IBinder param unmarshaling not yet supported in stubs
		var _arg_token binder.IBinder
		_ = _arg_token
		var _arg_channel view.InputChannel
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_channel.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnSessionCreated(ctx, _arg_serviceId, _arg_token, _arg_channel, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnSessionReleased:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnSessionReleased(ctx, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnLayoutSurface:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_left, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_top, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_right, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_bottom, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnLayoutSurface(ctx, _arg_left, _arg_top, _arg_right, _arg_bottom, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnRequestCurrentVideoBounds:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRequestCurrentVideoBounds(ctx, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnRequestCurrentChannelUri:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRequestCurrentChannelUri(ctx, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnRequestTrackInfoList:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRequestTrackInfoList(ctx, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnRequestCurrentTvInputId:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRequestCurrentTvInputId(ctx, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnRequestSigning:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_id, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_algorithm, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		_arg_alias, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		// TODO: array/list param unmarshaling not yet supported in stubs
		var _arg_data []byte
		_ = _arg_data
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnRequestSigning(ctx, _arg_id, _arg_algorithm, _arg_alias, _arg_data, _arg_seq)
		_ = _err
		return nil, nil
	case TransactionITvAdClientOnTvAdSessionData:
		if _, _err := _data.ReadString16(); _err != nil {
			return nil, _err
		}
		_arg_type_, _err := _data.ReadString16()
		if _err != nil {
			return nil, _err
		}
		var _arg_data os.Bundle
		{
			_nullInd, _err := _data.ReadInt32()
			if _err != nil {
				return nil, _err
			}
			if _nullInd != 0 {
				if _err = _arg_data.UnmarshalParcel(_data); _err != nil {
					return nil, _err
				}
			}
		}
		_arg_seq, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnTvAdSessionData(ctx, _arg_type_, _arg_data, _arg_seq)
		_ = _err
		return nil, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// ITvAdClientServer is the server-side interface that user implementations
// provide to NewTvAdClientStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type ITvAdClientServer interface {
	OnSessionCreated(ctx context.Context, serviceId string, token binder.IBinder, channel view.InputChannel, seq int32) error
	OnSessionReleased(ctx context.Context, seq int32) error
	OnLayoutSurface(ctx context.Context, left int32, top int32, right int32, bottom int32, seq int32) error
	OnRequestCurrentVideoBounds(ctx context.Context, seq int32) error
	OnRequestCurrentChannelUri(ctx context.Context, seq int32) error
	OnRequestTrackInfoList(ctx context.Context, seq int32) error
	OnRequestCurrentTvInputId(ctx context.Context, seq int32) error
	OnRequestSigning(ctx context.Context, id string, algorithm string, alias string, data []byte, seq int32) error
	OnTvAdSessionData(ctx context.Context, type_ string, data os.Bundle, seq int32) error
}

type tvAdClientStubWrapper struct {
	impl       ITvAdClientServer
	stubBinder *binder.StubBinder
}

func (w *tvAdClientStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *tvAdClientStubWrapper) OnSessionCreated(
	ctx context.Context,
	serviceId string,
	token binder.IBinder,
	channel view.InputChannel,
	seq int32,
) error {
	return w.impl.OnSessionCreated(ctx, serviceId, token, channel, seq)
}

func (w *tvAdClientStubWrapper) OnSessionReleased(
	ctx context.Context,
	seq int32,
) error {
	return w.impl.OnSessionReleased(ctx, seq)
}

func (w *tvAdClientStubWrapper) OnLayoutSurface(
	ctx context.Context,
	left int32,
	top int32,
	right int32,
	bottom int32,
	seq int32,
) error {
	return w.impl.OnLayoutSurface(ctx, left, top, right, bottom, seq)
}

func (w *tvAdClientStubWrapper) OnRequestCurrentVideoBounds(
	ctx context.Context,
	seq int32,
) error {
	return w.impl.OnRequestCurrentVideoBounds(ctx, seq)
}

func (w *tvAdClientStubWrapper) OnRequestCurrentChannelUri(
	ctx context.Context,
	seq int32,
) error {
	return w.impl.OnRequestCurrentChannelUri(ctx, seq)
}

func (w *tvAdClientStubWrapper) OnRequestTrackInfoList(
	ctx context.Context,
	seq int32,
) error {
	return w.impl.OnRequestTrackInfoList(ctx, seq)
}

func (w *tvAdClientStubWrapper) OnRequestCurrentTvInputId(
	ctx context.Context,
	seq int32,
) error {
	return w.impl.OnRequestCurrentTvInputId(ctx, seq)
}

func (w *tvAdClientStubWrapper) OnRequestSigning(
	ctx context.Context,
	id string,
	algorithm string,
	alias string,
	data []byte,
	seq int32,
) error {
	return w.impl.OnRequestSigning(ctx, id, algorithm, alias, data, seq)
}

func (w *tvAdClientStubWrapper) OnTvAdSessionData(
	ctx context.Context,
	type_ string,
	data os.Bundle,
	seq int32,
) error {
	return w.impl.OnTvAdSessionData(ctx, type_, data, seq)
}

var _ ITvAdClient = (*tvAdClientStubWrapper)(nil)

// NewTvAdClientStub creates a server-side ITvAdClient wrapping the given
// server implementation. The returned value satisfies ITvAdClient
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewTvAdClientStub(
	impl ITvAdClientServer,
) ITvAdClient {
	wrapper := &tvAdClientStubWrapper{impl: impl}
	stub := &TvAdClientStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
