package backup

import (
	"context"
	pm "github.com/xaionaro-go/binder/android/content/pm"
	"github.com/xaionaro-go/binder/binder"
	infra "github.com/xaionaro-go/binder/com/android/internal_/infra"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIBackupTransport = "com.android.internal.backup.IBackupTransport"

const (
	TransactionIBackupTransportName                                      = binder.FirstCallTransaction + 0
	TransactionIBackupTransportConfigurationIntent                       = binder.FirstCallTransaction + 1
	TransactionIBackupTransportCurrentDestinationString                  = binder.FirstCallTransaction + 2
	TransactionIBackupTransportDataManagementIntent                      = binder.FirstCallTransaction + 3
	TransactionIBackupTransportDataManagementIntentLabel                 = binder.FirstCallTransaction + 4
	TransactionIBackupTransportTransportDirName                          = binder.FirstCallTransaction + 5
	TransactionIBackupTransportRequestBackupTime                         = binder.FirstCallTransaction + 6
	TransactionIBackupTransportInitializeDevice                          = binder.FirstCallTransaction + 7
	TransactionIBackupTransportPerformBackup                             = binder.FirstCallTransaction + 8
	TransactionIBackupTransportClearBackupData                           = binder.FirstCallTransaction + 9
	TransactionIBackupTransportFinishBackup                              = binder.FirstCallTransaction + 10
	TransactionIBackupTransportGetAvailableRestoreSets                   = binder.FirstCallTransaction + 11
	TransactionIBackupTransportGetCurrentRestoreSet                      = binder.FirstCallTransaction + 12
	TransactionIBackupTransportStartRestore                              = binder.FirstCallTransaction + 13
	TransactionIBackupTransportNextRestorePackage                        = binder.FirstCallTransaction + 14
	TransactionIBackupTransportGetRestoreData                            = binder.FirstCallTransaction + 15
	TransactionIBackupTransportFinishRestore                             = binder.FirstCallTransaction + 16
	TransactionIBackupTransportRequestFullBackupTime                     = binder.FirstCallTransaction + 17
	TransactionIBackupTransportPerformFullBackup                         = binder.FirstCallTransaction + 18
	TransactionIBackupTransportCheckFullBackupSize                       = binder.FirstCallTransaction + 19
	TransactionIBackupTransportSendBackupData                            = binder.FirstCallTransaction + 20
	TransactionIBackupTransportCancelFullBackup                          = binder.FirstCallTransaction + 21
	TransactionIBackupTransportIsAppEligibleForBackup                    = binder.FirstCallTransaction + 22
	TransactionIBackupTransportGetBackupQuota                            = binder.FirstCallTransaction + 23
	TransactionIBackupTransportGetNextFullRestoreDataChunk               = binder.FirstCallTransaction + 24
	TransactionIBackupTransportAbortFullRestore                          = binder.FirstCallTransaction + 25
	TransactionIBackupTransportGetTransportFlags                         = binder.FirstCallTransaction + 26
	TransactionIBackupTransportGetBackupManagerMonitor                   = binder.FirstCallTransaction + 27
	TransactionIBackupTransportGetPackagesThatShouldNotUseRestrictedMode = binder.FirstCallTransaction + 28
)

type IBackupTransport interface {
	AsBinder() binder.IBinder
	Name(ctx context.Context, result infra.AndroidFuture) error
	ConfigurationIntent(ctx context.Context, resultFuture infra.AndroidFuture) error
	CurrentDestinationString(ctx context.Context, resultFuture infra.AndroidFuture) error
	DataManagementIntent(ctx context.Context, resultFuture infra.AndroidFuture) error
	DataManagementIntentLabel(ctx context.Context, resultFuture infra.AndroidFuture) error
	TransportDirName(ctx context.Context, resultFuture infra.AndroidFuture) error
	RequestBackupTime(ctx context.Context, resultFuture infra.AndroidFuture) error
	InitializeDevice(ctx context.Context, callback ITransportStatusCallback) error
	PerformBackup(ctx context.Context, packageInfo pm.PackageInfo, inFd int32, flags int32, callback ITransportStatusCallback) error
	ClearBackupData(ctx context.Context, packageInfo pm.PackageInfo, callback ITransportStatusCallback) error
	FinishBackup(ctx context.Context, callback ITransportStatusCallback) error
	GetAvailableRestoreSets(ctx context.Context, resultFuture infra.AndroidFuture) error
	GetCurrentRestoreSet(ctx context.Context, resultFuture infra.AndroidFuture) error
	StartRestore(ctx context.Context, token int64, packages []pm.PackageInfo, callback ITransportStatusCallback) error
	NextRestorePackage(ctx context.Context, resultFuture infra.AndroidFuture) error
	GetRestoreData(ctx context.Context, outFd int32, callback ITransportStatusCallback) error
	FinishRestore(ctx context.Context, callback ITransportStatusCallback) error
	RequestFullBackupTime(ctx context.Context, resultFuture infra.AndroidFuture) error
	PerformFullBackup(ctx context.Context, targetPackage pm.PackageInfo, socket int32, flags int32, callback ITransportStatusCallback) error
	CheckFullBackupSize(ctx context.Context, size int64, callback ITransportStatusCallback) error
	SendBackupData(ctx context.Context, numBytes int32, callback ITransportStatusCallback) error
	CancelFullBackup(ctx context.Context, callback ITransportStatusCallback) error
	IsAppEligibleForBackup(ctx context.Context, targetPackage pm.PackageInfo, isFullBackup bool, resultFuture infra.AndroidFuture) error
	GetBackupQuota(ctx context.Context, packageName string, isFullBackup bool, resultFuture infra.AndroidFuture) error
	GetNextFullRestoreDataChunk(ctx context.Context, socket int32, callback ITransportStatusCallback) error
	AbortFullRestore(ctx context.Context, callback ITransportStatusCallback) error
	GetTransportFlags(ctx context.Context, resultFuture infra.AndroidFuture) error
	GetBackupManagerMonitor(ctx context.Context, resultFuture infra.AndroidFuture) error
	GetPackagesThatShouldNotUseRestrictedMode(ctx context.Context, packageNames []string, operationType int32, resultFuture infra.AndroidFuture) error
}

type BackupTransportProxy struct {
	remote binder.IBinder
}

func NewBackupTransportProxy(
	remote binder.IBinder,
) *BackupTransportProxy {
	return &BackupTransportProxy{remote: remote}
}

func (p *BackupTransportProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IBackupTransport = (*BackupTransportProxy)(nil)

func (p *BackupTransportProxy) Name(
	ctx context.Context,
	result infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := result.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "name")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) ConfigurationIntent(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "configurationIntent")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) CurrentDestinationString(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "currentDestinationString")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) DataManagementIntent(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "dataManagementIntent")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) DataManagementIntentLabel(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "dataManagementIntentLabel")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) TransportDirName(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "transportDirName")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) RequestBackupTime(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "requestBackupTime")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) InitializeDevice(
	ctx context.Context,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "initializeDevice")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) PerformBackup(
	ctx context.Context,
	packageInfo pm.PackageInfo,
	inFd int32,
	flags int32,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := packageInfo.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteFileDescriptor(inFd)
	_data.WriteInt32(flags)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "performBackup")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) ClearBackupData(
	ctx context.Context,
	packageInfo pm.PackageInfo,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := packageInfo.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "clearBackupData")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) FinishBackup(
	ctx context.Context,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "finishBackup")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetAvailableRestoreSets(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getAvailableRestoreSets")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetCurrentRestoreSet(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getCurrentRestoreSet")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) StartRestore(
	ctx context.Context,
	token int64,
	packages []pm.PackageInfo,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteInt64(token)
	if packages == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packages)))
		for _, _item := range packages {
			if _err := _item.MarshalParcel(_data); _err != nil {
				return _err
			}
		}
	}
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "startRestore")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) NextRestorePackage(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "nextRestorePackage")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetRestoreData(
	ctx context.Context,
	outFd int32,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteFileDescriptor(outFd)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getRestoreData")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) FinishRestore(
	ctx context.Context,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "finishRestore")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) RequestFullBackupTime(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "requestFullBackupTime")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) PerformFullBackup(
	ctx context.Context,
	targetPackage pm.PackageInfo,
	socket int32,
	flags int32,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := targetPackage.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteFileDescriptor(socket)
	_data.WriteInt32(flags)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "performFullBackup")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) CheckFullBackupSize(
	ctx context.Context,
	size int64,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteInt64(size)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "checkFullBackupSize")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) SendBackupData(
	ctx context.Context,
	numBytes int32,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteInt32(numBytes)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "sendBackupData")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) CancelFullBackup(
	ctx context.Context,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "cancelFullBackup")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) IsAppEligibleForBackup(
	ctx context.Context,
	targetPackage pm.PackageInfo,
	isFullBackup bool,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := targetPackage.MarshalParcel(_data); _err != nil {
		return _err
	}
	_data.WriteBool(isFullBackup)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "isAppEligibleForBackup")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetBackupQuota(
	ctx context.Context,
	packageName string,
	isFullBackup bool,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteString16(packageName)
	_data.WriteBool(isFullBackup)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getBackupQuota")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetNextFullRestoreDataChunk(
	ctx context.Context,
	socket int32,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteFileDescriptor(socket)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getNextFullRestoreDataChunk")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) AbortFullRestore(
	ctx context.Context,
	callback ITransportStatusCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "abortFullRestore")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetTransportFlags(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getTransportFlags")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetBackupManagerMonitor(
	ctx context.Context,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getBackupManagerMonitor")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *BackupTransportProxy) GetPackagesThatShouldNotUseRestrictedMode(
	ctx context.Context,
	packageNames []string,
	operationType int32,
	resultFuture infra.AndroidFuture,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIBackupTransport)
	if packageNames == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(packageNames)))
		for _, _item := range packageNames {
			_data.WriteString16(_item)
		}
	}
	_data.WriteInt32(operationType)
	if _err := resultFuture.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIBackupTransport, "getPackagesThatShouldNotUseRestrictedMode")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
