package GnssAssistance

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type GnssSatelliteCorrections struct {
	Svid                    int32
	InonosphericCorrections []interface{}
}

var _ parcel.Parcelable = (*GnssSatelliteCorrections)(nil)

func (s *GnssSatelliteCorrections) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.Svid)
	if s.InonosphericCorrections == nil {
		p.WriteInt32(-1)
	} else {
		p.WriteInt32(int32(len(s.InonosphericCorrections)))
	}

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *GnssSatelliteCorrections) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	s.Svid, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	var _count0 int32
	_count0, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	if _count0 >= 0 {
		s.InonosphericCorrections = make([]interface{}, _count0)
		for _i := int32(0); _i < _count0; _i++ {
		}
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
