package watchdog

import (
	"context"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIExplicitHealthCheckService = "android.service.watchdog.IExplicitHealthCheckService"

const (
	TransactionIExplicitHealthCheckServiceSetCallback          = binder.FirstCallTransaction + 0
	TransactionIExplicitHealthCheckServiceRequest              = binder.FirstCallTransaction + 1
	TransactionIExplicitHealthCheckServiceCancel               = binder.FirstCallTransaction + 2
	TransactionIExplicitHealthCheckServiceGetSupportedPackages = binder.FirstCallTransaction + 3
	TransactionIExplicitHealthCheckServiceGetRequestedPackages = binder.FirstCallTransaction + 4
)

type IExplicitHealthCheckService interface {
	AsBinder() binder.IBinder
	SetCallback(ctx context.Context, callback *os.RemoteCallback) error
	Request(ctx context.Context, packageName string) error
	Cancel(ctx context.Context, packageName string) error
	GetSupportedPackages(ctx context.Context, callback os.RemoteCallback) error
	GetRequestedPackages(ctx context.Context, callback os.RemoteCallback) error
}

type ExplicitHealthCheckServiceProxy struct {
	remote binder.IBinder
}

func NewExplicitHealthCheckServiceProxy(
	remote binder.IBinder,
) *ExplicitHealthCheckServiceProxy {
	return &ExplicitHealthCheckServiceProxy{remote: remote}
}

func (p *ExplicitHealthCheckServiceProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IExplicitHealthCheckService = (*ExplicitHealthCheckServiceProxy)(nil)

func (p *ExplicitHealthCheckServiceProxy) SetCallback(
	ctx context.Context,
	callback *os.RemoteCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIExplicitHealthCheckService)
	if callback != nil {
		if _err := (*callback).MarshalParcel(_data); _err != nil {
			return _err
		}
	} else {
		_data.WriteInt32(-1)
	}

	_code, _err := p.remote.ResolveCode(DescriptorIExplicitHealthCheckService, "setCallback")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ExplicitHealthCheckServiceProxy) Request(
	ctx context.Context,
	packageName string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIExplicitHealthCheckService)
	_data.WriteString16(packageName)

	_code, _err := p.remote.ResolveCode(DescriptorIExplicitHealthCheckService, "request")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ExplicitHealthCheckServiceProxy) Cancel(
	ctx context.Context,
	packageName string,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIExplicitHealthCheckService)
	_data.WriteString16(packageName)

	_code, _err := p.remote.ResolveCode(DescriptorIExplicitHealthCheckService, "cancel")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ExplicitHealthCheckServiceProxy) GetSupportedPackages(
	ctx context.Context,
	callback os.RemoteCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIExplicitHealthCheckService)
	if _err := callback.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIExplicitHealthCheckService, "getSupportedPackages")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *ExplicitHealthCheckServiceProxy) GetRequestedPackages(
	ctx context.Context,
	callback os.RemoteCallback,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIExplicitHealthCheckService)
	if _err := callback.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIExplicitHealthCheckService, "getRequestedPackages")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
