package app

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIAlarmListener = "android.app.IAlarmListener"

const (
	TransactionIAlarmListenerDoAlarm = binder.FirstCallTransaction + 0
)

type IAlarmListener interface {
	AsBinder() binder.IBinder
	DoAlarm(ctx context.Context, callback IAlarmCompleteListener) error
}

type AlarmListenerProxy struct {
	remote binder.IBinder
}

func NewAlarmListenerProxy(
	remote binder.IBinder,
) *AlarmListenerProxy {
	return &AlarmListenerProxy{remote: remote}
}

func (p *AlarmListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IAlarmListener = (*AlarmListenerProxy)(nil)

func (p *AlarmListenerProxy) DoAlarm(
	ctx context.Context,
	callback IAlarmCompleteListener,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIAlarmListener)
	_data.WriteStrongBinder(callback.AsBinder().Handle())

	_code, _err := p.remote.ResolveCode(DescriptorIAlarmListener, "doAlarm")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
