package app

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIScreenCaptureObserver = "android.app.IScreenCaptureObserver"

const (
	TransactionIScreenCaptureObserverOnScreenCaptured = binder.FirstCallTransaction + 0
)

const (
	MethodIScreenCaptureObserverOnScreenCaptured = "onScreenCaptured"
)

type IScreenCaptureObserver interface {
	AsBinder() binder.IBinder
	OnScreenCaptured(ctx context.Context) error
}

type ScreenCaptureObserverProxy struct {
	Remote binder.IBinder
}

func NewScreenCaptureObserverProxy(
	remote binder.IBinder,
) *ScreenCaptureObserverProxy {
	return &ScreenCaptureObserverProxy{Remote: remote}
}

func (p *ScreenCaptureObserverProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IScreenCaptureObserver = (*ScreenCaptureObserverProxy)(nil)

func (p *ScreenCaptureObserverProxy) OnScreenCaptured(
	ctx context.Context,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIScreenCaptureObserver)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIScreenCaptureObserver, MethodIScreenCaptureObserverOnScreenCaptured)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIScreenCaptureObserver, MethodIScreenCaptureObserverOnScreenCaptured, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// ScreenCaptureObserverStub dispatches incoming binder transactions
// to a typed IScreenCaptureObserver implementation.
type ScreenCaptureObserverStub struct {
	Impl      IScreenCaptureObserver
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*ScreenCaptureObserverStub)(nil)

func (s *ScreenCaptureObserverStub) Descriptor() string {
	return DescriptorIScreenCaptureObserver
}

func (s *ScreenCaptureObserverStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIScreenCaptureObserverOnScreenCaptured:
		_err := s.Impl.OnScreenCaptured(ctx)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IScreenCaptureObserverServer is the server-side interface that user implementations
// provide to NewScreenCaptureObserverStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IScreenCaptureObserverServer interface {
	OnScreenCaptured(ctx context.Context) error
}

type screenCaptureObserverStubWrapper struct {
	impl       IScreenCaptureObserverServer
	stubBinder *binder.StubBinder
}

func (w *screenCaptureObserverStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *screenCaptureObserverStubWrapper) OnScreenCaptured(
	ctx context.Context,
) error {
	return w.impl.OnScreenCaptured(ctx)
}

var _ IScreenCaptureObserver = (*screenCaptureObserverStubWrapper)(nil)

// NewScreenCaptureObserverStub creates a server-side IScreenCaptureObserver wrapping the given
// server implementation. The returned value satisfies IScreenCaptureObserver
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewScreenCaptureObserverStub(
	impl IScreenCaptureObserverServer,
) IScreenCaptureObserver {
	wrapper := &screenCaptureObserverStubWrapper{impl: impl}
	stub := &ScreenCaptureObserverStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
