package app

import (
	"context"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorITransientNotificationCallback = "android.app.ITransientNotificationCallback"

const (
	TransactionITransientNotificationCallbackOnToastShown  = binder.FirstCallTransaction + 0
	TransactionITransientNotificationCallbackOnToastHidden = binder.FirstCallTransaction + 1
)

type ITransientNotificationCallback interface {
	AsBinder() binder.IBinder
	OnToastShown(ctx context.Context) error
	OnToastHidden(ctx context.Context) error
}

type TransientNotificationCallbackProxy struct {
	remote binder.IBinder
}

func NewTransientNotificationCallbackProxy(
	remote binder.IBinder,
) *TransientNotificationCallbackProxy {
	return &TransientNotificationCallbackProxy{remote: remote}
}

func (p *TransientNotificationCallbackProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ ITransientNotificationCallback = (*TransientNotificationCallbackProxy)(nil)

func (p *TransientNotificationCallbackProxy) OnToastShown(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITransientNotificationCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITransientNotificationCallback, "onToastShown")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *TransientNotificationCallbackProxy) OnToastHidden(
	ctx context.Context,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorITransientNotificationCallback)

	_code, _err := p.remote.ResolveCode(DescriptorITransientNotificationCallback, "onToastHidden")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
