package app

import (
	"context"
	"fmt"
	os "github.com/xaionaro-go/binder/android/os"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIUserSwitchObserver = "android.app.IUserSwitchObserver"

const (
	TransactionIUserSwitchObserverOnBeforeUserSwitching     = binder.FirstCallTransaction + 0
	TransactionIUserSwitchObserverOnUserSwitching           = binder.FirstCallTransaction + 1
	TransactionIUserSwitchObserverOnUserSwitchComplete      = binder.FirstCallTransaction + 2
	TransactionIUserSwitchObserverOnForegroundProfileSwitch = binder.FirstCallTransaction + 3
	TransactionIUserSwitchObserverOnLockedBootComplete      = binder.FirstCallTransaction + 4
)

const (
	MethodIUserSwitchObserverOnBeforeUserSwitching     = "onBeforeUserSwitching"
	MethodIUserSwitchObserverOnUserSwitching           = "onUserSwitching"
	MethodIUserSwitchObserverOnUserSwitchComplete      = "onUserSwitchComplete"
	MethodIUserSwitchObserverOnForegroundProfileSwitch = "onForegroundProfileSwitch"
	MethodIUserSwitchObserverOnLockedBootComplete      = "onLockedBootComplete"
)

type IUserSwitchObserver interface {
	AsBinder() binder.IBinder
	OnBeforeUserSwitching(ctx context.Context, newUserId int32) error
	OnUserSwitching(ctx context.Context, newUserId int32, reply os.IRemoteCallback) error
	OnUserSwitchComplete(ctx context.Context, newUserId int32) error
	OnForegroundProfileSwitch(ctx context.Context, newProfileId int32) error
	OnLockedBootComplete(ctx context.Context, newUserId int32) error
}

type UserSwitchObserverProxy struct {
	Remote binder.IBinder
}

func NewUserSwitchObserverProxy(
	remote binder.IBinder,
) *UserSwitchObserverProxy {
	return &UserSwitchObserverProxy{Remote: remote}
}

func (p *UserSwitchObserverProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IUserSwitchObserver = (*UserSwitchObserverProxy)(nil)

func (p *UserSwitchObserverProxy) OnBeforeUserSwitching(
	ctx context.Context,
	newUserId int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIUserSwitchObserver)
	_data.WriteInt32(newUserId)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnBeforeUserSwitching)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnBeforeUserSwitching, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *UserSwitchObserverProxy) OnUserSwitching(
	ctx context.Context,
	newUserId int32,
	reply os.IRemoteCallback,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIUserSwitchObserver)
	_data.WriteInt32(newUserId)
	binder.WriteBinderToParcel(ctx, _data, reply.AsBinder(), p.Remote.Transport())

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnUserSwitching)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnUserSwitching, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *UserSwitchObserverProxy) OnUserSwitchComplete(
	ctx context.Context,
	newUserId int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIUserSwitchObserver)
	_data.WriteInt32(newUserId)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnUserSwitchComplete)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnUserSwitchComplete, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *UserSwitchObserverProxy) OnForegroundProfileSwitch(
	ctx context.Context,
	newProfileId int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIUserSwitchObserver)
	_data.WriteInt32(newProfileId)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnForegroundProfileSwitch)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnForegroundProfileSwitch, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

func (p *UserSwitchObserverProxy) OnLockedBootComplete(
	ctx context.Context,
	newUserId int32,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIUserSwitchObserver)
	_data.WriteInt32(newUserId)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnLockedBootComplete)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIUserSwitchObserver, MethodIUserSwitchObserverOnLockedBootComplete, _err)
	}

	_, _err = p.Remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}

// UserSwitchObserverStub dispatches incoming binder transactions
// to a typed IUserSwitchObserver implementation.
type UserSwitchObserverStub struct {
	Impl      IUserSwitchObserver
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*UserSwitchObserverStub)(nil)

func (s *UserSwitchObserverStub) Descriptor() string {
	return DescriptorIUserSwitchObserver
}

func (s *UserSwitchObserverStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIUserSwitchObserverOnBeforeUserSwitching:
		_arg_newUserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnBeforeUserSwitching(ctx, _arg_newUserId)
		return nil, _err
	case TransactionIUserSwitchObserverOnUserSwitching:
		_arg_newUserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		var _arg_reply os.IRemoteCallback
		{
			_replyHandle, _err := _data.ReadStrongBinder()
			if _err != nil {
				return nil, _err
			}
			_arg_reply = os.NewRemoteCallbackProxy(binder.NewProxyBinder(s.Transport, binder.CallerIdentity{}, _replyHandle))
		}
		_err = s.Impl.OnUserSwitching(ctx, _arg_newUserId, _arg_reply)
		return nil, _err
	case TransactionIUserSwitchObserverOnUserSwitchComplete:
		_arg_newUserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnUserSwitchComplete(ctx, _arg_newUserId)
		return nil, _err
	case TransactionIUserSwitchObserverOnForegroundProfileSwitch:
		_arg_newProfileId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnForegroundProfileSwitch(ctx, _arg_newProfileId)
		return nil, _err
	case TransactionIUserSwitchObserverOnLockedBootComplete:
		_arg_newUserId, _err := _data.ReadInt32()
		if _err != nil {
			return nil, _err
		}
		_err = s.Impl.OnLockedBootComplete(ctx, _arg_newUserId)
		return nil, _err
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IUserSwitchObserverServer is the server-side interface that user implementations
// provide to NewUserSwitchObserverStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IUserSwitchObserverServer interface {
	OnBeforeUserSwitching(ctx context.Context, newUserId int32) error
	OnUserSwitching(ctx context.Context, newUserId int32, reply os.IRemoteCallback) error
	OnUserSwitchComplete(ctx context.Context, newUserId int32) error
	OnForegroundProfileSwitch(ctx context.Context, newProfileId int32) error
	OnLockedBootComplete(ctx context.Context, newUserId int32) error
}

type userSwitchObserverStubWrapper struct {
	impl       IUserSwitchObserverServer
	stubBinder *binder.StubBinder
}

func (w *userSwitchObserverStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *userSwitchObserverStubWrapper) OnBeforeUserSwitching(
	ctx context.Context,
	newUserId int32,
) error {
	return w.impl.OnBeforeUserSwitching(ctx, newUserId)
}

func (w *userSwitchObserverStubWrapper) OnUserSwitching(
	ctx context.Context,
	newUserId int32,
	reply os.IRemoteCallback,
) error {
	return w.impl.OnUserSwitching(ctx, newUserId, reply)
}

func (w *userSwitchObserverStubWrapper) OnUserSwitchComplete(
	ctx context.Context,
	newUserId int32,
) error {
	return w.impl.OnUserSwitchComplete(ctx, newUserId)
}

func (w *userSwitchObserverStubWrapper) OnForegroundProfileSwitch(
	ctx context.Context,
	newProfileId int32,
) error {
	return w.impl.OnForegroundProfileSwitch(ctx, newProfileId)
}

func (w *userSwitchObserverStubWrapper) OnLockedBootComplete(
	ctx context.Context,
	newUserId int32,
) error {
	return w.impl.OnLockedBootComplete(ctx, newUserId)
}

var _ IUserSwitchObserver = (*userSwitchObserverStubWrapper)(nil)

// NewUserSwitchObserverStub creates a server-side IUserSwitchObserver wrapping the given
// server implementation. The returned value satisfies IUserSwitchObserver
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewUserSwitchObserverStub(
	impl IUserSwitchObserverServer,
) IUserSwitchObserver {
	wrapper := &userSwitchObserverStubWrapper{impl: impl}
	stub := &UserSwitchObserverStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
