package types

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type Location struct {
	Provider                     string
	FieldsMask                   int32
	TimeMs                       int64
	ElapsedRealtimeNs            int64
	ElapsedRealtimeUncertaintyNs float64
	LatitudeDegrees              float64
	LongitudeDegrees             float64
	AltitudeMeters               float64
	SpeedMetersPerSecond         float32
	BearingDegrees               float32
	HorizontalAccuracyMeters     float32
	AltitudeAccuracyMeters       float32
	SpeedAccuracyMetersPerSecond float32
	BearingAccuracyDegrees       float32
	MslAltitudeMeters            float64
	MslAltitudeAccuracyMeters    float32
}

var _ parcel.Parcelable = (*Location)(nil)

func (s *Location) MarshalParcel(
	p *parcel.Parcel,
) error {
	p.WriteString(s.Provider)
	p.WriteInt32(s.FieldsMask)
	p.WriteInt64(s.TimeMs)
	p.WriteInt64(s.ElapsedRealtimeNs)
	if s.FieldsMask&256 != 0 {
		p.WriteFloat64(s.ElapsedRealtimeUncertaintyNs)
	}
	p.WriteFloat64(s.LatitudeDegrees)
	p.WriteFloat64(s.LongitudeDegrees)
	if s.FieldsMask&1 != 0 {
		p.WriteFloat64(s.AltitudeMeters)
	}
	if s.FieldsMask&2 != 0 {
		p.WriteFloat32(s.SpeedMetersPerSecond)
	}
	if s.FieldsMask&4 != 0 {
		p.WriteFloat32(s.BearingDegrees)
	}
	if s.FieldsMask&8 != 0 {
		p.WriteFloat32(s.HorizontalAccuracyMeters)
	}
	if s.FieldsMask&32 != 0 {
		p.WriteFloat32(s.AltitudeAccuracyMeters)
	}
	if s.FieldsMask&64 != 0 {
		p.WriteFloat32(s.SpeedAccuracyMetersPerSecond)
	}
	if s.FieldsMask&128 != 0 {
		p.WriteFloat32(s.BearingAccuracyDegrees)
	}
	if s.FieldsMask&512 != 0 {
		p.WriteFloat64(s.MslAltitudeMeters)
	}
	if s.FieldsMask&1024 != 0 {
		p.WriteFloat32(s.MslAltitudeAccuracyMeters)
	}
	p.WriteInt32(-1) // null Extras (Bundle)
	return nil
}

func (s *Location) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	var _err error
	s.Provider, _err = p.ReadString()
	if _err != nil {
		return _err
	}
	s.FieldsMask, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}
	s.TimeMs, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	s.ElapsedRealtimeNs, _err = p.ReadInt64()
	if _err != nil {
		return _err
	}
	if s.FieldsMask&256 != 0 {
		s.ElapsedRealtimeUncertaintyNs, _err = p.ReadFloat64()
		if _err != nil {
			return _err
		}
	}
	s.LatitudeDegrees, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	s.LongitudeDegrees, _err = p.ReadFloat64()
	if _err != nil {
		return _err
	}
	if s.FieldsMask&1 != 0 {
		s.AltitudeMeters, _err = p.ReadFloat64()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&2 != 0 {
		s.SpeedMetersPerSecond, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&4 != 0 {
		s.BearingDegrees, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&8 != 0 {
		s.HorizontalAccuracyMeters, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&32 != 0 {
		s.AltitudeAccuracyMeters, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&64 != 0 {
		s.SpeedAccuracyMetersPerSecond, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&128 != 0 {
		s.BearingAccuracyDegrees, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&512 != 0 {
		s.MslAltitudeMeters, _err = p.ReadFloat64()
		if _err != nil {
			return _err
		}
	}
	if s.FieldsMask&1024 != 0 {
		s.MslAltitudeAccuracyMeters, _err = p.ReadFloat32()
		if _err != nil {
			return _err
		}
	}
	{
		_opaqueLen, _opaqueErr := p.ReadInt32()
		if _opaqueErr != nil {
			return _opaqueErr
		}
		if _opaqueLen > 0 {
			p.SetPosition(p.Position() + int(_opaqueLen))
		}
	}
	return nil
}
