package tunerresourcemanager

import (
	"context"
	"fmt"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIResourcesReclaimListener = "android.media.tv.tunerresourcemanager.IResourcesReclaimListener"

const (
	TransactionIResourcesReclaimListenerOnReclaimResources = binder.FirstCallTransaction + 0
)

const (
	MethodIResourcesReclaimListenerOnReclaimResources = "onReclaimResources"
)

type IResourcesReclaimListener interface {
	AsBinder() binder.IBinder
	OnReclaimResources(ctx context.Context) error
}

type ResourcesReclaimListenerProxy struct {
	Remote binder.IBinder
}

func NewResourcesReclaimListenerProxy(
	remote binder.IBinder,
) *ResourcesReclaimListenerProxy {
	return &ResourcesReclaimListenerProxy{Remote: remote}
}

func (p *ResourcesReclaimListenerProxy) AsBinder() binder.IBinder {
	return p.Remote
}

var _ IResourcesReclaimListener = (*ResourcesReclaimListenerProxy)(nil)

func (p *ResourcesReclaimListenerProxy) OnReclaimResources(
	ctx context.Context,
) error {
	_data := parcel.New()
	defer _data.Recycle()
	_data.WriteInterfaceToken(DescriptorIResourcesReclaimListener)

	_code, _err := p.Remote.ResolveCode(ctx, DescriptorIResourcesReclaimListener, MethodIResourcesReclaimListenerOnReclaimResources)
	if _err != nil {
		return fmt.Errorf("resolving %s.%s: %w", DescriptorIResourcesReclaimListener, MethodIResourcesReclaimListenerOnReclaimResources, _err)
	}

	_reply, _err := p.Remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _err
	}

	return nil
}

// ResourcesReclaimListenerStub dispatches incoming binder transactions
// to a typed IResourcesReclaimListener implementation.
type ResourcesReclaimListenerStub struct {
	Impl      IResourcesReclaimListener
	Transport binder.VersionAwareTransport
}

var _ binder.TransactionReceiver = (*ResourcesReclaimListenerStub)(nil)

func (s *ResourcesReclaimListenerStub) Descriptor() string {
	return DescriptorIResourcesReclaimListener
}

func (s *ResourcesReclaimListenerStub) OnTransaction(
	ctx context.Context,
	code binder.TransactionCode,
	_data *parcel.Parcel,
) (*parcel.Parcel, error) {
	if _, _err := _data.ReadInterfaceToken(); _err != nil {
		return nil, _err
	}

	switch code {
	case TransactionIResourcesReclaimListenerOnReclaimResources:
		_err := s.Impl.OnReclaimResources(ctx)
		_reply := parcel.New()
		if _err != nil {
			binder.WriteStatus(_reply, _err)
			return _reply, nil
		}
		binder.WriteStatus(_reply, nil)
		return _reply, nil
	default:
		return nil, fmt.Errorf("unknown transaction code %d", code)
	}
}

// IResourcesReclaimListenerServer is the server-side interface that user implementations
// provide to NewResourcesReclaimListenerStub. It contains only the business methods,
// without AsBinder (which is provided by the stub itself).
type IResourcesReclaimListenerServer interface {
	OnReclaimResources(ctx context.Context) error
}

type resourcesReclaimListenerStubWrapper struct {
	impl       IResourcesReclaimListenerServer
	stubBinder *binder.StubBinder
}

func (w *resourcesReclaimListenerStubWrapper) AsBinder() binder.IBinder {
	return w.stubBinder
}

func (w *resourcesReclaimListenerStubWrapper) OnReclaimResources(
	ctx context.Context,
) error {
	return w.impl.OnReclaimResources(ctx)
}

var _ IResourcesReclaimListener = (*resourcesReclaimListenerStubWrapper)(nil)

// NewResourcesReclaimListenerStub creates a server-side IResourcesReclaimListener wrapping the given
// server implementation. The returned value satisfies IResourcesReclaimListener
// and can be passed to proxy methods; its AsBinder() returns a
// *binder.StubBinder that is auto-registered with the binder
// driver on first use.
func NewResourcesReclaimListenerStub(
	impl IResourcesReclaimListenerServer,
) IResourcesReclaimListener {
	wrapper := &resourcesReclaimListenerStubWrapper{impl: impl}
	stub := &ResourcesReclaimListenerStub{Impl: wrapper}
	wrapper.stubBinder = binder.NewStubBinder(stub)
	return wrapper
}
