package tunerresourcemanager

import (
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

type TunerDemuxInfo struct {
	Handle      int32
	FilterTypes int32
}

var _ parcel.Parcelable = (*TunerDemuxInfo)(nil)

func (s *TunerDemuxInfo) MarshalParcel(
	p *parcel.Parcel,
) error {
	_headerPos := parcel.WriteParcelableHeader(p)
	p.WriteInt32(s.Handle)
	p.WriteInt32(s.FilterTypes)

	parcel.WriteParcelableFooter(p, _headerPos)
	return nil
}

func (s *TunerDemuxInfo) UnmarshalParcel(
	p *parcel.Parcel,
) error {
	_endPos, _err := parcel.ReadParcelableHeader(p)
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.Handle, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	if p.Position() >= _endPos {
		parcel.SkipToParcelableEnd(p, _endPos)
		return nil
	}

	s.FilterTypes, _err = p.ReadInt32()
	if _err != nil {
		return _err
	}

	parcel.SkipToParcelableEnd(p, _endPos)
	return nil
}
