package session

import (
	"context"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIOnMediaKeyEventSessionChangedListener = "android.media.session.IOnMediaKeyEventSessionChangedListener"

const (
	TransactionIOnMediaKeyEventSessionChangedListenerOnMediaKeyEventSessionChanged = binder.FirstCallTransaction + 0
)

type IOnMediaKeyEventSessionChangedListener interface {
	AsBinder() binder.IBinder
	OnMediaKeyEventSessionChanged(ctx context.Context, packageName string, mediaKeyEventSessionToken MediaSessionToken) error
}

type OnMediaKeyEventSessionChangedListenerProxy struct {
	remote binder.IBinder
}

func NewOnMediaKeyEventSessionChangedListenerProxy(
	remote binder.IBinder,
) *OnMediaKeyEventSessionChangedListenerProxy {
	return &OnMediaKeyEventSessionChangedListenerProxy{remote: remote}
}

func (p *OnMediaKeyEventSessionChangedListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IOnMediaKeyEventSessionChangedListener = (*OnMediaKeyEventSessionChangedListenerProxy)(nil)

func (p *OnMediaKeyEventSessionChangedListenerProxy) OnMediaKeyEventSessionChanged(
	ctx context.Context,
	packageName string,
	mediaKeyEventSessionToken MediaSessionToken,
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIOnMediaKeyEventSessionChangedListener)
	_data.WriteString16(packageName)
	if _err := mediaKeyEventSessionToken.MarshalParcel(_data); _err != nil {
		return _err
	}

	_code, _err := p.remote.ResolveCode(DescriptorIOnMediaKeyEventSessionChangedListener, "onMediaKeyEventSessionChanged")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
