package session

import (
	"context"
	"github.com/xaionaro-go/aidl/binder"
	"github.com/xaionaro-go/aidl/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIOnVolumeKeyLongPressListener = "android.media.session.IOnVolumeKeyLongPressListener"

const (
	TransactionIOnVolumeKeyLongPressListenerOnVolumeKeyLongPress = binder.FirstCallTransaction + 0
)

type IOnVolumeKeyLongPressListener interface {
	AsBinder() binder.IBinder
	OnVolumeKeyLongPress(ctx context.Context, event interface{}) error
}

type OnVolumeKeyLongPressListenerProxy struct {
	remote binder.IBinder
}

func NewOnVolumeKeyLongPressListenerProxy(
	remote binder.IBinder,
) *OnVolumeKeyLongPressListenerProxy {
	return &OnVolumeKeyLongPressListenerProxy{remote: remote}
}

func (p *OnVolumeKeyLongPressListenerProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IOnVolumeKeyLongPressListener = (*OnVolumeKeyLongPressListenerProxy)(nil)

func (p *OnVolumeKeyLongPressListenerProxy) OnVolumeKeyLongPress(
	ctx context.Context,
	event interface{},
) error {
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIOnVolumeKeyLongPressListener)

	_code, _err := p.remote.ResolveCode(DescriptorIOnVolumeKeyLongPressListener, "onVolumeKeyLongPress")
	if _err != nil {
		return _err
	}

	_, _err = p.remote.Transact(ctx, _code, binder.FlagOneway, _data)
	return _err
}
