package stats

import (
	"context"
	"github.com/xaionaro-go/binder/binder"
	"github.com/xaionaro-go/binder/parcel"
)

// Code generated by aidlgen. DO NOT EDIT.

const DescriptorIPowerStats = "android.hardware.power.stats.IPowerStats"

const (
	TransactionIPowerStatsGetPowerEntityInfo    = binder.FirstCallTransaction + 0
	TransactionIPowerStatsGetStateResidency     = binder.FirstCallTransaction + 1
	TransactionIPowerStatsGetEnergyConsumerInfo = binder.FirstCallTransaction + 2
	TransactionIPowerStatsGetEnergyConsumed     = binder.FirstCallTransaction + 3
	TransactionIPowerStatsGetEnergyMeterInfo    = binder.FirstCallTransaction + 4
	TransactionIPowerStatsReadEnergyMeter       = binder.FirstCallTransaction + 5
)

type IPowerStats interface {
	AsBinder() binder.IBinder
	GetPowerEntityInfo(ctx context.Context) ([]PowerEntity, error)
	GetStateResidency(ctx context.Context, powerEntityIds []int32) ([]StateResidencyResult, error)
	GetEnergyConsumerInfo(ctx context.Context) ([]EnergyConsumer, error)
	GetEnergyConsumed(ctx context.Context, energyConsumerIds []int32) ([]EnergyConsumerResult, error)
	GetEnergyMeterInfo(ctx context.Context) ([]Channel, error)
	ReadEnergyMeter(ctx context.Context, channelIds []int32) ([]EnergyMeasurement, error)
}

type PowerStatsProxy struct {
	remote binder.IBinder
}

func NewPowerStatsProxy(
	remote binder.IBinder,
) *PowerStatsProxy {
	return &PowerStatsProxy{remote: remote}
}

func (p *PowerStatsProxy) AsBinder() binder.IBinder {
	return p.remote
}

var _ IPowerStats = (*PowerStatsProxy)(nil)

func (p *PowerStatsProxy) GetPowerEntityInfo(
	ctx context.Context,
) ([]PowerEntity, error) {
	var _result []PowerEntity
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "getPowerEntityInfo")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]PowerEntity, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *PowerStatsProxy) GetStateResidency(
	ctx context.Context,
	powerEntityIds []int32,
) ([]StateResidencyResult, error) {
	var _result []StateResidencyResult
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)
	if powerEntityIds == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(powerEntityIds)))
		for _, _item := range powerEntityIds {
			_data.WriteInt32(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "getStateResidency")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]StateResidencyResult, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *PowerStatsProxy) GetEnergyConsumerInfo(
	ctx context.Context,
) ([]EnergyConsumer, error) {
	var _result []EnergyConsumer
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "getEnergyConsumerInfo")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]EnergyConsumer, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *PowerStatsProxy) GetEnergyConsumed(
	ctx context.Context,
	energyConsumerIds []int32,
) ([]EnergyConsumerResult, error) {
	var _result []EnergyConsumerResult
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)
	if energyConsumerIds == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(energyConsumerIds)))
		for _, _item := range energyConsumerIds {
			_data.WriteInt32(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "getEnergyConsumed")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]EnergyConsumerResult, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *PowerStatsProxy) GetEnergyMeterInfo(
	ctx context.Context,
) ([]Channel, error) {
	var _result []Channel
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "getEnergyMeterInfo")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]Channel, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}

func (p *PowerStatsProxy) ReadEnergyMeter(
	ctx context.Context,
	channelIds []int32,
) ([]EnergyMeasurement, error) {
	var _result []EnergyMeasurement
	_data := parcel.New()
	_data.WriteInterfaceToken(DescriptorIPowerStats)
	if channelIds == nil {
		_data.WriteInt32(-1)
	} else {
		_data.WriteInt32(int32(len(channelIds)))
		for _, _item := range channelIds {
			_data.WriteInt32(_item)
		}
	}

	_code, _err := p.remote.ResolveCode(DescriptorIPowerStats, "readEnergyMeter")
	if _err != nil {
		return _result, _err
	}

	_reply, _err := p.remote.Transact(ctx, _code, 0, _data)
	if _err != nil {
		return _result, _err
	}
	defer _reply.Recycle()

	if _err = binder.ReadStatus(_reply); _err != nil {
		return _result, _err
	}

	_count, _err := _reply.ReadInt32()
	if _err != nil {
		return _result, _err
	}

	if _count >= 0 {
		_result = make([]EnergyMeasurement, _count)
		for _i := int32(0); _i < _count; _i++ {
			if _err = _result[_i].UnmarshalParcel(_reply); _err != nil {
				return _result, _err
			}
		}
	}
	return _result, nil
}
